import "screen_guides.dart";

/// Parent app screen guides, written from each screen's real labels
/// (English from app_en.arb, Hindi from app_hi.arb). See screen_guides.dart.
const List<ScreenGuide> parentScreenGuides = [
  ScreenGuide(
    id: "parent-home",
    titleEn: "Find your way around the home screen",
    titleHi: "होम स्क्रीन पर सब कुछ कैसे ढूँढें",
    stepsEn: [
      "Have more than one child? Tap a child's name at the top to switch between them.",
      "The cards **Fees due**, **Attendance** and **Homework** show today's status — tap one to open it.",
      "Under **Quick access**, tap a tile like **Tutor**, **Transport**, **PTM**, **Leave** or **Gallery**.",
      "Tap **Message a teacher · 8 AM – 8 PM** to reach the class and subject teachers.",
      "Tap the bell icon at the top for **Notices**, and the **Student ID** card for the ID QR.",
      "Use the bottom bar for **Home**, **Fees**, **Messages** and **Profile**.",
    ],
    stepsHi: [
      "एक से ज़्यादा बच्चे हैं? ऊपर बच्चे के नाम पर दबाकर बच्चा बदलें।",
      "**बाकी फ़ीस**, **हाज़िरी** और **होमवर्क** कार्ड आज की स्थिति दिखाते हैं — खोलने के लिए दबाएँ।",
      "**ज़रूरी सुविधाएँ** में **ट्यूटर**, **परिवहन**, **PTM**, **छुट्टी** या **गैलरी** जैसी टाइल दबाएँ।",
      "कक्षा और विषय अध्यापक से बात के लिए **अध्यापक को संदेश भेजें · सुबह 8 – रात 8 बजे** दबाएँ।",
      "ऊपर घंटी वाले निशान से **सूचनाएँ** देखें, और QR के लिए **छात्र पहचान पत्र** कार्ड दबाएँ।",
      "नीचे की पट्टी में **होम**, **फ़ीस**, **संदेश** और **प्रोफ़ाइल** हैं।",
    ],
    tipsEn: [
      "If you see \"Could not reach the school server.\", check your internet and tap **Retry**.",
      "If you see \"No active students found for this account.\", contact the school office.",
      "If WhatsApp does not open, message the school's number shown on the screen yourself.",
    ],
    tipsHi: [
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
      "अगर \"इस खाते से कोई चालू छात्र नहीं जुड़ा है।\" दिखे, तो स्कूल दफ़्तर से बात करें।",
      "अगर व्हाट्सएप न खुले, तो स्क्रीन पर दिखे स्कूल के नंबर पर खुद संदेश भेजें।",
    ],
  ),
  ScreenGuide(
    id: "fees",
    titleEn: "Pay school fees and set up auto-pay",
    titleHi: "स्कूल फीस भरें और ऑटो-पे लगाएँ",
    stepsEn: [
      "Open **Fees** from the bottom bar or the **Fees due** card. **Total due** shows the full amount.",
      "Tick the fees you want to pay now. Under **Pay ahead** you can also tick months not yet due.",
      "Tap **Pay ₹… online** at the bottom of the screen.",
      "Under **How will you pay?**, pick a way. Options marked **No extra charge** cost nothing more.",
      "Finish on the bank page and come back. Paid fees leave the list, usually within a minute.",
      "To pay every month by itself, tap **Set up auto-pay** and approve it on the bank page.",
    ],
    stepsHi: [
      "नीचे की पट्टी से **फ़ीस** या **बाकी फ़ीस** कार्ड खोलें। **कुल देय** में पूरी रकम दिखती है।",
      "जो फ़ीस अभी देनी है उस पर निशान लगाएँ। **पहले से जमा करें** में आगे के महीने भी चुन सकते हैं।",
      "नीचे **₹… ऑनलाइन जमा करें** बटन दबाएँ।",
      "**आप कैसे भुगतान करेंगे?** में तरीक़ा चुनें। **कोई अतिरिक्त शुल्क नहीं** वाले तरीक़े पर कुछ ज़्यादा नहीं लगता।",
      "बैंक के पेज पर भुगतान पूरा करके ऐप में लौटें। जमा फ़ीस आमतौर पर एक मिनट में सूची से हट जाती है।",
      "हर महीने अपने-आप फ़ीस जमा हो, इसके लिए **ऑटो-पे शुरू करें** दबाएँ और बैंक पेज पर मंज़ूरी दें।",
    ],
    tipsEn: [
      "If the button says **Select a fee to pay**, tick at least one fee first.",
      "If you see \"Could not start payment — check your connection\", check your internet and try again.",
      "If you see \"No pending fees — all dues are cleared\", nothing is due. Old receipts are in **Previous receipts**.",
    ],
    tipsHi: [
      "अगर बटन पर **जमा करने के लिए फ़ीस चुनें** लिखा हो, तो पहले कम से कम एक फ़ीस पर निशान लगाएँ।",
      "अगर \"भुगतान शुरू नहीं हो सका — अपना नेटवर्क देखें\" दिखे, तो इंटरनेट देखकर फिर कोशिश करें।",
      "अगर \"कोई फ़ीस बाकी नहीं\" दिखे, तो कुछ बकाया नहीं है। पुरानी रसीदें **पिछली रसीदें** में हैं।",
    ],
  ),
  ScreenGuide(
    id: "attendance-history",
    titleEn: "Check your child's attendance",
    titleHi: "बच्चे की हाज़िरी देखें",
    stepsEn: [
      "On the home screen, tap the **Attendance** card.",
      "The boxes at the top count the days **Present**, **Absent** and **Late** this term.",
      "Scroll down to **Day by day** to see the mark for each school day.",
      "Pull the list down to load the latest marks.",
    ],
    stepsHi: [
      "होम स्क्रीन पर **हाज़िरी** कार्ड दबाएँ।",
      "ऊपर के डिब्बों में इस सत्र के **उपस्थित**, **अनुपस्थित** और **देर से** वाले दिन गिने हैं।",
      "हर दिन की हाज़िरी देखने के लिए नीचे **दिन-प्रतिदिन** तक जाएँ।",
      "ताज़ा हाज़िरी के लिए सूची को नीचे खींचें।",
    ],
    tipsEn: [
      "If you see \"No attendance marked yet this term.\", it appears the day the class teacher marks the register.",
      "If you see \"Could not reach the school server.\", check your internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर \"इस सत्र में अभी हाज़िरी नहीं लगी है।\" दिखे, तो कक्षा अध्यापक के रजिस्टर भरते ही दिखेगी।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "homework-parent",
    titleEn: "See homework and get help with it",
    titleHi: "होमवर्क देखें और उसमें मदद लें",
    stepsEn: [
      "On the home screen, tap the **Homework** card to open **Homework & diary**.",
      "Each item is marked **Homework** or **Diary**, with the subject and the date it is due.",
      "Read the teacher's note with your child and help plan the work.",
      "Stuck? Tap **Ask tutor** on that item — the tutor already knows the assignment.",
      "Pull the list down to see newly posted homework.",
    ],
    stepsHi: [
      "होम स्क्रीन पर **होमवर्क** कार्ड दबाकर **होमवर्क और डायरी** खोलें।",
      "हर काम पर **होमवर्क** या **डायरी** लिखा है, साथ में विषय और जमा करने की तारीख़।",
      "बच्चे के साथ अध्यापक का नोट पढ़ें और काम की योजना बनाएँ।",
      "अटक गए? उस काम पर **ट्यूटर से पूछें** दबाएँ — ट्यूटर को वह काम पहले से पता होगा।",
      "नया होमवर्क देखने के लिए सूची को नीचे खींचें।",
    ],
    tipsEn: [
      "If you see \"No homework posted for this class yet.\", it appears as soon as the teacher publishes it.",
      "If you see \"Could not reach the school server.\", check your internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर \"इस कक्षा के लिए अभी कोई होमवर्क नहीं है।\" दिखे, तो अध्यापक के डालते ही यहाँ आ जाएगा।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "tutor",
    titleEn: "Study at home with the AI tutor",
    titleHi: "एआई ट्यूटर से घर पर पढ़ाई करें",
    stepsEn: [
      "Open **Tutor** from home, or tap **Ask tutor** on a homework item.",
      "Choose the **Reply language**, then pick a mode from the row of buttons.",
      "Type in the box at the bottom, or tap the mic (**Speak your question**) and speak.",
      "Under a reply, tap **Watch videos** for lessons on that topic, or **Report** if it looks wrong.",
      "Hints are free every day. Tap **Get a pass** to unlock the full tutor for a day, week or month.",
      "Tap the ? icon (**How to use the tutor**) for a 30-minute daily routine.",
    ],
    stepsHi: [
      "होम से **ट्यूटर** खोलें, या होमवर्क पर **ट्यूटर से पूछें** दबाएँ।",
      "**उत्तर की भाषा** चुनें, फिर बटनों की पंक्ति से कोई तरीक़ा चुनें।",
      "नीचे के डिब्बे में लिखें, या माइक (**अपना प्रश्न बोलें**) दबाकर बोलें।",
      "उत्तर के नीचे **वीडियो देखें** से उसी विषय के वीडियो, या ग़लत लगे तो **शिकायत करें** दबाएँ।",
      "संकेत रोज़ मुफ़्त हैं। पूरा ट्यूटर एक दिन, हफ़्ते या महीने के लिए खोलने को **पास लें** दबाएँ।",
      "रोज़ 30 मिनट का तरीक़ा जानने के लिए ? निशान (**ट्यूटर कैसे इस्तेमाल करें**) दबाएँ।",
    ],
    tipsEn: [
      "If you see \"needs a pass — hints stay free\", switch to the free hint mode or tap **Get a pass**.",
      "If you see \"Voice input is not available on this phone.\", type your question instead.",
      "If you see \"Could not reach the tutor.\", check your internet and send again.",
    ],
    tipsHi: [
      "अगर \"के लिए पास चाहिए — संकेत (hints) मुफ़्त रहेंगे\" दिखे, तो मुफ़्त संकेत चुनें या **पास लें** दबाएँ।",
      "अगर \"इस फ़ोन में बोलकर लिखना उपलब्ध नहीं है।\" दिखे, तो प्रश्न टाइप करें।",
      "अगर \"ट्यूटर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट जाँचकर फिर भेजें।",
    ],
  ),
  ScreenGuide(
    id: "notices",
    titleEn: "Read school notices and news",
    titleHi: "स्कूल की सूचनाएँ और समाचार पढ़ें",
    stepsEn: [
      "On the home screen, tap the bell icon at the top to open **Notices & news**.",
      "Each item is marked **Notice** or **News**. Pinned ones stay at the top.",
      "Scroll down to read older circulars.",
      "Pull the list down to check for new notices.",
    ],
    stepsHi: [
      "होम स्क्रीन पर ऊपर घंटी वाला निशान दबाकर **नोटिस और समाचार** खोलें।",
      "हर सूचना पर **नोटिस** या **समाचार** लिखा है। पिन वाली सूचनाएँ सबसे ऊपर रहती हैं।",
      "पुराने परिपत्र पढ़ने के लिए नीचे स्क्रॉल करें।",
      "नई सूचना देखने के लिए सूची को नीचे खींचें।",
    ],
    tipsEn: [
      "If you see \"No notices published yet.\", school circulars will appear here when published.",
      "If you see \"Could not reach the school server.\", check your internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर \"अभी कोई सूचना प्रकाशित नहीं है।\" दिखे, तो स्कूल के परिपत्र आते ही यहाँ दिखेंगे।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "transport",
    titleEn: "School bus details and transport requests",
    titleHi: "स्कूल बस की जानकारी और बस का अनुरोध",
    stepsEn: [
      "Tap **Transport** under Quick access to see your child's bus, **Stop** and driver.",
      "Tap **Call** to phone the driver, or **Live bus location** to see the bus on a map.",
      "Tap **See all bus routes and stops** to view every route.",
      "Not on the bus yet? Tap **Request school transport**.",
      "Fill **Pickup address**, **Locality / village** and **Landmark**, then tap **Send request**.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **परिवहन** दबाएँ — बच्चे की बस, **स्टॉप** और ड्राइवर दिखेंगे।",
      "ड्राइवर को फ़ोन के लिए **फ़ोन करें**, या नक्शे पर बस देखने के लिए **बस की लाइव लोकेशन** दबाएँ।",
      "सभी रूट देखने के लिए **सभी बस रूट और स्टॉप देखें** दबाएँ।",
      "अभी बस नहीं लगी? **स्कूल बस के लिए अनुरोध करें** दबाएँ।",
      "**लेने का पता**, **मोहल्ला / गाँव** और **पहचान चिह्न** भरें, फिर **अनुरोध भेजें** दबाएँ।",
    ],
    tipsEn: [
      "If you see \"Driver's number is not on the school's record yet.\", ask the school office for it.",
      "If you see \"Please give the pickup address.\", fill the address before sending.",
      "If you see \"Boarding is paused by the office\", call the school office before sending your child.",
    ],
    tipsHi: [
      "अगर \"चालक का नंबर अभी स्कूल के रिकॉर्ड में नहीं है।\" दिखे, तो स्कूल दफ़्तर से नंबर लें।",
      "अगर \"कृपया लेने का पता बताएँ।\" दिखे, तो भेजने से पहले पता भरें।",
      "अगर \"दफ़्तर ने फ़िलहाल बोर्डिंग रोक रखी है।\" दिखे, तो बच्चे को भेजने से पहले दफ़्तर से बात करें।",
    ],
  ),
  ScreenGuide(
    id: "bus-routes",
    titleEn: "See all school bus routes",
    titleHi: "स्कूल के सभी बस रूट देखें",
    stepsEn: [
      "On the **Transport** screen, tap **See all bus routes and stops**.",
      "**All bus routes** lists each route with its stops in order.",
      "The distance next to each stop is in km.",
      "Not sure which route is your child's? Ask the school office.",
    ],
    stepsHi: [
      "**परिवहन** स्क्रीन पर **सभी बस रूट और स्टॉप देखें** दबाएँ।",
      "**All bus routes** में हर रूट और उसके स्टॉप क्रम से दिखते हैं।",
      "हर स्टॉप के आगे दूरी किलोमीटर (km) में लिखी है।",
      "बच्चा किस रूट पर है, पता न हो तो स्कूल दफ़्तर से पूछें।",
    ],
    tipsEn: [
      "If you see \"No bus routes published yet.\", contact the school office to find your child's route.",
      "If you see \"Could not reach the school server.\", check your internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर \"अभी कोई बस रूट प्रकाशित नहीं है।\" दिखे, तो बच्चे का रूट जानने के लिए दफ़्तर से बात करें।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "bus-live",
    titleEn: "Track the school bus live",
    titleHi: "स्कूल बस को लाइव देखें",
    stepsEn: [
      "On the **Transport** screen, tap **Live bus location**.",
      "The map shows the bus, its speed and when it was last updated.",
      "Read the time to your stop, e.g. About 10 min to your stop — it is an estimate, not a promise.",
      "Tap **Centre on the bus** to bring the bus back to the middle of the map.",
      "Tap **Refresh** for the newest position. It also refreshes by itself.",
    ],
    stepsHi: [
      "**परिवहन** स्क्रीन पर **बस की लाइव लोकेशन** दबाएँ।",
      "नक्शे पर बस, उसकी रफ़्तार और आख़िरी अपडेट का समय दिखता है।",
      "आपके स्टॉप तक का समय देखें — यह अंदाज़ा है, पक्का वादा नहीं।",
      "बस को नक्शे के बीच में लाने के लिए **नक्शे पर बस दिखाएँ** दबाएँ।",
      "नई लोकेशन के लिए **ताज़ा करें** दबाएँ। यह अपने-आप भी ताज़ा होती है।",
    ],
    tipsEn: [
      "If you see \"Bus is not on a school trip now\", live location shows only 06:00–17:30, Mon–Sat.",
      "If you see \"This vehicle has no GPS tracker\", call the driver from the Transport screen.",
      "If you see \"Tracker not reporting right now\", wait — the map checks again every 15 seconds.",
    ],
    tipsHi: [
      "अगर \"बस अभी स्कूल के फेरे पर नहीं है\" दिखे, तो लोकेशन सिर्फ़ 06:00–17:30, सोमवार–शनिवार दिखती है।",
      "अगर \"इस गाड़ी में GPS ट्रैकर नहीं है\" दिखे, तो परिवहन स्क्रीन से ड्राइवर को फ़ोन करें।",
      "अगर \"ट्रैकर अभी लोकेशन नहीं भेज रहा\" दिखे, तो रुकें — नक्शा हर 15 सेकंड में फिर देखता है।",
    ],
  ),
  ScreenGuide(
    id: "online-classes-parent",
    titleEn: "Join your child's online class",
    titleHi: "बच्चे की ऑनलाइन क्लास से जुड़ें",
    stepsEn: [
      "Tap **Online class** under Quick access.",
      "Classes under **Coming up** show the day and time. Past ones are under **Earlier**.",
      "The **Join** button works from 10 minutes before the class starts.",
      "When the class shows **LIVE**, tap **Join now** — Google Meet or the teacher's app opens.",
      "After class, tap **Teacher's questions & my answers** to send your child's answers.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **ऑनलाइन क्लास** दबाएँ।",
      "**आने वाली क्लास** में दिन और समय दिखता है। पुरानी क्लास **पिछली क्लास** में हैं।",
      "**जुड़ें** बटन क्लास शुरू होने से 10 मिनट पहले से काम करता है।",
      "क्लास पर **लाइव** दिखे तो **अभी जुड़ें** दबाएँ — Google Meet या टीचर का ऐप खुलेगा।",
      "क्लास के बाद बच्चे के उत्तर भेजने के लिए **टीचर के प्रश्न और मेरे उत्तर** दबाएँ।",
    ],
    tipsEn: [
      "If the button says **Opens at** a time, it is too early — come back 10 minutes before class.",
      "If you see \"No online class is scheduled\", you will get a notification when the teacher sets one.",
      "If a class shows **Cancelled**, it will not happen — watch for a new one in the list.",
    ],
    tipsHi: [
      "अगर बटन पर **बजे खुलेगी** लिखा हो, तो अभी जल्दी है — क्लास से 10 मिनट पहले आएँ।",
      "अगर \"कोई ऑनलाइन क्लास अभी तय नहीं है\" दिखे, तो टीचर के क्लास तय करते ही सूचना मिलेगी।",
      "अगर क्लास पर **रद्द** लिखा हो, तो वह नहीं होगी — सूची में नई क्लास देखते रहें।",
    ],
  ),
  ScreenGuide(
    id: "online-class-qa-parent",
    titleEn: "Send answers to the teacher's class questions",
    titleHi: "टीचर के प्रश्नों के उत्तर भेजें",
    stepsEn: [
      "On **Online classes**, tap **Teacher's questions & my answers** under the class.",
      "Read each question under **Questions from the teacher**.",
      "Your child writes the answer in the copy.",
      "Tap **Send answer photo**, then **Take a photo of the copy** or **Choose from gallery**.",
      "Wait for the teacher: **Correct ✓**, **Partly right** or **Not correct — try again**.",
      "To answer again, tap **Send again** — you can, until the teacher closes the question.",
    ],
    stepsHi: [
      "**ऑनलाइन क्लास** में क्लास के नीचे **टीचर के प्रश्न और मेरे उत्तर** दबाएँ।",
      "**टीचर के प्रश्न** में हर प्रश्न पढ़ें।",
      "बच्चा उत्तर अपनी कॉपी में लिखे।",
      "**उत्तर की फ़ोटो भेजें** दबाएँ, फिर **कॉपी की फ़ोटो लें** या **गैलरी से चुनें**।",
      "टीचर के जवाब का इंतज़ार करें: **सही ✓**, **आंशिक रूप से सही** या **सही नहीं — फिर से कोशिश करें**।",
      "दोबारा उत्तर के लिए **दोबारा भेजें** दबाएँ — प्रश्न बंद होने तक भेज सकते हैं।",
    ],
    tipsEn: [
      "If you see \"The teacher has not asked a question yet.\", pull the screen down to refresh.",
      "If a question says **closed**, the teacher has stopped taking answers for it.",
      "If it says **Sent · waiting for the teacher**, your photo has reached — no need to send again.",
    ],
    tipsHi: [
      "अगर \"टीचर ने अभी कोई प्रश्न नहीं पूछा है।\" दिखे, तो ताज़ा करने के लिए स्क्रीन नीचे खींचें।",
      "अगर प्रश्न पर **बंद** लिखा हो, तो टीचर अब उसके उत्तर नहीं ले रहे।",
      "अगर **भेज दिया · टीचर के जवाब का इंतज़ार** दिखे, तो फ़ोटो पहुँच गई है — दोबारा भेजने की ज़रूरत नहीं।",
    ],
  ),
  ScreenGuide(
    id: "ebooks",
    titleEn: "Read e-books from the school library",
    titleHi: "स्कूल लाइब्रेरी की ई-बुक पढ़ें",
    stepsEn: [
      "Tap **Library** under Quick access to open **E-books**.",
      "Tap **Open the whole shelf** to see everything the library has published.",
      "Swipe through the books and tap one to open it.",
      "If a **Key** is shown, tap the copy icon next to it, then paste it where the book asks.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **लाइब्रेरी** दबाकर **ई-बुक** खोलें।",
      "पुस्तकालय की सारी किताबें देखने के लिए **पूरी शेल्फ़ खोलें** दबाएँ।",
      "किताबों को खिसकाकर देखें और खोलने के लिए किसी एक पर दबाएँ।",
      "अगर **चाबी (key)** दिखे, तो उसके आगे कॉपी निशान दबाएँ और किताब माँगे तो वहाँ चिपकाएँ।",
    ],
    tipsEn: [
      "If you see \"The school's e-book shelf is not switched on yet.\", check back after the library sets it up.",
      "If you see \"Could not open this book.\", check your internet and tap the book again.",
      "If you see \"No individual books catalogued yet\", use **Open the whole shelf** instead.",
    ],
    tipsHi: [
      "अगर \"स्कूल की ई-बुक शेल्फ़ अभी चालू नहीं है।\" दिखे, तो पुस्तकालय के सेट करने के बाद देखें।",
      "अगर \"यह किताब नहीं खुल सकी।\" दिखे, तो इंटरनेट देखकर किताब फिर से दबाएँ।",
      "अगर \"अभी अलग-अलग किताबें दर्ज नहीं हैं\" दिखे, तो **पूरी शेल्फ़ खोलें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "ptm-parent",
    titleEn: "Book a parent-teacher meeting slot",
    titleHi: "अभिभावक-शिक्षक बैठक (PTM) का समय बुक करें",
    stepsEn: [
      "Tap **PTM** under Quick access to open **Parent-teacher meetings**.",
      "Under **Choose a slot**, find a teacher and time that shows seats left.",
      "Tap the slot, check the details, then tap **Book**.",
      "A green **Booked** line shows the teacher and time — be there on the day.",
      "Can't come? Tap **Cancel** on that green line to free the slot.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **PTM** दबाकर **अभिभावक-शिक्षक बैठक (PTM)** खोलें।",
      "**समय चुनें** में ऐसा अध्यापक और समय ढूँढें जिसमें जगह **बाकी** हो।",
      "समय पर दबाएँ, जानकारी देखें, फिर **बुक करें** दबाएँ।",
      "हरी पट्टी में **बुक हो गया** के साथ अध्यापक और समय दिखेगा — उस दिन समय पर पहुँचें।",
      "नहीं आ पाएँगे? हरी पट्टी पर **रद्द करें** दबाएँ ताकि समय किसी और को मिल सके।",
    ],
    tipsEn: [
      "If you see \"No PTM scheduled\", booking opens here when the school announces one.",
      "If a slot says **Full**, pick another time or another teacher.",
    ],
    tipsHi: [
      "अगर \"कोई PTM तय नहीं है\" दिखे, तो स्कूल की घोषणा के बाद यहीं बुकिंग खुलेगी।",
      "अगर समय पर **भर गया** लिखा हो, तो दूसरा समय या दूसरा अध्यापक चुनें।",
    ],
  ),
  ScreenGuide(
    id: "leave-parent",
    titleEn: "Tell the school your child will be away",
    titleHi: "बच्चे की छुट्टी के लिए स्कूल को बताएँ",
    stepsEn: [
      "Tap **Leave** under Quick access, then tap **Request leave**.",
      "Choose the **Type of leave**.",
      "Set the **From** and **To** dates (or just **Date** for a half day).",
      "Write the **Reason**, e.g. fever, then tap **Send request**.",
      "The request shows **Pending** until the school marks it **Approved** or **Not approved**.",
      "Plans changed? Tap **Withdraw request**, then **Withdraw**.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **छुट्टी** दबाएँ, फिर **छुट्टी का अनुरोध** दबाएँ।",
      "**छुट्टी का प्रकार** चुनें।",
      "**से** और **तक** की तारीख़ चुनें (आधे दिन के लिए सिर्फ़ **तारीख़**)।",
      "**कारण** लिखें, जैसे बुख़ार, फिर **अनुरोध भेजें** दबाएँ।",
      "स्कूल के फ़ैसले तक **फ़ैसला बाकी** दिखेगा, फिर **मंज़ूर** या **मंज़ूर नहीं**।",
      "योजना बदल गई? **अनुरोध वापस लें** दबाएँ, फिर **वापस लें**।",
    ],
    tipsEn: [
      "If you see \"Please give a reason.\", write a short reason before sending.",
      "If it shows **Not approved**, read the School: note under it or call the office.",
      "If you see \"Could not reach the school server.\", check your internet and send again.",
    ],
    tipsHi: [
      "अगर \"कृपया कारण बताएँ।\" दिखे, तो भेजने से पहले छोटा-सा कारण लिखें।",
      "अगर **मंज़ूर नहीं** दिखे, तो नीचे लिखा स्कूल: नोट पढ़ें या दफ़्तर से बात करें।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखकर फिर भेजें।",
    ],
  ),
  ScreenGuide(
    id: "complaints-parent",
    titleEn: "Raise a complaint with the school",
    titleHi: "स्कूल में शिकायत दर्ज करें",
    stepsEn: [
      "Tap **Complaints** under Quick access, then tap **Raise a complaint**.",
      "Choose **What is it about?** from the list.",
      "Under **Concerning**, pick your child or **General — not about one child**.",
      "Fill **Subject** and **Details** — what happened, when, and what you want done.",
      "Tap **Send to the school**. The school's response appears under your complaint.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **शिकायत** दबाएँ, फिर **शिकायत दर्ज करें** दबाएँ।",
      "**बात किस बारे में है?** में से एक चुनें।",
      "**किसके बारे में** में अपना बच्चा या **सामान्य — किसी एक बच्चे के बारे में नहीं** चुनें।",
      "**विषय** और **विवरण** भरें — क्या हुआ, कब हुआ, और आप क्या चाहते हैं।",
      "**स्कूल को भेजें** दबाएँ। स्कूल का जवाब आपकी शिकायत के नीचे दिखेगा।",
    ],
    tipsEn: [
      "If you see \"Please fill in the subject and the details.\", fill both boxes and send again.",
      "If you see \"Could not reach the school server.\", check your internet and try again.",
    ],
    tipsHi: [
      "अगर \"कृपया विषय और विवरण भरें।\" दिखे, तो दोनों डिब्बे भरकर फिर भेजें।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखकर फिर कोशिश करें।",
    ],
  ),
  ScreenGuide(
    id: "receipts",
    titleEn: "View your fee receipts",
    titleHi: "फ़ीस की रसीदें देखें",
    stepsEn: [
      "Tap **Receipts** under Quick access, or **Previous receipts** on the Fees screen.",
      "**Fee receipts** lists every payment — at the counter or online — with date and payer.",
      "Tap a receipt to open it as a PDF.",
      "A receipt marked **VOID — cancelled by the office** no longer counts.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **रसीदें** दबाएँ, या फ़ीस स्क्रीन पर **पिछली रसीदें** दबाएँ।",
      "**फ़ीस की रसीदें** में काउंटर या ऑनलाइन का हर भुगतान, तारीख़ और भुगतान करने वाले के साथ है।",
      "पीडीएफ़ में देखने के लिए किसी रसीद पर दबाएँ।",
      "जिस रसीद पर **रद्द — दफ़्तर ने यह रसीद रद्द कर दी है** लिखा हो, वह अब मान्य नहीं है।",
    ],
    tipsEn: [
      "If you see \"No receipts yet.\", every payment made at the counter or online will appear here.",
      "If you see \"Could not fetch the receipt. Check your connection.\", check your internet and tap it again.",
    ],
    tipsHi: [
      "अगर \"अभी कोई रसीद नहीं।\" दिखे, तो काउंटर या ऑनलाइन का हर भुगतान यहाँ आ जाएगा।",
      "अगर \"रसीद नहीं मिल सकी। अपना नेटवर्क देखें।\" दिखे, तो इंटरनेट देखकर रसीद फिर से दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "gallery",
    titleEn: "See photos from school events",
    titleHi: "स्कूल के कार्यक्रमों की तस्वीरें देखें",
    stepsEn: [
      "Tap **Gallery** under Quick access to open **School photos**.",
      "Each album shows its name and how many photos it has.",
      "Swipe an album's photos left to see more.",
      "Tap a photo to see it full screen, then swipe for the next one.",
    ],
    stepsHi: [
      "ज़रूरी सुविधाएँ में **गैलरी** दबाकर **स्कूल की तस्वीरें** खोलें।",
      "हर एल्बम पर उसका नाम और फ़ोटो की गिनती लिखी है।",
      "और फ़ोटो देखने के लिए एल्बम की फ़ोटो को बाईं ओर खिसकाएँ।",
      "पूरी स्क्रीन पर देखने के लिए फ़ोटो दबाएँ, फिर अगली फ़ोटो के लिए खिसकाएँ।",
    ],
    tipsEn: [
      "If you see \"No albums published yet.\", photos from school events will appear here.",
      "If you see \"Could not reach the school server.\", check your internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर \"अभी कोई एल्बम प्रकाशित नहीं है।\" दिखे, तो स्कूल के कार्यक्रमों की तस्वीरें यहाँ आएँगी।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "chat",
    titleEn: "Chat with the class teacher",
    titleHi: "कक्षा अध्यापक से बात करें",
    stepsEn: [
      "Tap **Messages** in the bottom bar, or **Chat in app** on the Teachers screen.",
      "The top shows who you are talking to, e.g. **Class teacher**.",
      "Type in the **Type a message…** box and tap the send arrow.",
      "Teachers reply between 8 AM and 8 PM. Messages sent later reach them in the morning.",
    ],
    stepsHi: [
      "नीचे की पट्टी में **संदेश** दबाएँ, या शिक्षक स्क्रीन पर **ऐप में बात करें** दबाएँ।",
      "ऊपर लिखा है कि आप किससे बात कर रहे हैं, जैसे **कक्षा अध्यापक**।",
      "**संदेश लिखें…** डिब्बे में लिखें और भेजने वाला तीर दबाएँ।",
      "अध्यापक सुबह 8 से रात 8 बजे तक जवाब देते हैं। बाद में भेजा संदेश सुबह पहुँचता है।",
    ],
    tipsEn: [
      "If you see \"No class teacher is assigned to this section yet\", check with the school office.",
      "If you see \"Could not send. Check your connection.\", check your internet and send again.",
      "If you see \"Could not reach the school server.\", tap **Retry**.",
    ],
    tipsHi: [
      "अगर \"इस सेक्शन के लिए अभी कोई कक्षा अध्यापक तय नहीं है\" दिखे, तो स्कूल दफ़्तर से पता करें।",
      "अगर \"भेजा नहीं जा सका। अपना नेटवर्क देखें।\" दिखे, तो इंटरनेट देखकर फिर भेजें।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "teachers",
    titleEn: "Message your child's teachers",
    titleHi: "बच्चे के अध्यापकों को संदेश भेजें",
    stepsEn: [
      "On home, tap **Message a teacher · 8 AM – 8 PM** to open **Teachers**.",
      "Find the teacher — class teacher and subject teachers are listed.",
      "Tap **Chat in app** to write inside the app.",
      "Or tap **WhatsApp**: the message is already addressed — type below the last line and send.",
      "WhatsApp goes to the school's number, which passes it to the teacher.",
    ],
    stepsHi: [
      "होम पर **अध्यापक को संदेश भेजें · सुबह 8 – रात 8 बजे** दबाकर **शिक्षक** खोलें।",
      "अध्यापक ढूँढें — कक्षा अध्यापक और विषय अध्यापक सूची में हैं।",
      "ऐप के अंदर लिखने के लिए **ऐप में बात करें** दबाएँ।",
      "या **व्हाट्सएप** दबाएँ: संदेश पहले से तैयार है — आख़िरी पंक्ति के नीचे लिखकर भेजें।",
      "व्हाट्सएप संदेश स्कूल के नंबर पर जाता है, जो उसे अध्यापक तक पहुँचाता है।",
    ],
    tipsEn: [
      "If you see \"WhatsApp is not installed on this phone.\", use **Chat in app** instead.",
      "If the button says **After 8 AM**, teachers are off now — an app message reaches them in the morning.",
      "If you see \"No teachers are linked to this class yet.\", the school office has not assigned them yet.",
    ],
    tipsHi: [
      "अगर \"इस फ़ोन में व्हाट्सएप नहीं है।\" दिखे, तो **ऐप में बात करें** इस्तेमाल करें।",
      "अगर बटन पर **सुबह 8 बजे के बाद** लिखा हो, तो अभी अध्यापक उपलब्ध नहीं — ऐप का संदेश सुबह पहुँचेगा।",
      "अगर \"इस कक्षा से अभी कोई अध्यापक नहीं जुड़ा है।\" दिखे, तो स्कूल दफ़्तर ने अभी तय नहीं किया है।",
    ],
  ),
  ScreenGuide(
    id: "student-id",
    titleEn: "Show your child's student ID",
    titleHi: "बच्चे का छात्र पहचान पत्र दिखाएँ",
    stepsEn: [
      "On the home screen, tap the **Student ID** card.",
      "The ID shows your child's photo, class, admission number and **Guardian** name.",
      "Show the QR at the school gate, library or fee counter.",
    ],
    stepsHi: [
      "होम स्क्रीन पर **छात्र पहचान पत्र** कार्ड दबाएँ।",
      "पहचान पत्र पर बच्चे की फ़ोटो, कक्षा, प्रवेश संख्या और **अभिभावक** का नाम है।",
      "स्कूल गेट, पुस्तकालय या फ़ीस काउंटर पर यह क्यूआर दिखाएँ।",
    ],
    tipsEn: [
      "If you see \"No admission number on record yet\", contact the school office.",
      "If a detail on the ID is wrong, tell the school office — it is changed there.",
    ],
    tipsHi: [
      "अगर \"अभी कोई प्रवेश संख्या दर्ज नहीं है\" दिखे, तो स्कूल दफ़्तर से संपर्क करें।",
      "अगर पहचान पत्र में कुछ ग़लत हो, तो स्कूल दफ़्तर को बताएँ — वहीं बदला जाता है।",
    ],
  ),
  ScreenGuide(
    id: "profile",
    titleEn: "Update your family details",
    titleHi: "परिवार की जानकारी अपडेट करें",
    stepsEn: [
      "Tap **Profile** in the bottom bar to see your **Family** details.",
      "Tap **Update family details**.",
      "Change **Alternate mobile**, **Email**, **Address**, **PIN code** or other fields.",
      "Tap **Save**. The school office can see the update.",
      "Under **Children**, tap a child to see their documents and record.",
    ],
    stepsHi: [
      "नीचे की पट्टी में **प्रोफ़ाइल** दबाएँ — **परिवार** की जानकारी दिखेगी।",
      "**पारिवारिक विवरण अद्यतन करें** दबाएँ।",
      "**दूसरा मोबाइल**, **ईमेल**, **पता**, **पिन कोड** या दूसरी जानकारी बदलें।",
      "**सहेजें** दबाएँ। स्कूल दफ़्तर बदलाव देख सकता है।",
      "**बच्चे** में किसी बच्चे पर दबाकर उसके दस्तावेज़ और रिकॉर्ड देखें।",
    ],
    tipsEn: [
      "Your **Registered mobile** is your sign-in — it can only be changed at the school office.",
      "If you see \"Could not reach the school server.\", check your internet and tap **Save** again.",
      "If a child shows documents to upload, tap that child and upload them.",
    ],
    tipsHi: [
      "आपका **रजिस्टर्ड मोबाइल** ही लॉग-इन है — इसे सिर्फ़ स्कूल दफ़्तर में बदला जा सकता है।",
      "अगर \"स्कूल सर्वर से संपर्क नहीं हुआ।\" दिखे, तो इंटरनेट देखकर फिर **सहेजें** दबाएँ।",
      "अगर बच्चे के दस्तावेज़ अपलोड करने बाकी दिखें, तो उस बच्चे पर दबाकर अपलोड करें।",
    ],
  ),
  ScreenGuide(
    id: "child-profile",
    titleEn: "Upload your child's documents",
    titleHi: "बच्चे के दस्तावेज़ अपलोड करें",
    stepsEn: [
      "In **Profile**, tap your child's name under **Children** to open **Student profile**.",
      "Under **Documents the school needs**, see which are **Required** and which **Optional**.",
      "Tap **Upload**, then **Take a photo**, **Choose from gallery** or **Choose a PDF or file**.",
      "Each document shows **Awaiting verification** until the office marks it **Verified**.",
      "Check **Details on record**. Anything wrong? Tell the school office with your documents.",
    ],
    stepsHi: [
      "**प्रोफ़ाइल** में **बच्चे** के नीचे बच्चे का नाम दबाकर **बच्चे की प्रोफ़ाइल** खोलें।",
      "**स्कूल को चाहिए ये दस्तावेज़** में देखें कौन से **ज़रूरी** हैं और कौन से **ज़रूरी नहीं**।",
      "**अपलोड करें** दबाएँ, फिर **फ़ोटो लें**, **गैलरी से चुनें** या **पीडीएफ़ या फ़ाइल चुनें**।",
      "दफ़्तर के जाँचने तक **जाँच बाकी** दिखेगा, फिर **जाँच पूरी**।",
      "**रिकॉर्ड में दर्ज जानकारी** देखें। कुछ ग़लत हो तो दस्तावेज़ लेकर स्कूल दफ़्तर को बताएँ।",
    ],
    tipsEn: [
      "If a document shows **Rejected**, read the Office: note and tap **Upload again** with a clear copy.",
      "If the Automatic check says \"does not match\", make sure you picked the right child's document.",
      "If you see \"Could not reach the school server. Nothing was uploaded.\", check your internet and retry.",
    ],
    tipsHi: [
      "अगर दस्तावेज़ पर **अस्वीकार** दिखे, तो दफ़्तर: नोट पढ़ें और साफ़ कॉपी के साथ **फिर से अपलोड करें** दबाएँ।",
      "अगर स्वतः जाँच में \"मेल नहीं खाता\" दिखे, तो देखें कि सही बच्चे का दस्तावेज़ चुना है।",
      "अगर \"कुछ भी अपलोड नहीं हुआ।\" दिखे, तो इंटरनेट देखकर फिर से अपलोड करें।",
    ],
  ),
];
