import "screen_guides.dart";

/// Staff app screen guides, written from each screen's real labels
/// (hardcoded English labels stay English in Hindi). See screen_guides.dart.
const List<ScreenGuide> staffScreenGuides = [
  ScreenGuide(
    id: "teacher-home",
    titleEn: "Find your work for the day",
    titleHi: "आज का अपना काम देखें",
    stepsEn: [
      "Tap the green banner (**Mark today's attendance**) to take your class register.",
      "Tap **My attendance** to punch in or out from campus.",
      "Check **Today's periods** for your classes and timings.",
      "Open a tile under **Modules**, like **Homework**, **Marks** or **Period log**.",
      "Use the bottom bar: **Classes** for students, **Messages** for parent chats.",
      "Pull the screen down to refresh the counts.",
    ],
    stepsHi: [
      "हरे बैनर (**Mark today's attendance**) को दबाकर अपनी कक्षा की हाज़िरी लें।",
      "कैंपस से पंच इन या आउट के लिए **मेरी हाज़िरी** दबाएँ।",
      "**आज के पीरियड** में अपनी कक्षाएँ और समय देखें।",
      "**मॉड्यूल** में कोई टाइल खोलें, जैसे **Homework**, **Marks** या **Period log**।",
      "नीचे की पट्टी: छात्रों के लिए **Classes**, अभिभावकों की चैट के लिए **Messages**।",
      "गिनती ताज़ा करने के लिए स्क्रीन नीचे खींचें।",
    ],
    tipsEn: [
      "If you see **No periods for you today on the published timetable.**, ask the office to publish it.",
      "If a tile you need is missing, ask the office to give it to your role in the ERP.",
      "If you see **Could not reach the school server.**, check the internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर **प्रकाशित समय-सारणी में आज आपका कोई पीरियड नहीं है।** दिखे, तो दफ़्तर से प्रकाशित करने को कहें।",
      "अगर कोई ज़रूरी टाइल नहीं दिख रही, तो दफ़्तर से ईआरपी में अपनी भूमिका में जुड़वाएँ।",
      "अगर **Could not reach the school server.** दिखे, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "principal-home",
    titleEn: "See the whole school at a glance",
    titleHi: "पूरे विद्यालय की झलक देखें",
    stepsEn: [
      "Read the **Fees**, **Students**, **Staff** and **Admissions** cards at the top.",
      "Tap **Open dues** or **Students with dues** to open the defaulters list.",
      "Tap **Present** or **Absent** under student attendance to see registers by section.",
      "Check **Waiting for you** for leave, complaints and documents to decide.",
      "Use the **Actions** grid, e.g. **Broadcast**, **Staff leave** or **Mark attendance**.",
      "Pull down to refresh the figures.",
    ],
    stepsHi: [
      "ऊपर **Fees**, **Students**, **Staff** और **Admissions** के कार्ड पढ़ें।",
      "बकाया सूची के लिए **Open dues** या **Students with dues** दबाएँ।",
      "सेक्शन के रजिस्टर देखने के लिए छात्र हाज़िरी में **Present** या **Absent** दबाएँ।",
      "**Waiting for you** में छुट्टी, शिकायत और दस्तावेज़ के फ़ैसले देखें।",
      "**Actions** में से चुनें, जैसे **Broadcast**, **Staff leave** या **Mark attendance**।",
      "आँकड़े ताज़ा करने के लिए नीचे खींचें।",
    ],
    tipsEn: [
      "If you see **No sections marked yet today.**, tap it to see which registers are pending.",
      "If you see **section registers not marked yet**, tap it and remind those class teachers.",
      "If the screen will not load, check the internet and tap **Retry**.",
    ],
    tipsHi: [
      "अगर **आज अभी किसी सेक्शन की हाज़िरी नहीं लगी।** दिखे, तो उसे दबाकर बाकी रजिस्टर देखें।",
      "अगर **section registers not marked yet** दिखे, तो दबाकर उन कक्षा अध्यापकों को याद दिलाएँ।",
      "अगर स्क्रीन न खुले, तो इंटरनेट देखें और **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "desk-home",
    titleEn: "Start your office or support work",
    titleHi: "दफ़्तर या सहायक काम शुरू करें",
    stepsEn: [
      "Tap **Mark my attendance** to punch in when you reach school.",
      "Office staff: check **Waiting for you** for items to decide.",
      "Tap a tile to open your work, e.g. **Collect fees** or **Visitor gate**.",
      "Each tile also shows its Hindi name, like **फ़ीस लें**.",
      "Pull down to refresh.",
    ],
    stepsHi: [
      "विद्यालय पहुँचकर पंच इन के लिए **हाज़िरी लगाएँ** दबाएँ।",
      "दफ़्तर स्टाफ़: फ़ैसले वाले काम **Waiting for you** में देखें।",
      "अपना काम खोलने के लिए टाइल दबाएँ, जैसे **फ़ीस लें** या **आगंतुक**।",
      "हर टाइल पर अंग्रेज़ी नाम भी है, जैसे **Collect fees**।",
      "ताज़ा करने के लिए नीचे खींचें।",
    ],
    tipsEn: [
      "If a tile you need is missing, ask the office to add it to your role in the ERP.",
      "If the tiles look empty, pull down to refresh once you have internet.",
    ],
    tipsHi: [
      "अगर कोई ज़रूरी टाइल नहीं है, तो दफ़्तर से ईआरपी में अपनी भूमिका में जुड़वाएँ।",
      "अगर टाइलें ख़ाली दिखें, तो इंटरनेट आने पर नीचे खींचकर ताज़ा करें।",
    ],
  ),
  ScreenGuide(
    id: "driver-home",
    titleEn: "See your route and take bus attendance",
    titleHi: "अपना रूट देखें और बस की हाज़िरी लें",
    stepsEn: [
      "Tap **My attendance** to punch in or out from campus.",
      "Under **Route**, find your bus by its code and name.",
      "Tap **Take attendance** to mark children at each stop.",
      "Tap **Route** (map button) to open the stops in Google Maps.",
      "Stops are listed in order; **मैप पर नहीं** means the stop has no map pin.",
    ],
    stepsHi: [
      "कैंपस से पंच इन या आउट के लिए **मेरी हाज़िरी** दबाएँ।",
      "**रूट** में अपनी बस का कोड और नाम खोजें।",
      "हर स्टॉप पर बच्चों की हाज़िरी के लिए **हाज़िरी लें** दबाएँ।",
      "गूगल मैप में स्टॉप देखने के लिए **रास्ता** दबाएँ।",
      "स्टॉप क्रम से हैं; **मैप पर नहीं** का मतलब स्टॉप मैप पर नहीं लगा है।",
    ],
    tipsEn: [
      "If you see **No routes yet.**, ask the office to create your route.",
      "If you see **No stop on this route is placed on the map — tell the office**, tell the office.",
      "If the screen does not load, tap **Try again**.",
    ],
    tipsHi: [
      "अगर **अभी कोई रूट नहीं है।** दिखे, तो दफ़्तर से रूट बनवाएँ।",
      "अगर **इस रूट का कोई स्टॉप मैप पर नहीं लगा है — दफ़्तर से कहें** दिखे, तो दफ़्तर को बताएँ।",
      "अगर स्क्रीन न खुले, तो **दोबारा कोशिश करें** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "take-attendance",
    titleEn: "Mark today's attendance for a class",
    titleHi: "कक्षा की आज की हाज़िरी लगाएँ",
    stepsEn: [
      "Every child starts as **P** (Present).",
      "Tap **A** for a child who is absent.",
      "Tap **L** for a child who came late.",
      "Check the count on the button at the bottom.",
      "Tap **Save · … present, … absent** to save the register.",
      "You will see **Attendance saved** when it is done.",
    ],
    stepsHi: [
      "हर बच्चा पहले से **P** (उपस्थित) होता है।",
      "जो बच्चा नहीं आया उसके लिए **A** दबाएँ।",
      "जो बच्चा देर से आया उसके लिए **L** दबाएँ।",
      "नीचे के बटन पर गिनती जाँच लें।",
      "रजिस्टर सहेजने के लिए **Save · … present, … absent** दबाएँ।",
      "पूरा होने पर **हाज़िरी सहेज ली गई** दिखेगा।",
    ],
    tipsEn: [
      "If you see **Already marked today — saving again will update the register.**, saving changes it.",
      "If you see **Could not save. Check the connection and try again.**, check internet and save again.",
      "If you see **No active students in this section.**, tell the office.",
    ],
    tipsHi: [
      "अगर **आज पहले ही लग चुकी है — दोबारा सहेजने पर रजिस्टर अद्यतन हो जाएगा।** दिखे, तो सहेजने से बदलेगा।",
      "अगर **Could not save. Check the connection and try again.** दिखे, तो इंटरनेट देखकर फिर सहेजें।",
      "अगर **इस सेक्शन में कोई चालू छात्र नहीं है।** दिखे, तो दफ़्तर को बताएँ।",
    ],
  ),
  ScreenGuide(
    id: "self-attendance",
    titleEn: "Punch your own attendance with GPS",
    titleHi: "जीपीएस से अपनी हाज़िरी पंच करें",
    stepsEn: [
      "Turn on location (GPS) and stand inside the school campus.",
      "Wait until it shows **On campus**.",
      "Tap **Punch IN** in the morning or **Punch OUT** when you leave.",
      "Scan the QR on the office screen, or type the code in **Or type the 6-digit code**.",
      "Tap **Punch IN** / **Punch OUT** again; the time shows under **IN** and **OUT**.",
    ],
    stepsHi: [
      "लोकेशन (जीपीएस) चालू करें और विद्यालय परिसर के अंदर रहें।",
      "**On campus** दिखने तक रुकें।",
      "सुबह **Punch IN** और जाते समय **Punch OUT** दबाएँ।",
      "ऑफ़िस स्क्रीन का QR स्कैन करें, या **Or type the 6-digit code** में कोड लिखें।",
      "फिर **Punch IN** / **Punch OUT** दबाएँ; समय **IN** और **OUT** के नीचे दिखेगा।",
    ],
    tipsEn: [
      "If you see **Turn on location (GPS) to punch attendance.**, switch on GPS in your phone.",
      "If you see **too vague** next to GPS accuracy, move outdoors and wait a moment.",
      "If you see **Mock location is ON**, turn off the fake-GPS app; mock punches are rejected.",
    ],
    tipsHi: [
      "अगर **Turn on location (GPS) to punch attendance.** दिखे, तो फ़ोन में जीपीएस चालू करें।",
      "अगर जीपीएस सटीकता के साथ **too vague** दिखे, तो खुले में जाएँ और थोड़ा रुकें।",
      "अगर **नक़ली लोकेशन चालू है** दिखे, तो फ़ेक-जीपीएस ऐप बंद करें; नक़ली पंच अस्वीकार होते हैं।",
    ],
  ),
  ScreenGuide(
    id: "period-log",
    titleEn: "Log the periods you taught today",
    titleHi: "आज पढ़ाए गए पीरियड दर्ज करें",
    stepsEn: [
      "Find the period card for each class you had today.",
      "Tap **Mark taught** after the class, or **Not taught** if it did not happen.",
      "Tap **Add chapter / topic covered** and choose what you taught.",
      "Tap **Link a lesson plan** to attach a plan, or **Write a new lesson plan**.",
      "Open any item under **CONTENT** to use the class material.",
    ],
    stepsHi: [
      "आज की हर कक्षा का पीरियड कार्ड देखें।",
      "कक्षा के बाद **Mark taught** दबाएँ, न हुई हो तो **नहीं पढ़ाया** दबाएँ।",
      "**Add chapter / topic covered** दबाकर चुनें कि क्या पढ़ाया।",
      "योजना जोड़ने के लिए **Link a lesson plan** या **नई पाठ योजना लिखें** दबाएँ।",
      "पढ़ाने की सामग्री के लिए **विषय-वस्तु** में कोई चीज़ खोलें।",
    ],
    tipsEn: [
      "If you see **No periods on your timetable today.**, there is nothing to log.",
      "If you see **No syllabus plan set for this subject yet.**, use **Scan syllabus** or ask the office.",
      "If it says **Logged away from campus**, the office sees a location note for that period.",
    ],
    tipsHi: [
      "अगर **आज आपकी समय-सारणी में कोई पीरियड नहीं है।** दिखे, तो दर्ज करने को कुछ नहीं है।",
      "अगर **इस विषय के लिए अभी पाठ्यक्रम योजना तय नहीं है।** दिखे, तो **Scan syllabus** करें या दफ़्तर से पूछें।",
      "अगर **Logged away from campus** दिखे, तो दफ़्तर को उस पीरियड की लोकेशन टिप्पणी दिखेगी।",
    ],
  ),
  ScreenGuide(
    id: "lesson-plan",
    titleEn: "Write a new lesson plan",
    titleHi: "नई पाठ योजना लिखें",
    stepsEn: [
      "Type the **Lesson title** first.",
      "Fill **Objectives**, **Teaching aids**, **Activities** and **Assessment**.",
      "Add **Homework** if you plan to give any.",
      "Tap **Speak** on any box to say it instead of typing.",
      "Tap **Save lesson plan**; it is linked to the period.",
    ],
    stepsHi: [
      "पहले **पाठ का शीर्षक** लिखें।",
      "**Objectives**, **Teaching aids**, **Activities** और **Assessment** भरें।",
      "गृहकार्य देना हो तो **Homework** भरें।",
      "टाइप करने के बजाय किसी भी बॉक्स पर **बोलें** दबाकर बोलें।",
      "**Save lesson plan** दबाएँ; योजना पीरियड से जुड़ जाएगी।",
    ],
    tipsEn: [
      "If you see **Give the lesson a title**, fill the title box and save again.",
      "If you see **Dictation is not available on this phone**, type the text instead.",
    ],
    tipsHi: [
      "अगर **Give the lesson a title** दिखे, तो शीर्षक भरकर फिर सहेजें।",
      "अगर **इस फ़ोन में बोलकर लिखना उपलब्ध नहीं है** दिखे, तो टाइप करें।",
    ],
  ),
  ScreenGuide(
    id: "syllabus-scan",
    titleEn: "Add chapters by photographing the contents page",
    titleHi: "विषय-सूची की फ़ोटो से अध्याय जोड़ें",
    stepsEn: [
      "Choose the **Class** and the **Subject**.",
      "Tap **Camera** to photograph the textbook's contents page, or **Gallery** for a saved photo.",
      "Check the chapters and topics found; untick anything wrong.",
      "Tap **Add to plan** to save them, or **Discard** to start over.",
    ],
    stepsHi: [
      "**कक्षा** और **विषय** चुनें।",
      "पाठ्यपुस्तक के विषय-सूची पेज की फ़ोटो के लिए **कैमरा**, या रखी फ़ोटो के लिए **गैलरी** दबाएँ।",
      "मिले अध्याय और विषय जाँचें; ग़लत वाले का निशान हटाएँ।",
      "सहेजने के लिए **योजना में जोड़ें**, दोबारा शुरू करने के लिए **छोड़ दें** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Pick the class and subject first.**, choose both before taking the photo.",
      "If you see **Nothing recognisable.**, take a straighter, brighter photo of just the contents page.",
      "If you see **Read only partly — please check every row.**, check each line before adding.",
    ],
    tipsHi: [
      "अगर **पहले कक्षा और विषय चुनें।** दिखे, तो फ़ोटो से पहले दोनों चुनें।",
      "अगर **Nothing recognisable.** दिखे, तो सिर्फ़ विषय-सूची की सीधी और साफ़ फ़ोटो लें।",
      "अगर **Read only partly — please check every row.** दिखे, तो जोड़ने से पहले हर पंक्ति जाँचें।",
    ],
  ),
  ScreenGuide(
    id: "homework-staff",
    titleEn: "Post homework for your section",
    titleHi: "अपने सेक्शन को होमवर्क भेजें",
    stepsEn: [
      "Pick the class and section when asked.",
      "Tap **Post homework** at the bottom.",
      "Choose the **Subject** and type a **Title**.",
      "Write the details for parents, or tap **Speak** to say them.",
      "Tap **Publish**; parents see it in their app.",
    ],
    stepsHi: [
      "पूछे जाने पर कक्षा और सेक्शन चुनें।",
      "नीचे **गृहकार्य भेजें** दबाएँ।",
      "**विषय** चुनें और **शीर्षक** लिखें।",
      "अभिभावकों के लिए विवरण लिखें, या **बोलें** दबाकर बोलें।",
      "**प्रकाशित करें** दबाएँ; अभिभावकों के ऐप में दिखेगा।",
    ],
    tipsEn: [
      "If you see **No homework posted for this section yet**, use **Post homework** to add the first one.",
      "If you see **Could not post. Check the connection and try again.**, check internet and publish again.",
    ],
    tipsHi: [
      "अगर **इस सेक्शन के लिए अभी कोई होमवर्क नहीं डाला गया** दिखे, तो **गृहकार्य भेजें** से पहला डालें।",
      "अगर **भेजा नहीं जा सका। नेटवर्क देखें और दोबारा कोशिश करें।** दिखे, तो इंटरनेट देखकर फिर भेजें।",
    ],
  ),
  ScreenGuide(
    id: "marks",
    titleEn: "Choose an exam to enter marks",
    titleHi: "अंक भरने के लिए परीक्षा चुनें",
    stepsEn: [
      "Tap the exam (term) you want to enter marks for.",
      "In **Choose class & section**, pick the section.",
      "The mark sheet opens for that section.",
      "Tap **Exam date sheet** to see the exam days.",
    ],
    stepsHi: [
      "जिस परीक्षा (सत्र) के अंक भरने हैं उसे दबाएँ।",
      "**कक्षा और सेक्शन चुनें** में सेक्शन चुनें।",
      "उस सेक्शन की अंक-सूची खुल जाएगी।",
      "परीक्षा के दिन देखने के लिए **परीक्षा तिथि-पत्र** दबाएँ।",
    ],
    tipsEn: [
      "If you see **No exam is set up for this year yet.**, wait for the exams desk to create the term.",
      "If a sheet count shows **sheets entered**, some subjects already have marks saved.",
    ],
    tipsHi: [
      "अगर **इस वर्ष की कोई परीक्षा अभी तय नहीं हुई है।** दिखे, तो परीक्षा डेस्क के सत्र बनाने तक रुकें।",
      "अगर **sheets entered** दिखे, तो कुछ विषयों के अंक पहले से सहेजे गए हैं।",
    ],
  ),
  ScreenGuide(
    id: "mark-entry",
    titleEn: "Enter marks for one subject",
    titleHi: "एक विषय के अंक भरें",
    stepsEn: [
      "Tap a subject chip at the top, e.g. **Maths /100**.",
      "Type each child's marks in the box next to the name.",
      "Leave the box blank if the child was absent.",
      "Tap **Save** with the subject name to save.",
      "Then pick the next subject chip.",
    ],
    stepsHi: [
      "ऊपर विषय की चिप दबाएँ, जैसे **Maths /100**।",
      "हर बच्चे के नाम के आगे बॉक्स में अंक लिखें।",
      "बच्चा अनुपस्थित था तो बॉक्स ख़ाली छोड़ें।",
      "सहेजने के लिए विषय के नाम वाला **Save** दबाएँ।",
      "फिर अगले विषय की चिप चुनें।",
    ],
    tipsEn: [
      "If you see **Locked by the exams desk**, marks can no longer be changed here.",
      "If you see **enter 0–… or leave blank for absent**, fix that child's marks and save again.",
      "If you see **Discard unsaved marks?**, tap **Stay** and save first.",
    ],
    tipsHi: [
      "अगर **Locked by the exams desk** दिखे, तो यहाँ अंक बदल नहीं सकते।",
      "अगर **enter 0–… or leave blank for absent** दिखे, तो उस बच्चे के अंक ठीक करके फिर सहेजें।",
      "अगर **बिना सहेजे अंक छोड़ दें?** दिखे, तो **रुकें** दबाकर पहले सहेजें।",
    ],
  ),
  ScreenGuide(
    id: "date-sheet",
    titleEn: "See the exam date sheet",
    titleHi: "परीक्षा तिथि-पत्र देखें",
    stepsEn: [
      "Exams are grouped by date, with the term name.",
      "Each line shows the class and subject.",
      "Check the time, duration and any note below it.",
    ],
    stepsHi: [
      "परीक्षाएँ तारीख़ के हिसाब से, सत्र के नाम के साथ हैं।",
      "हर पंक्ति में कक्षा और विषय है।",
      "नीचे समय, अवधि और टिप्पणी देखें।",
    ],
    tipsEn: [
      "If you see **No date sheet has been published for this year yet.**, ask the exams desk.",
      "Pull down to refresh if a new date sheet was just published.",
    ],
    tipsHi: [
      "अगर **इस वर्ष की परीक्षा तिथि-पत्र अभी प्रकाशित नहीं हुई है।** दिखे, तो परीक्षा डेस्क से पूछें।",
      "नई तिथि-पत्र अभी आई हो तो नीचे खींचकर ताज़ा करें।",
    ],
  ),
  ScreenGuide(
    id: "timetable",
    titleEn: "See your weekly timetable",
    titleHi: "अपनी साप्ताहिक समय-सारणी देखें",
    stepsEn: [
      "Check **This week's arrangements** for substitutions at the top.",
      "Tap a day to see its periods; today is marked **today**.",
      "Each row shows period number, subject, class and time.",
      "The bottom shows your total **periods a week**.",
    ],
    stepsHi: [
      "ऊपर **इस सप्ताह की व्यवस्था** में बदले गए पीरियड देखें।",
      "पीरियड देखने के लिए दिन दबाएँ; आज के दिन पर **today** लिखा है।",
      "हर पंक्ति में पीरियड नंबर, विषय, कक्षा और समय है।",
      "नीचे आपके कुल **periods a week** हैं।",
    ],
    tipsEn: [
      "If you see **No periods are assigned to you on the timetable yet.**, ask the office.",
      "If you see **Working draft**, the timetable is not final yet.",
      "If a row says **You cover**, you are the substitute for that period.",
    ],
    tipsHi: [
      "अगर **समय-सारणी में अभी आपको कोई पीरियड नहीं दिया गया है।** दिखे, तो दफ़्तर से पूछें।",
      "अगर **कच्चा प्रारूप** दिखे, तो समय-सारणी अभी पक्की नहीं है।",
      "अगर पंक्ति में **You cover** लिखा है, तो उस पीरियड में आप सब्स्टीट्यूट हैं।",
    ],
  ),
  ScreenGuide(
    id: "online-classes-teacher",
    titleEn: "Schedule and run online classes",
    titleHi: "ऑनलाइन कक्षा तय करें और चलाएँ",
    stepsEn: [
      "Pick **Today**, **Week**, **Later** or **Past** at the top.",
      "Tap **Schedule**, pick **Class & section**, **Subject**, date and times.",
      "Choose **Google Meet** or **Paste a link**, then tap **Schedule**.",
      "At class time tap **Start**; tap **End** when it is over.",
      "Use **Who joined**, **Q&A** and **Summary** on the class card.",
    ],
    stepsHi: [
      "ऊपर **Today**, **Week**, **Later** या **Past** चुनें।",
      "**Schedule** दबाएँ, **Class & section**, **Subject**, तारीख़ और समय चुनें।",
      "**Google Meet** या **Paste a link** चुनें, फिर **Schedule** दबाएँ।",
      "कक्षा के समय **Start** दबाएँ; ख़त्म होने पर **End** दबाएँ।",
      "कक्षा कार्ड पर **Who joined**, **Q&A** और **Summary** का उपयोग करें।",
    ],
    tipsEn: [
      "If you see **Pick the section and the time.**, fill both before scheduling.",
      "If Google is not connected, paste a meeting link, or connect Google from the ERP desk.",
      "In **Who joined**, tap **Mark register from this class**, then **Save register**.",
    ],
    tipsHi: [
      "अगर **Pick the section and the time.** दिखे, तो दोनों भरकर फिर तय करें।",
      "अगर गूगल नहीं जुड़ा है, तो मीटिंग लिंक डालें, या ईआरपी डेस्क से गूगल जोड़ें।",
      "**Who joined** में **Mark register from this class** दबाएँ, फिर **Save register** दबाएँ।",
    ],
  ),
  ScreenGuide(
    id: "online-class-qa-teacher",
    titleEn: "Ask questions during an online class",
    titleHi: "ऑनलाइन कक्षा में सवाल पूछें",
    stepsEn: [
      "Type in **Ask the class a question…**.",
      "Tap **Ask**; it goes to the children's phones.",
      "See how many answered under each question.",
      "Mark each answer **✓ Right**, **✗ Wrong** or **Partly**.",
      "Tap **Close question** to stop answers, or **Reopen**.",
    ],
    stepsHi: [
      "**Ask the class a question…** में सवाल लिखें।",
      "**Ask** दबाएँ; सवाल बच्चों के फ़ोन पर जाएगा।",
      "हर सवाल के नीचे देखें कितनों ने जवाब दिया।",
      "हर जवाब पर **✓ Right**, **✗ Wrong** या **Partly** दबाएँ।",
      "जवाब रोकने के लिए **Close question**, फिर खोलने के लिए **Reopen** दबाएँ।",
    ],
    tipsEn: [
      "If you see **The class is over**, questions can only be asked during a class.",
      "If you see **No questions asked yet.**, type the first question above.",
      "**Not yet:** lists children who have not answered.",
    ],
    tipsHi: [
      "अगर **The class is over** दिखे, तो सवाल केवल कक्षा के दौरान पूछे जा सकते हैं।",
      "अगर **No questions asked yet.** दिखे, तो ऊपर पहला सवाल लिखें।",
      "**Not yet:** में वे बच्चे हैं जिन्होंने जवाब नहीं दिया।",
    ],
  ),
  ScreenGuide(
    id: "online-class-summary",
    titleEn: "Write the class summary and homework",
    titleHi: "कक्षा का सारांश और होमवर्क लिखें",
    stepsEn: [
      "Fill **What did you teach? (one or two lines)**.",
      "Tap **Write the note & suggest homework**.",
      "Check **Topic**, **Summary (class record)**, and the homework **Title** and **Task**.",
      "Tap **Due date**, then **Save**.",
      "Tap **Post homework** to send it to the section's diary.",
    ],
    stepsHi: [
      "**What did you teach? (one or two lines)** भरें।",
      "**Write the note & suggest homework** दबाएँ।",
      "**Topic**, **Summary (class record)**, और होमवर्क का **Title** व **Task** जाँचें।",
      "**Due date** दबाएँ, फिर **Save** दबाएँ।",
      "सेक्शन की डायरी में भेजने के लिए **Post homework** दबाएँ।",
    ],
    tipsEn: [
      "If the note is not right, tap **Write again** for a new draft.",
      "Posting notifies parents, the same as the Homework screen; save first if unsure.",
    ],
    tipsHi: [
      "अगर टिप्पणी ठीक न लगे, तो नए मसौदे के लिए **Write again** दबाएँ।",
      "भेजने पर अभिभावकों को सूचना जाती है, होमवर्क स्क्रीन की तरह; पक्का न हो तो पहले सहेजें।",
    ],
  ),
  ScreenGuide(
    id: "students",
    titleEn: "See your students and add a note",
    titleHi: "अपने छात्र देखें और टिप्पणी जोड़ें",
    stepsEn: [
      "The top line shows how many students and if attendance is marked today.",
      "Tap a student's name.",
      "Choose **Merit / good conduct**, **Discipline note** or **Sick room / first aid**.",
      "Write **What happened**, and turn on telling the parent if needed.",
      "Tap **Save**.",
    ],
    stepsHi: [
      "ऊपर छात्रों की गिनती और आज की हाज़िरी लगी या नहीं, दिखता है।",
      "छात्र का नाम दबाएँ।",
      "**प्रशंसा / अच्छा आचरण**, **अनुशासन टिप्पणी** या **बीमार कक्ष / प्राथमिक उपचार** चुनें।",
      "**What happened** लिखें, और ज़रूरत हो तो अभिभावक को बताना चालू करें।",
      "**Save** दबाएँ।",
    ],
    tipsEn: [
      "If you see **No active students in this section.**, tell the office.",
      "For a discipline note, keep it brief and factual; the office and parent may read it.",
    ],
    tipsHi: [
      "अगर **इस सेक्शन में कोई चालू छात्र नहीं है।** दिखे, तो दफ़्तर को बताएँ।",
      "अनुशासन टिप्पणी छोटी और सही लिखें; दफ़्तर और अभिभावक इसे पढ़ सकते हैं।",
    ],
  ),
  ScreenGuide(
    id: "student-leave-queue",
    titleEn: "Approve or decline a child's leave",
    titleHi: "बच्चे की छुट्टी स्वीकृत या अस्वीकार करें",
    stepsEn: [
      "Keep **Pending** selected to see waiting requests.",
      "Read the child, dates, days and who asked.",
      "Tap **Approve** or **Decline**.",
      "Add a note for the parent (needed when declining).",
      "Confirm with **Approve** or **Decline**; see past ones under **Decided**.",
    ],
    stepsHi: [
      "प्रतीक्षा वाले अनुरोध देखने के लिए **Pending** चुना रहने दें।",
      "बच्चा, तारीख़ें, दिन और किसने माँगा, पढ़ें।",
      "**स्वीकृत करें** या **अस्वीकार करें** दबाएँ।",
      "अभिभावक के लिए टिप्पणी लिखें (अस्वीकार करते समय ज़रूरी)।",
      "फिर से **Approve** या **Decline** दबाएँ; पुराने **Decided** में देखें।",
    ],
    tipsEn: [
      "If you see **No leave request is waiting for your classes.**, there is nothing to decide.",
      "If you see **Waiting for the principal.**, the principal decides this one.",
    ],
    tipsHi: [
      "अगर **No leave request is waiting for your classes.** दिखे, तो कुछ तय नहीं करना है।",
      "अगर **प्रधानाचार्य की प्रतीक्षा है।** दिखे, तो इसका फ़ैसला प्रधानाचार्य करेंगे।",
    ],
  ),
  ScreenGuide(
    id: "staff-leave-approvals",
    titleEn: "Approve or reject staff leave",
    titleHi: "स्टाफ़ की छुट्टी स्वीकृत या अस्वीकार करें",
    stepsEn: [
      "Keep **Pending** selected to see waiting requests.",
      "Read the leave type, dates and days left after this.",
      "Tap **Approve** or **Reject**.",
      "Add a **Note (optional)** or a **Reason** when rejecting.",
      "Confirm; see past decisions under **Decided**.",
    ],
    stepsHi: [
      "प्रतीक्षा वाले अनुरोध देखने के लिए **Pending** चुना रहने दें।",
      "छुट्टी का प्रकार, तारीख़ें और इसके बाद बचे दिन पढ़ें।",
      "**स्वीकृत करें** या **अस्वीकार करें** दबाएँ।",
      "**Note (optional)** लिखें, या अस्वीकार करते समय **Reason** लिखें।",
      "पुष्टि करें; पुराने फ़ैसले **Decided** में देखें।",
    ],
    tipsEn: [
      "If you see **No staff leave is waiting.**, nothing needs a decision now.",
      "Check the **left after this** line before approving long leave.",
    ],
    tipsHi: [
      "अगर **No staff leave is waiting.** दिखे, तो अभी कोई फ़ैसला बाकी नहीं है।",
      "लंबी छुट्टी स्वीकृत करने से पहले **left after this** पंक्ति देखें।",
    ],
  ),
  ScreenGuide(
    id: "my-leave",
    titleEn: "Apply for your leave",
    titleHi: "अपनी छुट्टी के लिए आवेदन करें",
    stepsEn: [
      "Check **Balance this year** for days left of each leave type.",
      "Tap **Apply for leave** and pick the leave type.",
      "Pick the start date and end date (or **Same day**).",
      "Turn on **Half day** if needed and pick **Morning off** or **Afternoon off**.",
      "Write a short **Reason** and tap **Submit**.",
    ],
    stepsHi: [
      "हर प्रकार की बची छुट्टी **इस वर्ष शेष** में देखें।",
      "**छुट्टी के लिए आवेदन** दबाएँ और छुट्टी का प्रकार चुनें।",
      "शुरू और अंत की तारीख़ चुनें (या **Same day**)।",
      "ज़रूरत हो तो **आधा दिन** चालू करें, फिर **Morning off** या **Afternoon off** चुनें।",
      "छोटा **कारण** लिखें और **Submit** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Half day: choose morning off or afternoon off.**, pick one and submit again.",
      "To cancel a pending request, tap **Withdraw** under **My requests**.",
      "If you see **No leave applied yet this year.**, you have no requests yet.",
    ],
    tipsHi: [
      "अगर **Half day: choose morning off or afternoon off.** दिखे, तो एक चुनकर फिर भेजें।",
      "प्रतीक्षा वाला अनुरोध रद्द करने के लिए **मेरे अनुरोध** में **वापस लें** दबाएँ।",
      "अगर **इस वर्ष अभी कोई छुट्टी नहीं ली गई है।** दिखे, तो अभी कोई अनुरोध नहीं है।",
    ],
  ),
  ScreenGuide(
    id: "my-subjects",
    titleEn: "Ask to change a class's subjects",
    titleHi: "कक्षा के विषय बदलने का अनुरोध करें",
    stepsEn: [
      "Tap a class to see the subjects it studies.",
      "To take a subject out, tap the minus icon next to it.",
      "To add one, tap **Ask to add a subject** and pick it — or choose **Not in the list** to ask for a new subject.",
      "Write **Why?** and tap **Send to office**.",
      "The answer shows under **My requests**: Waiting, Approved or Declined.",
    ],
    stepsHi: [
      "कक्षा पर टैप करें — उसके विषय दिखेंगे।",
      "कोई विषय हटवाना हो तो उसके आगे माइनस का निशान दबाएँ।",
      "विषय जुड़वाना हो तो **Ask to add a subject** दबाकर चुनें — या नया विषय माँगने के लिए **Not in the list** चुनें।",
      "**Why?** में कारण लिखें और **Send to office** दबाएँ।",
      "जवाब **My requests** में दिखेगा: Waiting, Approved या Declined।",
    ],
    tipsEn: [
      "Nothing changes until the principal or office approves it in the web ERP.",
      "To cancel a request that is still waiting, tap **Withdraw**.",
      "If no class is shown, the office has not given you classes yet (Staff → Duties).",
    ],
    tipsHi: [
      "प्रधानाचार्य या ऑफिस के वेब ERP में स्वीकृत करने तक कुछ नहीं बदलता।",
      "जो अनुरोध अभी प्रतीक्षा में है उसे रद्द करने के लिए **Withdraw** दबाएँ।",
      "अगर कोई कक्षा न दिखे, तो ऑफिस ने अभी आपको कक्षाएँ नहीं दी हैं (Staff → Duties)।",
    ],
  ),
  ScreenGuide(
    id: "complaints-staff",
    titleEn: "Handle a parent's complaint",
    titleHi: "अभिभावक की शिकायत निपटाएँ",
    stepsEn: [
      "Keep **Open** selected to see complaints for your classes.",
      "Tap **Take up** to make it yours.",
      "Tap the phone icon (**Call parent**) to talk to the parent.",
      "Tap **In progress** while you work on it.",
      "Tap **Resolve**, write **What was done**, and confirm.",
    ],
    stepsHi: [
      "अपनी कक्षाओं की शिकायतें देखने के लिए **Open** चुना रहने दें।",
      "शिकायत अपने ज़िम्मे लेने के लिए **हाथ में लें** दबाएँ।",
      "अभिभावक से बात के लिए फ़ोन आइकन (**अभिभावक को फ़ोन करें**) दबाएँ।",
      "काम चलते समय **चल रहा है** दबाएँ।",
      "**निपटाएँ** दबाएँ, **क्या किया गया** लिखें और पुष्टि करें।",
    ],
    tipsEn: [
      "If you see **No open complaint for your classes.**, there is nothing to handle.",
      "The parent reads your resolution note in their app, so write it clearly.",
      "Resolved ones are under **Resolved**; **Close** appears there if you may close them.",
    ],
    tipsHi: [
      "अगर **No open complaint for your classes.** दिखे, तो कुछ नहीं निपटाना है।",
      "अभिभावक आपकी टिप्पणी अपने ऐप में पढ़ते हैं, इसलिए साफ़ लिखें।",
      "निपटी शिकायतें **Resolved** में हैं; अनुमति हो तो वहाँ **बंद करें** दिखेगा।",
    ],
  ),
  ScreenGuide(
    id: "ptm-teacher",
    titleEn: "Meet parents on PTM day",
    titleHi: "पीटीएम के दिन अभिभावकों से मिलें",
    stepsEn: [
      "See your PTM slots with time and room, and how many are booked.",
      "Tap **Call** to phone a parent if needed.",
      "After meeting, tap **Met · add note**; tap **Did not come** if they missed it.",
      "Fill **Doing well**, **Needs attention** and **Agreed follow-up**.",
      "Tap **Save**.",
    ],
    stepsHi: [
      "अपने पीटीएम समय, कमरा और कितनी बुकिंग हुई, देखें।",
      "ज़रूरत हो तो अभिभावक को **फ़ोन करें** दबाएँ।",
      "मिलने के बाद **मिले · टिप्पणी जोड़ें** दबाएँ; न आए हों तो **नहीं आए** दबाएँ।",
      "**अच्छा कर रहे हैं**, **ध्यान देने की ज़रूरत** और **तय हुआ फ़ॉलो-अप** भरें।",
      "**सहेजें** दबाएँ।",
    ],
    tipsEn: [
      "If you see **No PTM slots are yours right now.**, the office has not given you slots yet.",
      "All three note boxes are optional; write only what helps the parent.",
      "If a meeting shows **Add note**, the note was not written yet; tap it to add.",
    ],
    tipsHi: [
      "अगर **अभी आपका कोई पीटीएम समय नहीं है।** दिखे, तो दफ़्तर ने अभी समय नहीं दिया है।",
      "तीनों टिप्पणी बॉक्स वैकल्पिक हैं; वही लिखें जो अभिभावक के काम का हो।",
      "अगर मीटिंग पर **टिप्पणी जोड़ें** दिखे, तो टिप्पणी बाकी है; दबाकर जोड़ें।",
    ],
  ),
  ScreenGuide(
    id: "documents-review",
    titleEn: "Verify documents parents upload",
    titleHi: "अभिभावकों के भेजे दस्तावेज़ जाँचें",
    stepsEn: [
      "Keep **Pending** selected to see documents waiting.",
      "Tap a document to open it.",
      "Check it is clear, correct and for the right child.",
      "Tap **Verify** if it is fine.",
      "Or tap **Reject**, write why, and confirm with **Reject**.",
    ],
    stepsHi: [
      "प्रतीक्षा वाले दस्तावेज़ देखने के लिए **Pending** चुना रहने दें।",
      "दस्तावेज़ खोलने के लिए उसे दबाएँ।",
      "देखें कि वह साफ़, सही और सही बच्चे का है।",
      "ठीक हो तो **Verify** दबाएँ।",
      "नहीं तो **अस्वीकार करें** दबाएँ, कारण लिखें और फिर **अस्वीकार करें** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Nothing to verify.**, no parent has uploaded anything new.",
      "If you see **Could not load the file.**, go back and open it again.",
      "Write the reject reason simply, e.g. blurred, wrong child, expired; the parent reads it.",
    ],
    tipsHi: [
      "अगर **Nothing to verify.** दिखे, तो किसी अभिभावक ने नया कुछ नहीं भेजा है।",
      "अगर **Could not load the file.** दिखे, तो वापस जाकर फिर खोलें।",
      "अस्वीकार का कारण आसान लिखें, जैसे: धुंधला, ग़लत बच्चा, अवधि समाप्त; अभिभावक इसे पढ़ेंगे।",
    ],
  ),
  ScreenGuide(
    id: "fee-counter",
    titleEn: "Find a child to collect fees",
    titleHi: "फ़ीस लेने के लिए बच्चा खोजें",
    stepsEn: [
      "Type the name, admission no. or mobile in the search box.",
      "Tap **Find**.",
      "Each result shows the amount owed or **Clear**.",
      "Tap the child to open the collection screen.",
    ],
    stepsHi: [
      "खोज बॉक्स में नाम, प्रवेश संख्या या मोबाइल लिखें।",
      "**Find** दबाएँ।",
      "हर नतीजे में बकाया रक़म या **Clear** दिखेगा।",
      "पैसे लेने की स्क्रीन खोलने के लिए बच्चे को दबाएँ।",
    ],
    tipsEn: [
      "If you see **Type at least two letters, or the admission number**, type a bit more.",
      "If you see **Nobody matched.**, try the admission number or the parent's mobile.",
    ],
    tipsHi: [
      "अगर **Type at least two letters, or the admission number** दिखे, तो थोड़ा और लिखें।",
      "अगर **कोई नहीं मिला।** दिखे, तो प्रवेश संख्या या अभिभावक का मोबाइल आज़माएँ।",
    ],
  ),
  ScreenGuide(
    id: "fee-counter-student",
    titleEn: "Take a fee payment and issue a receipt",
    titleHi: "फ़ीस लें और रसीद बनाएँ",
    stepsEn: [
      "Tick the dues being paid; siblings show below the main child.",
      "For a part payment tap **Part**, type the amount in **Paying now (₹)**, tap **Set**.",
      "Choose the payment mode, e.g. cash, and fill the reference if asked.",
      "Tap **Collect**, check the amount, then tap **Take money**.",
      "Read the receipt number under **Received** and tap **Done**.",
    ],
    stepsHi: [
      "जो बकाया जमा हो रहा है उस पर निशान लगाएँ; भाई-बहन नीचे दिखते हैं।",
      "आंशिक भुगतान के लिए **Part** दबाएँ, **अभी जमा (₹)** में रक़म लिखें, **सेट** दबाएँ।",
      "भुगतान का तरीक़ा चुनें, जैसे नक़द, और माँगा जाए तो रेफ़रेंस भरें।",
      "**Collect** दबाएँ, रक़म जाँचें, फिर **पैसे लें** दबाएँ।",
      "**Received** के नीचे रसीद नंबर देखें और **हो गया** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Nothing outstanding.**, this family owes nothing.",
      "If you see **More than the … outstanding**, enter an amount up to the balance.",
      "If you see **Already collected**, this payment was saved before; do not take money again.",
    ],
    tipsHi: [
      "अगर **कुछ बकाया नहीं।** दिखे, तो इस परिवार का कुछ बाकी नहीं है।",
      "अगर **More than the … outstanding** दिखे, तो बकाया तक की रक़म लिखें।",
      "अगर **Already collected** दिखे, तो यह पहले ही दर्ज है; दोबारा पैसे न लें।",
    ],
  ),
  ScreenGuide(
    id: "fee-defaulters",
    titleEn: "Follow up families with unpaid fees",
    titleHi: "बकाया फ़ीस वाले परिवारों से बात करें",
    stepsEn: [
      "Pick **All**, **₹5,000+** or **₹20,000+**, or search a child, parent or mobile.",
      "Tap **Call** or **WhatsApp** to reach the family.",
      "Tap **Log call** and choose what they said, e.g. **Promised to pay**.",
      "Set the **Will pay by** date if they promised, then tap **Save**.",
      "Tap **Collect** next to a child to take the fee now.",
    ],
    stepsHi: [
      "**All**, **₹5,000+** या **₹20,000+** चुनें, या बच्चा, अभिभावक या मोबाइल खोजें।",
      "परिवार से बात के लिए **फ़ोन करें** या **व्हाट्सएप** दबाएँ।",
      "**कॉल दर्ज करें** दबाएँ और जवाब चुनें, जैसे **Promised to pay**।",
      "वादा किया हो तो **Will pay by** तारीख़ चुनें, फिर **Save** दबाएँ।",
      "अभी फ़ीस लेने के लिए बच्चे के आगे **लें** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Nothing outstanding in your classes.**, no family owes fees.",
      "If you see **No mobile on record**, ask the office to add the parent's number.",
    ],
    tipsHi: [
      "अगर **Nothing outstanding in your classes.** दिखे, तो किसी का बकाया नहीं है।",
      "अगर **No mobile on record** दिखे, तो दफ़्तर से अभिभावक का नंबर जुड़वाएँ।",
    ],
  ),
  ScreenGuide(
    id: "my-collections",
    titleEn: "Check the money you collected today",
    titleHi: "आज लिया गया पैसा देखें",
    stepsEn: [
      "The top shows the total and number of receipts for today.",
      "Below it, see the split by payment mode.",
      "Each receipt shows the parent, child, mode and time.",
      "Match the total with the cash you hold before handing over.",
    ],
    stepsHi: [
      "ऊपर आज की कुल रक़म और रसीदों की गिनती है।",
      "उसके नीचे भुगतान के तरीक़े के हिसाब से बँटवारा है।",
      "हर रसीद में अभिभावक, बच्चा, तरीक़ा और समय है।",
      "जमा करने से पहले कुल रक़म अपने पास के नक़द से मिलाएँ।",
    ],
    tipsEn: [
      "If you see **You have not collected anything today.**, no receipt is in your name today.",
      "Pull down to refresh after a new collection.",
    ],
    tipsHi: [
      "अगर **आपने आज कुछ नहीं लिया है।** दिखे, तो आज आपके नाम कोई रसीद नहीं है।",
      "नई वसूली के बाद नीचे खींचकर ताज़ा करें।",
    ],
  ),
  ScreenGuide(
    id: "admission-leads",
    titleEn: "Call admission enquiries",
    titleHi: "प्रवेश पूछताछ वालों को फ़ोन करें",
    stepsEn: [
      "Pick **Due**, **Overdue**, **Mine** or **All open**, or search by name or mobile.",
      "Tap **Call** or **WhatsApp** to reach the parent.",
      "Tap **Log call** and choose how it went, e.g. **Spoke** or **Visit fixed**.",
      "Write **What was said** and set **Call again on**.",
      "Tap **Save**.",
    ],
    stepsHi: [
      "**Due**, **Overdue**, **Mine** या **All open** चुनें, या नाम/मोबाइल से खोजें।",
      "अभिभावक से बात के लिए **फ़ोन करें** या **व्हाट्सएप** दबाएँ।",
      "**कॉल दर्ज करें** दबाएँ और नतीजा चुनें, जैसे **Spoke** या **Visit fixed**।",
      "**क्या बात हुई** लिखें और **Call again on** तारीख़ चुनें।",
      "**Save** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Nothing to call right now.**, no lead is due; try **All open**.",
      "The **Last:** line shows the previous call, so read it before calling.",
    ],
    tipsHi: [
      "अगर **अभी किसी को फ़ोन नहीं करना है।** दिखे, तो कोई बाकी नहीं; **All open** देखें।",
      "**Last:** पंक्ति में पिछली कॉल है, फ़ोन से पहले पढ़ लें।",
    ],
  ),
  ScreenGuide(
    id: "field-survey",
    titleEn: "Record families during a field survey",
    titleHi: "सर्वे में परिवारों को दर्ज करें",
    stepsEn: [
      "Under **Choose the beat you are walking**, tap your area.",
      "Fill **Child's name**, **Parent's name** and **Mobile**.",
      "Add **Class sought**, **Age (approx)**, **Gender** and **Locality / street**.",
      "Ask the parent, then tick **The parent agreed to be contacted by the school**.",
      "Tap **Save family**.",
    ],
    stepsHi: [
      "**आप जिस क्षेत्र में जा रहे हैं वह चुनें** में अपना क्षेत्र दबाएँ।",
      "**बच्चे का नाम**, **अभिभावक का नाम** और **मोबाइल** भरें।",
      "**वांछित कक्षा**, **आयु (लगभग)**, **लिंग** और **मोहल्ला / गली** भरें।",
      "अभिभावक से पूछें, फिर **अभिभावक विद्यालय से संपर्क के लिए सहमत हुए** पर निशान लगाएँ।",
      "**Save family** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Ask the parent before recording their details.**, get consent and tick the box.",
      "If you see **No survey beat is active.**, ask the admissions desk to set the areas.",
    ],
    tipsHi: [
      "अगर **विवरण दर्ज करने से पहले अभिभावक से पूछ लें।** दिखे, तो सहमति लेकर निशान लगाएँ।",
      "अगर **कोई सर्वेक्षण क्षेत्र चालू नहीं है।** दिखे, तो प्रवेश डेस्क से क्षेत्र तय करवाएँ।",
    ],
  ),
  ScreenGuide(
    id: "visitor-gate",
    titleEn: "Check visitors in and out at the gate",
    titleHi: "गेट पर आगंतुकों को अंदर-बाहर दर्ज करें",
    stepsEn: [
      "Tap **Check in** and type the **Mobile number**.",
      "Fill **Visitor's name**, **Why are they here?** and **Who are they here to meet?**.",
      "Add **ID shown (optional)**, then tap **Check in**.",
      "When they leave, tap **Out** next to their name and confirm **Check out**.",
      "For **Early pickup**, tap **Hand over** and write who is collecting the child.",
    ],
    stepsHi: [
      "**अंदर दर्ज करें** दबाएँ और **मोबाइल नंबर** लिखें।",
      "**आगंतुक का नाम**, **किस काम से आए हैं?** और **किससे मिलने आए हैं?** भरें।",
      "**दिखाया गया पहचान पत्र (वैकल्पिक)** भरें, फिर **Check in** दबाएँ।",
      "जाते समय नाम के आगे **बाहर** दबाएँ और **बाहर दर्ज करें** से पुष्टि करें।",
      "**Early pickup** में **सौंपें** दबाएँ और बच्चे को ले जाने वाले का नाम लिखें।",
    ],
    tipsEn: [
      "If you see **is already on campus**, tap **Check them out instead**.",
      "If you see **Enter a 10-digit mobile number**, fix the number and try again.",
      "If you see **Pick why they are here**, choose a reason from the list.",
    ],
    tipsHi: [
      "अगर **is already on campus** दिखे, तो **इसके बजाय बाहर दर्ज करें** दबाएँ।",
      "अगर **Enter a 10-digit mobile number** दिखे, तो नंबर ठीक करके फिर कोशिश करें।",
      "अगर **Pick why they are here** दिखे, तो सूची से कारण चुनें।",
    ],
  ),
  ScreenGuide(
    id: "transport-requests",
    titleEn: "Handle parents' transport requests",
    titleHi: "अभिभावकों के परिवहन अनुरोध संभालें",
    stepsEn: [
      "Keep **New & contacted** selected to see open requests.",
      "Read the pickup address and preferred stop.",
      "Tap **Call** or **WhatsApp** to talk to the family.",
      "Tap **Contacted**, **Assigned** or **Decline** to update the request.",
      "Write a note for the family and tap **Save**.",
    ],
    stepsHi: [
      "खुले अनुरोध देखने के लिए **New & contacted** चुना रहने दें।",
      "पिकअप का पता और पसंदीदा स्टॉप पढ़ें।",
      "परिवार से बात के लिए **फ़ोन करें** या **व्हाट्सएप** दबाएँ।",
      "अनुरोध बदलने के लिए **संपर्क हुआ**, **सौंपा गया** या **अस्वीकार करें** दबाएँ।",
      "परिवार के लिए टिप्पणी लिखें और **सहेजें** दबाएँ।",
    ],
    tipsEn: [
      "If you see **Nothing here.**, no parent has sent a request yet.",
      "The family sees your note, so write it clearly.",
      "Done requests are under **Assigned** and **Declined**.",
    ],
    tipsHi: [
      "अगर **यहाँ कुछ नहीं।** दिखे, तो किसी अभिभावक ने अनुरोध नहीं भेजा है।",
      "परिवार आपकी टिप्पणी देखेगा, इसलिए साफ़ लिखें।",
      "पूरे हुए अनुरोध **Assigned** और **Declined** में हैं।",
    ],
  ),
  ScreenGuide(
    id: "route-manifest",
    titleEn: "Mark children on and off the bus",
    titleHi: "बस में चढ़ने-उतरने वाले बच्चे दर्ज करें",
    stepsEn: [
      "Pick **Morning — pick up** or **Afternoon — drop** at the top.",
      "Go stop by stop; each stop lists its children.",
      "Tap **चढ़ गए** (morning) or **उतर गए** (afternoon) for each child.",
      "Tap **Did not come** if the child is absent.",
      "Tap **Change** to fix a mistake; the count at the top shows marked / total.",
    ],
    stepsHi: [
      "ऊपर **सुबह — लेना** या **दोपहर — छोड़ना** चुनें।",
      "स्टॉप-दर-स्टॉप चलें; हर स्टॉप पर उसके बच्चे हैं।",
      "हर बच्चे के लिए **चढ़ गए** (सुबह) या **उतर गए** (दोपहर) दबाएँ।",
      "बच्चा न आया हो तो **नहीं आया** दबाएँ।",
      "ग़लती ठीक करने के लिए **बदलें** दबाएँ; ऊपर दर्ज / कुल गिनती दिखती है।",
    ],
    tipsEn: [
      "If you see **लोकेशन नहीं मिली, दोबारा कोशिश करें**, turn on GPS and tap again.",
      "If you see **दर्ज नहीं हुआ**, check the internet and tap again.",
      "If you see **No stops on this route**, tell the office.",
    ],
    tipsHi: [
      "अगर **लोकेशन नहीं मिली, दोबारा कोशिश करें** दिखे, तो जीपीएस चालू करके फिर दबाएँ।",
      "अगर **दर्ज नहीं हुआ** दिखे, तो इंटरनेट देखकर फिर दबाएँ।",
      "अगर **इस रूट पर कोई स्टॉप नहीं है** दिखे, तो दफ़्तर को बताएँ।",
    ],
  ),
  ScreenGuide(
    id: "broadcast",
    titleEn: "Send a message to all parents or staff",
    titleHi: "सभी अभिभावकों या स्टाफ़ को संदेश भेजें",
    stepsEn: [
      "Under **Audience**, pick **All parents** or **All staff**.",
      "Under **Message type**, pick an approved template, or free text.",
      "Fill the template fields, or type the **Message**.",
      "Tap **Preview recipients** to see how many will get it.",
      "Tap **Send to … now**, then confirm with **Send to …**.",
    ],
    stepsHi: [
      "**किसे भेजें** में **सारे अभिभावक** या **सारा स्टाफ़** चुनें।",
      "**संदेश का प्रकार** में स्वीकृत टेम्पलेट, या खुला संदेश चुनें।",
      "टेम्पलेट के ख़ाने भरें, या **संदेश** लिखें।",
      "कितनों को जाएगा, यह देखने के लिए **प्राप्तकर्ता देखें** दबाएँ।",
      "**Send to … now** दबाएँ, फिर **Send to …** से पुष्टि करें।",
    ],
    tipsEn: [
      "If you see **Fill every template field first.**, fill all the boxes before preview.",
      "Free text reaches only those who messaged the school in the last 24 hours; use a template.",
      "A send cannot be undone, so read the message again before confirming.",
    ],
    tipsHi: [
      "अगर **Fill every template field first.** दिखे, तो देखने से पहले सब ख़ाने भरें।",
      "खुला संदेश केवल पिछले 24 घंटे में संदेश भेजने वालों तक जाता है; टेम्पलेट चुनें।",
      "भेजा संदेश वापस नहीं होता, इसलिए पुष्टि से पहले दोबारा पढ़ें।",
    ],
  ),
  ScreenGuide(
    id: "registers",
    titleEn: "Check today's attendance registers",
    titleHi: "आज के हाज़िरी रजिस्टर देखें",
    stepsEn: [
      "The top line shows how many sections are marked and pending.",
      "Each section shows **Marked**, **Pending** or **Holiday**.",
      "Marked sections show P, A and L counts and who marked.",
      "Tap a section to view or mark its register.",
    ],
    stepsHi: [
      "ऊपर दिखता है कितने सेक्शन की हाज़िरी लगी और कितने बाकी हैं।",
      "हर सेक्शन पर **Marked**, **Pending** या **Holiday** लिखा है।",
      "लगे सेक्शन में P, A, L की गिनती और किसने लगाई, दिखता है।",
      "रजिस्टर देखने या भरने के लिए सेक्शन दबाएँ।",
    ],
    tipsEn: [
      "If a section says **Not marked yet**, remind the class teacher or mark it yourself.",
      "If you see **No active sections configured.**, ask the office to set up sections.",
    ],
    tipsHi: [
      "अगर सेक्शन पर **Not marked yet** लिखा है, तो कक्षा अध्यापक को याद दिलाएँ या ख़ुद लगाएँ।",
      "अगर **कोई चालू सेक्शन तय नहीं है।** दिखे, तो दफ़्तर से सेक्शन बनवाएँ।",
    ],
  ),
  ScreenGuide(
    id: "staff-today",
    titleEn: "See which staff are present today",
    titleHi: "आज कौन-सा स्टाफ़ आया है, देखें",
    stepsEn: [
      "The top line shows present, absent and not marked counts.",
      "Each name shows **Present**, **Absent**, **Late**, **Leave** or **Not marked**.",
      "Punch times show as in / out.",
      "For anyone not present, tap **Call** or **WhatsApp**.",
    ],
    stepsHi: [
      "ऊपर उपस्थित, अनुपस्थित और बिना दर्ज की गिनती है।",
      "हर नाम पर **Present**, **Absent**, **Late**, **Leave** या **Not marked** लिखा है।",
      "पंच का समय in / out में दिखता है।",
      "जो उपस्थित नहीं है, उसके लिए **फ़ोन करें** या **व्हाट्सएप** दबाएँ।",
    ],
    tipsEn: [
      "If you see **No mobile on file**, ask the office to add the number in **Staff contacts**.",
      "If you see **Could not open the dialer.**, dial the number by hand.",
    ],
    tipsHi: [
      "अगर **रिकॉर्ड में मोबाइल नहीं है** दिखे, तो दफ़्तर से **Staff contacts** में नंबर जुड़वाएँ।",
      "अगर **डायलर नहीं खुल सका।** दिखे, तो नंबर हाथ से मिलाएँ।",
    ],
  ),
  ScreenGuide(
    id: "follow-ups",
    titleEn: "Call admission follow-ups that are due",
    titleHi: "बाकी प्रवेश फ़ॉलो-अप पर फ़ोन करें",
    stepsEn: [
      "Leads are listed oldest first.",
      "Each shows the child, class sought, parent and enquiry number.",
      "Check the **Due** date and days overdue.",
      "Tap **Call** or **WhatsApp** to reach the parent.",
    ],
    stepsHi: [
      "लीड सबसे पुरानी से पहले दिखती हैं।",
      "हर लीड में बच्चा, वांछित कक्षा, अभिभावक और पूछताछ नंबर है।",
      "**Due** तारीख़ और कितने दिन देर हुई, देखें।",
      "अभिभावक से बात के लिए **फ़ोन करें** या **व्हाट्सएप** दबाएँ।",
    ],
    tipsEn: [
      "If you see **No follow-ups are due. Nice.**, nothing is pending.",
      "If you see **No mobile on file**, the lead has no number to call.",
    ],
    tipsHi: [
      "अगर **कोई फ़ॉलो-अप बाकी नहीं। बढ़िया।** दिखे, तो कुछ बाकी नहीं है।",
      "अगर **रिकॉर्ड में मोबाइल नहीं है** दिखे, तो इस लीड का नंबर नहीं है।",
    ],
  ),
  ScreenGuide(
    id: "staff-contacts",
    titleEn: "Call staff or fix a staff mobile number",
    titleHi: "स्टाफ़ को फ़ोन करें या मोबाइल नंबर ठीक करें",
    stepsEn: [
      "Find the staff member in the list.",
      "Tap **Call** or **WhatsApp** to reach them.",
      "To add or fix a number, tap the name.",
      "Type the **10-digit mobile** and tap **Save**.",
    ],
    stepsHi: [
      "सूची में स्टाफ़ का नाम खोजें।",
      "बात के लिए **फ़ोन करें** या **व्हाट्सएप** दबाएँ।",
      "नंबर जोड़ने या ठीक करने के लिए नाम दबाएँ।",
      "**10 अंकों का मोबाइल** लिखें और **सहेजें** दबाएँ।",
    ],
    tipsEn: [
      "If a name says **no mobile — cannot sign in**, add the number so they can use the app.",
      "Staff sign in with an OTP sent to this number, so check it carefully.",
    ],
    tipsHi: [
      "अगर नाम पर **no mobile — cannot sign in** लिखा है, तो नंबर जोड़ें ताकि वे ऐप चला सकें।",
      "स्टाफ़ इसी नंबर पर आए ओटीपी से साइन इन करते हैं, इसलिए ध्यान से जाँचें।",
    ],
  ),
  ScreenGuide(
    id: "payslips",
    titleEn: "See your monthly payslip",
    titleHi: "अपनी मासिक वेतन पर्ची देखें",
    stepsEn: [
      "Each month shows its status: **Approved**, **Released** or **Paid**.",
      "Tap a month to open the details.",
      "Check **Present**, leave days, **Gross** and the deductions.",
      "**Net pay** is your take-home salary for the month.",
    ],
    stepsHi: [
      "हर महीने पर स्थिति लिखी है: **Approved**, **Released** या **Paid**।",
      "विवरण खोलने के लिए महीना दबाएँ।",
      "**Present**, छुट्टी के दिन, **Gross** और कटौतियाँ देखें।",
      "**Net pay** महीने का आपका हाथ में आने वाला वेतन है।",
    ],
    tipsEn: [
      "If you see **No payslip has been released yet.**, it appears once the office approves payroll.",
      "If you see **salary is being prepared**, wait for the office to approve it.",
      "If a month says **on hold**, speak to the office.",
    ],
    tipsHi: [
      "अगर **अभी कोई वेतन पर्ची जारी नहीं हुई है।** दिखे, तो वेतन स्वीकृत होने पर पर्ची आएगी।",
      "अगर **salary is being prepared** दिखे, तो दफ़्तर के स्वीकृत करने तक रुकें।",
      "अगर महीने पर **on hold** लिखा है, तो दफ़्तर से बात करें।",
    ],
  ),
  ScreenGuide(
    id: "chat-inbox",
    titleEn: "Read and reply to parent messages",
    titleHi: "अभिभावकों के संदेश पढ़ें और जवाब दें",
    stepsEn: [
      "Each row is one child's parent chat, with the last message.",
      "A number on the right shows unread messages.",
      "Tap a row to open the chat.",
      "Type your reply and send it.",
    ],
    stepsHi: [
      "हर पंक्ति एक बच्चे के अभिभावक की चैट है, आख़िरी संदेश के साथ।",
      "दाईं ओर का नंबर बिना पढ़े संदेश बताता है।",
      "चैट खोलने के लिए पंक्ति दबाएँ।",
      "अपना जवाब लिखें और भेजें।",
    ],
    tipsEn: [
      "If you see **You're not set as a class teacher for any section**, ask the office to assign you.",
      "**No messages yet — say hello** means that parent has not written yet.",
    ],
    tipsHi: [
      "अगर **आप किसी सेक्शन के कक्षा अध्यापक नहीं हैं** दिखे, तो दफ़्तर से कक्षा दिलवाएँ।",
      "**No messages yet — say hello** का मतलब अभिभावक ने अभी नहीं लिखा है।",
    ],
  ),
  ScreenGuide(
    id: "notices-staff",
    titleEn: "Read school notices and news",
    titleHi: "विद्यालय की सूचनाएँ और समाचार पढ़ें",
    stepsEn: [
      "Open **Notices** from your home screen; the screen is called **Notices & news**.",
      "Each item is tagged **Notice** or **News**.",
      "Read the title, text and the date it was published.",
      "Pull down to see new ones.",
    ],
    stepsHi: [
      "होम स्क्रीन से **नोटिस और समाचार** खोलें।",
      "हर चीज़ पर **नोटिस** या **समाचार** लिखा है।",
      "शीर्षक, विवरण और प्रकाशन की तारीख़ पढ़ें।",
      "नए देखने के लिए नीचे खींचें।",
    ],
    tipsEn: [
      "If you see **No notices published yet.**, check again later.",
      "If the list does not load, check the internet and pull down to refresh.",
    ],
    tipsHi: [
      "अगर **अभी कोई सूचना प्रकाशित नहीं है।** दिखे, तो बाद में देखें।",
      "अगर सूची न खुले, तो इंटरनेट देखें और नीचे खींचकर ताज़ा करें।",
    ],
  ),
];
