import { CRUD, type RbacFeatureDef } from "@/lib/rbacFeatureCatalog/types";

/** Masters — wired 6 Oct 2026 (masters-desk POST, lib/deskFeatureAuth). */
export const MASTERS_FEATURES: RbacFeatureDef[] = [
  {
    id: "masters.class_subjects",
    module: "masters",
    label: "Class subjects",
    blurb: "Which subjects each class studies — add, change or remove a subject for a class.",
    actions: CRUD,
    slices: ["classSubjects"],
    classScoped: true,
    tabs: ["subjects"],
  },
  {
    id: "masters.subjects",
    module: "masters",
    label: "Subject list",
    blurb: "The school's subject catalogue (codes, names, streams).",
    actions: CRUD,
    slices: ["subjects", "seniorStreams"],
    tabs: ["subjects"],
  },
  {
    id: "masters.classes_sections",
    module: "masters",
    label: "Classes & sections",
    blurb: "Classes, sections and campuses.",
    actions: CRUD,
    slices: ["classes", "sections", "campuses"],
    tabs: ["classes", "campuses"],
  },
  {
    id: "masters.academic_calendar",
    module: "masters",
    label: "Session, terms & holidays",
    blurb: "Academic years, terms, school timing and the holiday list.",
    actions: CRUD,
    slices: ["academicYears", "academicTerms", "schoolTiming", "holidays"],
    tabs: ["academic", "holidays"],
  },
  {
    id: "masters.fee_heads",
    module: "masters",
    label: "Fee heads & groups",
    blurb: "Fee heads, their categories and fee groups.",
    actions: CRUD,
    slices: ["feeHeads", "feeHeadCategories", "feeGroups"],
    tabs: ["fee-heads", "fee-groups"],
  },
  {
    id: "masters.fee_structure",
    module: "masters",
    label: "Fee structure & due dates",
    blurb: "Fee amounts per class, instalments, late fee and fee rules.",
    actions: CRUD,
    slices: [
      "feeStructureLines",
      "installments",
      "lateFeeRules",
      "midYearFeePolicy",
      "feeBackdatePolicy",
    ],
    tabs: ["fee-structure", "installments", "late-fee", "mid-year"],
  },
  {
    id: "masters.special_fees",
    module: "masters",
    label: "Special fees",
    blurb: "One-off and special fees and who they apply to.",
    actions: CRUD,
    slices: ["specialFees", "specialFeeAssignments"],
    tabs: ["special-fees"],
  },
  {
    id: "masters.concessions",
    module: "masters",
    label: "Concessions",
    blurb: "Concession kinds, rules and grants.",
    actions: CRUD,
    slices: ["concessionKinds", "concessions", "concessionGrants"],
    tabs: ["concessions"],
  },
  {
    id: "masters.school_profile",
    module: "masters",
    label: "School profile & numbering",
    blurb: "School details, statutory setup and number series.",
    actions: ["view", "edit"],
    slices: ["schoolProfile", "statutoryConfig", "numberSeries"],
    tabs: ["school", "brand", "series"],
  },
  {
    id: "masters.departments",
    module: "masters",
    label: "Departments & designations",
    blurb: "Staff departments and designations.",
    actions: CRUD,
    slices: ["departments", "designations"],
    tabs: ["staff"],
  },
];
