#!/usr/bin/env python3
"""
Generate apps/web/.env.verify.local from .env.local.

The verification stack must be incapable of touching anything real: it points at
the verification Supabase project, and every outbound credential (WhatsApp, push,
AI, BigQuery, cron/mirror secrets) is blanked. Google Maps is kept because stop
distances are read-only lookups that verification actually needs to exercise.
"""
import re, sys, pathlib

SRC = pathlib.Path("apps/web/.env.local")
DST = pathlib.Path("apps/web/.env.verify.local")

VERIFY_REF = "tmgtivjwelxgxajkcvmx"
VERIFY_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZ3Rpdmp3ZWx4Z3hhamtjdm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczMTEyNjksImV4cCI6MjEwMjg4NzI2OX0.hwOkXJ5v7dtHf5wfGoNvX6KsN43FVFhKzdfw9BRe6Hk"

REPLACE = {
    "NEXT_PUBLIC_SUPABASE_URL": f"https://{VERIFY_REF}.supabase.co",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY": VERIFY_ANON,
    "SUPABASE_SERVICE_ROLE_KEY": "PASTE_VERIFY_SERVICE_ROLE_KEY_HERE",
    "DATABASE_URL": "PASTE_VERIFY_POOLER_URL_HERE",
    "DIRECT_URL": "PASTE_VERIFY_DIRECT_URL_HERE",
    "NEXT_PUBLIC_APP_URL": "http://localhost:3000",
}

# Anything that can reach a real person, a real bill, or real infrastructure.
BLANK = {
    "WHATSAPP_TOKEN", "WHATSAPP_PHONE_ID", "WHATSAPP_WABA_ID",
    "WHATSAPP_VERIFY_TOKEN", "WA_APP_SECRET", "WA_DISPATCH_SECRET",
    "MIRROR_SYNC_SECRET", "CRON_SECRET",
    "VAPID_PRIVATE_KEY", "VAPID_PUBLIC_KEY", "NEXT_PUBLIC_VAPID_PUBLIC_KEY",
    "GOOGLE_APPLICATION_CREDENTIALS",
    "GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET",
    "BIGQUERY_PROJECT_ID", "BIGQUERY_DATASET", "BIGQUERY_LOCATION",
    "BIGQUERY_TENANT_SLUG",
    "OPENAI_API_KEY", "GEMINI_API_KEY", "SARVAM_API_KEY",
    "FLEET_EDGE_SOS_NOTIFY_MOBILE", "FLEET_EDGE_ALLOWED_IPS",
    "REDIS_URL",
}

if not SRC.exists():
    sys.exit("apps/web/.env.local not found")

out, seen = [], set()
out.append("# GENERATED by scripts/make-verify-env.py — do not edit by hand.")
out.append("# Points the dev server at the VERIFICATION Supabase project.")
out.append(f"# Project ref: {VERIFY_REF}")
out.append("# Outbound credentials are blanked on purpose: nothing here can message")
out.append("# a parent, spend AI credit, or write to production.")
out.append("")

for raw in SRC.read_text().splitlines():
    m = re.match(r"^([A-Z_0-9]+)=(.*)$", raw)
    if not m:
        out.append(raw)
        continue
    key = m.group(1)
    seen.add(key)
    if key in REPLACE:
        out.append(f"{key}={REPLACE[key]}")
    elif key in BLANK:
        out.append(f"{key}=")
    else:
        out.append(raw)

for key, val in REPLACE.items():
    if key not in seen:
        out.append(f"{key}={val}")

DST.write_text("\n".join(out) + "\n")
print(f"wrote {DST}")
print(f"  replaced: {len([k for k in REPLACE if k in seen])} keys")
print(f"  blanked:  {len([k for k in BLANK if k in seen])} keys")
