/**
 * Turn the fetched CASE Network data into the seed migration.
 *
 * Run from this directory:  node build-seed.mjs > ../../supabase/migrations/<ts>_learning_standards_seed_maths.sql
 *
 * Reads the four files beside it — standards.jsonl, prereqs.jsonl,
 * components.jsonl, mapping.maths.json — and writes idempotent SQL. Re-running
 * it after a re-fetch produces a migration that can be applied over the old
 * one: every insert is ON CONFLICT DO UPDATE, and no teacher's review decision
 * is ever overwritten (see the chapter-map insert).
 */
import { readFileSync } from "node:fs";

const lines = (f) => readFileSync(f, "utf8").trim().split("\n").map((l) => JSON.parse(l));
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
// CCSS writes kindergarten as "K"; we store the publisher's own band, and this
// is the only place it becomes a number.
const gradeNum = (g) => (String(g).toUpperCase() === "K" ? 0 : Number(g));

const standards = lines("standards.jsonl");
const prereqs = lines("prereqs.jsonl");
const components = lines("components.jsonl");
const mapping = JSON.parse(readFileSync("mapping.maths.json", "utf8"));

// The books these chapter positions belong to. Guarding on the textbook id
// rather than on (grade, subject) means that if the school ever changes maths
// publisher, this seed simply maps nothing rather than silently attaching
// Propel's chapter 7 to somebody else's chapter 7.
const BOOKS = {
  1: "sb-g1-maths-propel-edition-a-mathematics-grade-1",
  2: "sb-g2-maths-propel-edition-a-mathematics-grade-2",
  3: "sb-g3-maths-propel-edition-a-mathematics-grade-3",
  4: "sb-g4-maths-propel-edition-a-mathematics-grade-4",
  5: "sb-g5-maths-propel-edition-a-mathematics-grade-5",
  6: "sb-g6-maths-propel-new-prime-mathematics-coursebook-grade-6",
  7: "sb-g7-maths-propel-new-prime-mathematics-coursebook-grade-7",
  8: "sb-g8-maths-propel-new-prime-mathematics-coursebook-grade-8",
};

/* ── every standard we hold, mapped or merely a prerequisite ────────── */
const all = new Map();
for (const s of standards) {
  const g = s.grades.map(gradeNum);
  all.set(s.code, { uuid: s.case_uuid, statement: s.statement, lo: Math.min(...g), hi: Math.max(...g) });
}
for (const row of prereqs) {
  for (const p of row.prereqs) {
    if (all.has(p.code)) continue;
    const g = gradeNum(p.grade);
    all.set(p.code, { uuid: p.uuid, statement: p.statement, lo: g, hi: g });
  }
}

// A uuid must mean one code and one code one uuid, or the primary key and the
// unique index disagree with each other and the migration dies half-applied.
const byUuid = new Map();
for (const [code, s] of all) {
  if (byUuid.has(s.uuid)) throw new Error(`uuid ${s.uuid} claimed by ${byUuid.get(s.uuid)} and ${code}`);
  byUuid.set(s.uuid, code);
}

const out = [];
const w = (s) => out.push(s);

w(`-- CASE Network mathematics standards, and the map from them to Propel's
-- chapters for Classes 1-8. Generated by scripts/learning-commons/build-seed.mjs
-- from data fetched on 22 Sep 2026 — do not hand-edit; re-run the generator.
--
-- Three kinds of row, and they are not equally certain:
--
--   learning_standards / _components / _prereqs are PUBLISHED FACTS, copied
--   as the CASE Network states them.
--
--   textbook_chapter_standards is OUR JUDGEMENT about which standard a Propel
--   chapter teaches, and it arrives unreviewed. Nothing in the app can read it
--   until a teacher sets reviewed_at (the learning_chapter_outcomes view).
--
-- Chapters are mapped by WHAT THEY TEACH. Propel runs ahead of CCSS in places
-- — Class 5 sets profit and loss, which CCSS places in grade 7 — so the grade
-- numbers deliberately do not line up, and nothing joins on them.
--
-- Three chapters are deliberately left unmapped, and a re-run will leave them
-- unmapped again:
--   Class 1 ch12 Money, Class 2 ch11 Money — the only CCSS money standard
--     (2.MD.C.8) is written in dollars, quarters, dimes, nickels and pennies.
--     A rupee chapter must not inherit American currency as its outcome.
--   Class 8 ch3 A Story of Numbers — a history chapter; CCSS has no counterpart.
--
-- Learning components are seeded for the standards taught in Classes 3-8. The
-- components published for Classes 1-2 are representation micro-skills
-- ("represent addition with fingers", "…with sounds") which make poor question
-- targets; those standards carry their statement and nothing else.

begin;
`);

/* ── standards ───────────────────────────────────────────────────────── */
w(`-- ${all.size} standards: ${standards.length} mapped to a chapter, ${all.size - standards.length} held only because something maps to them as a prerequisite.`);
w(`insert into public.learning_standards (case_uuid, code, framework, subject, statement, grade_low, grade_high) values`);
w([...all.entries()]
  .map(([code, s]) => `  (${q(s.uuid)}, ${q(code)}, 'ccss-math', 'Mathematics', ${q(s.statement)}, ${s.lo}, ${s.hi})`)
  .join(",\n"));
w(`on conflict (case_uuid) do update set
  code = excluded.code,
  statement = excluded.statement,
  grade_low = excluded.grade_low,
  grade_high = excluded.grade_high,
  fetched_at = now();
`);

/* ── components ──────────────────────────────────────────────────────── */
const comps = components.flatMap((r) =>
  all.has(r.code) ? r.components.map((c) => ({ uuid: all.get(r.code).uuid, id: c.id, d: c.d })) : []
);
w(`-- ${comps.length} learning components across ${components.length} standards.`);
w(`insert into public.learning_standard_components (case_uuid, component_id, description) values`);
w(comps.map((c) => `  (${q(c.uuid)}, ${q(c.id)}, ${q(c.d)})`).join(",\n"));
w(`on conflict (case_uuid, component_id) do update set description = excluded.description;
`);

/* ── prerequisite edges ──────────────────────────────────────────────── */
const edges = [];
for (const row of prereqs) {
  const to = all.get(row.code);
  if (!to) continue;
  for (const p of row.prereqs) {
    const from = all.get(p.code);
    // The schema forbids a self-edge; the Coherence Map does not emit one, but
    // a future re-fetch might, and a cycle would spin the drill's backward walk.
    if (!from || from.uuid === to.uuid) continue;
    edges.push([to.uuid, from.uuid]);
  }
}
w(`-- ${edges.length} prerequisite edges from the SAP Coherence Map. Read as:
-- to sit \`case_uuid\`, a child needs \`prereq_case_uuid\` first.`);
w(`insert into public.learning_standard_prereqs (case_uuid, prereq_case_uuid) values`);
w(edges.map(([a, b]) => `  (${q(a)}, ${q(b)})`).join(",\n"));
w(`on conflict do nothing;
`);

/* ── chapter map ─────────────────────────────────────────────────────── */
const rows = [];
for (const ch of mapping.chapters) {
  const book = BOOKS[ch.grade];
  for (const code of ch.codes) {
    const s = all.get(code);
    if (!s) throw new Error(`chapter G${ch.grade} ch${ch.position} maps to unknown ${code}`);
    rows.push({ book, position: ch.position, uuid: s.uuid, conf: ch.confidence, why: ch.rationale, name: ch.name, code });
  }
}
const unmapped = mapping.chapters.filter((c) => c.codes.length === 0);
w(`-- ${rows.length} chapter-to-standard matches over ${mapping.chapters.length - unmapped.length} chapters.
-- Written for EVERY tenant that owns the book, joined through
-- school_textbook_chapters so a chapter we do not have is simply skipped.
--
-- ON CONFLICT DO NOTHING, not DO UPDATE: once this row exists a teacher may
-- have reviewed or rejected it, and a re-seed must never quietly undo that.`);
w(`insert into public.textbook_chapter_standards (tenant_id, textbook_id, position, case_uuid, confidence, rationale)`);
w(rows
  .map(
    // The uuid needs an explicit cast: unlike a VALUES list, a SELECT gets no
    // assignment coercion from text, and Postgres rejects the whole statement.
    (r) => `select c.tenant_id, c.textbook_id, c.position, ${q(r.uuid)}::uuid, ${q(r.conf)}, ${q(r.why)}
  from public.school_textbook_chapters c
  where c.textbook_id = ${q(r.book)} and c.position = ${r.position}  -- ${r.name} -> ${r.code}`
  )
  .join("\nunion all\n"));
w(`on conflict (tenant_id, textbook_id, position, case_uuid) do nothing;
`);

w(`commit;`);
console.log(out.join("\n"));
