/**
 * Student birthday cards & greetings — the pure part.
 *
 *  - Who: active students whose DOB (month-day) matches a date.
 *  - Card: one of several designs × formats (square for WhatsApp/Instagram,
 *    story, landscape for Facebook, A5 portrait for print), rendered server-side
 *    by /api/birthday/card (next/og). The design + format choice lives here;
 *    the drawing lives in birthdayCardDesigns.tsx.
 *  - Message: templates per language with placeholders, editable by the
 *    school; rendered with the family's own details. Nothing is generated by
 *    a model — a birthday wish has no facts to get wrong and must be instant.
 *  - Settings (module_local_state "birthday_settings"): chosen design/format,
 *    message templates, auto-send on/off + hour, WhatsApp template for
 *    outside-24h delivery, social posting (off by default, photos only on
 *    explicit opt-in), and a send log keyed by student+date so a day is never
 *    sent twice.
 */

import { writeCacheOrInvalidate } from "@/lib/browserStorage";
import { assertModulePermission } from "@/lib/rbacGuard";
import { householdLanguage, type HouseholdLanguage, type HouseholdPrefsLike } from "@/lib/householdPrefs";

/* ─── Designs & formats ─────────────────────────────────────────────── */

export type BirthdayDesignId = "confetti" | "balloons" | "stars" | "pastel" | "classic" | "minimal";
export type BirthdayFormatId = "square" | "story" | "landscape" | "a5";

export const BIRTHDAY_DESIGNS: { id: BirthdayDesignId; label: string; hint: string; accent: string; bg: string; ink: string }[] = [
  { id: "confetti", label: "Confetti", hint: "Bright, playful — primary classes", accent: "#ff6b6b", bg: "#fff7ed", ink: "#1f2937" },
  { id: "balloons", label: "Balloons", hint: "Soft sky with balloons", accent: "#2563eb", bg: "#eff6ff", ink: "#1e3a8a" },
  { id: "stars", label: "Night stars", hint: "Deep navy, gold stars — seniors", accent: "#fbbf24", bg: "#0f172a", ink: "#f8fafc" },
  { id: "pastel", label: "Pastel floral", hint: "Gentle pinks and greens", accent: "#db2777", bg: "#fdf2f8", ink: "#4a044e" },
  { id: "classic", label: "Classic crest", hint: "School colours, crest forward — formal", accent: "#c5a028", bg: "#f8f6ee", ink: "#1f2f4f" },
  { id: "minimal", label: "Minimal bold", hint: "Big name, clean — social feeds", accent: "#0f766e", bg: "#ffffff", ink: "#111827" },
];

export const BIRTHDAY_FORMATS: { id: BirthdayFormatId; label: string; width: number; height: number; use: string }[] = [
  { id: "square", label: "Square 1:1", width: 1080, height: 1080, use: "WhatsApp · Instagram post" },
  { id: "story", label: "Story 9:16", width: 1080, height: 1920, use: "Instagram / WhatsApp status" },
  { id: "landscape", label: "Landscape", width: 1200, height: 630, use: "Facebook post · website banner" },
  { id: "a5", label: "A5 print", width: 1240, height: 1748, use: "Printed card (148×210 mm @ ~210 dpi)" },
];

export function normalizeDesign(v: unknown): BirthdayDesignId {
  return BIRTHDAY_DESIGNS.some((d) => d.id === v) ? (v as BirthdayDesignId) : "confetti";
}
export function normalizeFormat(v: unknown): BirthdayFormatId {
  return BIRTHDAY_FORMATS.some((f) => f.id === v) ? (v as BirthdayFormatId) : "square";
}

/* ─── Who has a birthday ───────────────────────────────────────────── */

export type BirthdayStudentLike = { id: string; fullName: string; dob: string; status?: string; classId?: string; sectionId?: string; householdId?: string; photoUrl?: string; admissionNo?: string; academicYearCode?: string };

/**
 * SIS keeps one row per student per session; the same child must count once.
 * Key = admission no (fallback name+dob), keep the row with the latest
 * session code (ties → the one with a photo).
 */
export function dedupeStudents<T extends BirthdayStudentLike>(students: T[]): T[] {
  const best = new Map<string, T>();
  for (const s of students) {
    const key = (s.admissionNo || "").trim() || `${s.fullName.trim().toLowerCase()}|${s.dob}`;
    const cur = best.get(key);
    if (!cur) {
      best.set(key, s);
      continue;
    }
    const a = s.academicYearCode || "";
    const b = cur.academicYearCode || "";
    if (a > b || (a === b && !cur.photoUrl && !!s.photoUrl)) best.set(key, s);
  }
  return [...best.values()];
}

/** "YYYY-MM-DD" → "MM-DD"; invalid → "" */
export function monthDay(ymd: string): string {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec((ymd || "").slice(0, 10));
  return m ? `${m[2]}-${m[3]}` : "";
}

/** Students whose birthday falls on `dateYmd` (29-Feb birthdays count on 28-Feb in non-leap years). */
export function studentsWithBirthday<T extends BirthdayStudentLike>(students: T[], dateYmd: string): T[] {
  const md = monthDay(dateYmd);
  if (!md) return [];
  const year = Number(dateYmd.slice(0, 4));
  const leap = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
  return dedupeStudents(students.filter((s) => (s.status ?? "active") === "active"))
    .filter((s) => {
      const b = monthDay(s.dob);
      if (!b) return false;
      if (b === md) return true;
      return b === "02-29" && md === "02-28" && !leap;
    })
    .sort((a, b) => a.fullName.localeCompare(b.fullName));
}

/** Upcoming birthdays within `days` from `fromYmd` (inclusive), with the date they fall on. */
export function upcomingBirthdays<T extends BirthdayStudentLike>(students: T[], fromYmd: string, days: number): { date: string; student: T; age: number | null }[] {
  const out: { date: string; student: T; age: number | null }[] = [];
  const start = new Date(`${fromYmd}T00:00:00`);
  for (let i = 0; i < days; i++) {
    const d = new Date(start);
    d.setDate(start.getDate() + i);
    const ymd = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
    for (const s of studentsWithBirthday(students, ymd)) out.push({ date: ymd, student: s, age: ageOn(s.dob, ymd) });
  }
  return out;
}

export function ageOn(dob: string, ymd: string): number | null {
  const by = Number((dob || "").slice(0, 4));
  const y = Number(ymd.slice(0, 4));
  if (!by || !y || by > y) return null;
  return y - by;
}

/* ─── Message templates ────────────────────────────────────────────── */

export type BirthdayMessageLanguage = "en" | "hi";

export const BIRTHDAY_PLACEHOLDERS = ["{{childName}}", "{{firstName}}", "{{guardianName}}", "{{className}}", "{{age}}", "{{schoolName}}", "{{cardLink}}"] as const;

export const DEFAULT_BIRTHDAY_MESSAGES: Record<BirthdayMessageLanguage, { label: string; body: string }[]> = {
  en: [
    { label: "Warm", body: "Dear {{guardianName}}, 🎂 the whole {{schoolName}} family wishes {{childName}} ({{className}}) a very happy birthday! May the year ahead be full of learning, laughter and new friends. Your birthday card: {{cardLink}}" },
    { label: "Short", body: "Happy birthday, {{firstName}}! 🎉 Warm wishes from everyone at {{schoolName}}. {{cardLink}}" },
    { label: "Formal", body: "Dear {{guardianName}}, on behalf of {{schoolName}}, we extend our warmest birthday wishes to {{childName}} of {{className}}. We are proud to have {{firstName}} with us. Birthday card: {{cardLink}}" },
  ],
  hi: [
    { label: "Warm", body: "प्रिय {{guardianName}} जी, 🎂 {{schoolName}} परिवार की ओर से {{childName}} ({{className}}) को जन्मदिन की हार्दिक शुभकामनाएँ! आने वाला वर्ष सीखने, हँसी और नए दोस्तों से भरा हो। जन्मदिन कार्ड: {{cardLink}}" },
    { label: "Short", body: "जन्मदिन मुबारक, {{firstName}}! 🎉 {{schoolName}} की ओर से ढेर सारी शुभकामनाएँ। {{cardLink}}" },
    { label: "Formal", body: "प्रिय {{guardianName}} जी, {{schoolName}} की ओर से {{className}} के {{childName}} को जन्मदिन की शुभकामनाएँ। {{firstName}} हमारे विद्यालय का गौरव है। जन्मदिन कार्ड: {{cardLink}}" },
  ],
};

export const DEFAULT_SOCIAL_CAPTION = "🎂 Happy birthday to {{names}}! The whole {{schoolName}} family wishes you a wonderful year ahead. #HappyBirthday #{{schoolTag}}";

export function renderBirthdayMessage(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k: string) => (vars[k] ?? "")).replace(/[ \t]{2,}/g, " ").trim();
}

/** Which message language a family gets: their preference, else the school default. Regional → Hindi. */
export function birthdayMessageLanguageFor(hh: HouseholdPrefsLike, schoolDefault: BirthdayMessageLanguage): BirthdayMessageLanguage {
  const { language, source } = householdLanguage(hh, schoolDefault as HouseholdLanguage);
  if (source === "default") return schoolDefault;
  return language === "en" ? "en" : "hi";
}

/* ─── Settings ─────────────────────────────────────────────────────── */

export type BirthdaySettings = {
  version: 1;
  design: BirthdayDesignId;
  format: BirthdayFormatId;
  /** Optional wish line printed on the card ("" = design default) */
  cardWish: string;
  /** Message templates the school edited (index into DEFAULT_* when empty) */
  messageEn: string;
  messageHi: string;
  defaultLanguage: BirthdayMessageLanguage;
  /** Send greetings to the family's WhatsApp automatically on the day */
  autoSend: boolean;
  /** IST hour (0–23) the daily tick sends at */
  sendHour: number;
  /** Approved Meta template (IMAGE header + body vars) for outside-24h delivery; "" = free text only */
  waTemplateName: string;
  waTemplateLanguage: string;
  /** Body variable order for the template, by placeholder key (e.g. ["childName","className","schoolName"]) */
  waTemplateVars: string[];
  /** Post a birthday greeting on the school's social pages */
  socialEnabled: boolean;
  /** Include the student's photo on the social card (off = names-only group card) */
  socialIncludePhoto: boolean;
  socialCaption: string;
  socialDesign: BirthdayDesignId;
  updatedAt: string;
};

export type BirthdayLogEntry = {
  /** `${studentId}:${YYYY-MM-DD}` */
  key: string;
  studentId: string;
  date: string;
  channel: "whatsapp" | "social" | "manual";
  status: "sent" | "failed" | "deferred" | "skipped";
  detail: string;
  at: string;
};

export type BirthdayState = { settings: BirthdaySettings; log: BirthdayLogEntry[] };

const STORAGE_KEY = "bhb_birthday_settings_v1";
const str = (v: unknown, max: number) => String(v ?? "").trim().slice(0, max);
const LOG_MAX = 2000;

export function defaultBirthdaySettings(): BirthdaySettings {
  return {
    version: 1,
    design: "confetti",
    format: "square",
    cardWish: "",
    messageEn: "",
    messageHi: "",
    defaultLanguage: "en",
    autoSend: false,
    sendHour: 9,
    waTemplateName: "",
    waTemplateLanguage: "en",
    waTemplateVars: [],
    socialEnabled: false,
    socialIncludePhoto: false,
    socialCaption: "",
    socialDesign: "minimal",
    updatedAt: "",
  };
}

export function normalizeBirthdaySettings(raw: unknown): BirthdaySettings {
  const d = defaultBirthdaySettings();
  if (!raw || typeof raw !== "object") return d;
  const r = raw as Partial<BirthdaySettings>;
  return {
    version: 1,
    design: normalizeDesign(r.design),
    format: normalizeFormat(r.format),
    cardWish: str(r.cardWish, 120),
    messageEn: str(r.messageEn, 1000),
    messageHi: str(r.messageHi, 1000),
    defaultLanguage: r.defaultLanguage === "hi" ? "hi" : "en",
    autoSend: r.autoSend === true,
    sendHour: Number.isInteger(Number(r.sendHour)) && Number(r.sendHour) >= 0 && Number(r.sendHour) <= 23 ? Number(r.sendHour) : 9,
    waTemplateName: str(r.waTemplateName, 120),
    waTemplateLanguage: str(r.waTemplateLanguage, 10) || "en",
    waTemplateVars: Array.isArray(r.waTemplateVars) ? r.waTemplateVars.map((x) => str(x, 30)).filter(Boolean).slice(0, 8) : [],
    socialEnabled: r.socialEnabled === true,
    socialIncludePhoto: r.socialIncludePhoto === true,
    socialCaption: str(r.socialCaption, 600),
    socialDesign: normalizeDesign(r.socialDesign ?? "minimal"),
    updatedAt: str(r.updatedAt, 40),
  };
}

export function normalizeBirthdayState(raw: unknown): BirthdayState {
  const r = (raw ?? {}) as Partial<BirthdayState>;
  const seen = new Set<string>();
  const log: BirthdayLogEntry[] = [];
  for (const e of Array.isArray(r.log) ? r.log : []) {
    const x = (e ?? {}) as Partial<BirthdayLogEntry>;
    const key = str(x.key, 80);
    if (!key || seen.has(key + String(x.channel))) continue;
    seen.add(key + String(x.channel));
    log.push({
      key,
      studentId: str(x.studentId, 40),
      date: str(x.date, 10),
      channel: x.channel === "social" || x.channel === "manual" ? x.channel : "whatsapp",
      status: x.status === "failed" || x.status === "deferred" || x.status === "skipped" ? x.status : "sent",
      detail: str(x.detail, 200),
      at: str(x.at, 40),
    });
  }
  return { settings: normalizeBirthdaySettings(r.settings), log: log.slice(-LOG_MAX) };
}

export function emptyBirthdayState(): BirthdayState {
  return { settings: defaultBirthdaySettings(), log: [] };
}

export function loadBirthdayState(): BirthdayState {
  if (typeof window === "undefined") return emptyBirthdayState();
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    return raw ? normalizeBirthdayState(JSON.parse(raw)) : emptyBirthdayState();
  } catch {
    return emptyBirthdayState();
  }
}

export function saveBirthdayState(state: BirthdayState): BirthdayState {
  const next = normalizeBirthdayState({ ...state, settings: { ...state.settings, updatedAt: new Date().toISOString() } });
  if (!assertModulePermission("students", "edit", "saveBirthdayState")) return next;
  if (typeof window !== "undefined") {
    writeCacheOrInvalidate(STORAGE_KEY, JSON.stringify(next));
    void import("@/lib/localModulesPersistence").then((m) => m.scheduleModuleStateSync("birthday_settings", next));
    window.dispatchEvent(new CustomEvent("bhb-birthday-settings"));
  }
  return next;
}

export function writeBirthdayStateLocalRaw(state: BirthdayState): void {
  if (typeof window === "undefined") return;
  try {
    writeCacheOrInvalidate(STORAGE_KEY, JSON.stringify(normalizeBirthdayState(state)));
  } catch {
    /* quota */
  }
  window.dispatchEvent(new CustomEvent("bhb-birthday-settings"));
}

export function birthdayStateIsEmpty(s: BirthdayState): boolean {
  return !s.settings.updatedAt && s.log.length === 0;
}

/** Merge-safe log append (server and client both write; union by key+channel, newest wins). */
export function appendBirthdayLog(state: BirthdayState, entries: BirthdayLogEntry[]): BirthdayState {
  const map = new Map(state.log.map((e) => [`${e.key}|${e.channel}`, e]));
  for (const e of entries) map.set(`${e.key}|${e.channel}`, e);
  return { ...state, log: [...map.values()].sort((a, b) => a.at.localeCompare(b.at)).slice(-LOG_MAX) };
}

export function alreadySent(state: BirthdayState, studentId: string, date: string, channel: BirthdayLogEntry["channel"]): boolean {
  return state.log.some((e) => e.studentId === studentId && e.date === date && e.channel === channel && e.status === "sent");
}

/** The text for one family. */
export function birthdayMessageFor(opts: {
  settings: BirthdaySettings;
  language: BirthdayMessageLanguage;
  childName: string;
  guardianName: string;
  className: string;
  age: number | null;
  schoolName: string;
  cardLink: string;
}): string {
  const custom = opts.language === "hi" ? opts.settings.messageHi : opts.settings.messageEn;
  const template = custom || DEFAULT_BIRTHDAY_MESSAGES[opts.language][0].body;
  const firstName = (opts.childName || "").split(/\s+/)[0] || opts.childName;
  return renderBirthdayMessage(template, {
    childName: opts.childName,
    firstName,
    guardianName: opts.guardianName || (opts.language === "hi" ? "अभिभावक" : "Parent"),
    className: opts.className,
    age: opts.age != null ? String(opts.age) : "",
    schoolName: opts.schoolName,
    cardLink: opts.cardLink,
  });
}
