/**
 * Step-by-step guides for notices, news, gallery, the WhatsApp inbox, the
 * website and modules screens, and one guide per important tab of the big
 * modules (students, fees, accounts, exams, masters, attendance, admissions,
 * comms, transport). Joined into the guide list by lib/erpAiPageGuides.ts.
 *
 * Note: Students and Comms write ?tab= to the address bar when a tab is
 * clicked; the other big modules read ?tab= only on load, so their tab
 * guides show when a tab is opened by link.
 */

import type { ErpAiPageGuideDef } from "@/lib/erpAiPageGuideTypes";

export const PAGE_GUIDES_D: ErpAiPageGuideDef[] = [
  // ───────────── Part A ─────────────
  {
    id: "comms-notices",
    paths: ["/notices", "/comms"],
    tab: "notices",
    pageLabel: "Notices",
    title: "Write, schedule and publish notices and circulars",
    module: "notices",
    chipLabel: "How Notices works",
    steps: [
      "Under **New notice**, type a **Title** and **Body**. Both are required.",
      "Pick the **Audience** (Everyone, Staff, Parents or Students). Tick **Pin** to keep the notice at the top.",
      "Click **Publish now**, or **Save draft** to finish it later.",
      "To publish it later, set **Publish at (schedule)** and click **Schedule**.",
      "In the list, use the row menu to **Edit**, **Publish**, **Archive**, **Post to social** or **Delete**.",
      "Click **Sync published notices to AI** so the parent WhatsApp bot can answer from them.",
    ],
    stuckTips: [
      'If you see "Title is required" or "Body is required", fill in both boxes before saving.',
      'If "Pick a publish date & time" appears, set **Publish at (schedule)** first, then click **Schedule**.',
      "If **Sync published notices to AI** is greyed out, OPENAI_API_KEY is not set up. Ask your admin.",
      'If you see "No permission to create notices", ask an admin to give your role Notices access.',
    ],
  },
  {
    id: "comms-news",
    paths: ["/news", "/comms"],
    tab: "news",
    pageLabel: "News",
    title: "Publish school news stories for the parent portal",
    module: "news",
    chipLabel: "How News works",
    steps: [
      "Under **New story**, fill in the **Headline**, **Short summary** and **Full story**.",
      "If you want a picture, paste a **Cover image URL**. This is optional.",
      "Check the cross-post options under the form, then click **Publish now** or **Save draft**.",
      "To publish later, set **Publish at (schedule)** and click **Schedule**.",
      "In the list, click **Publish** on a draft, or **Post to social** on a published story.",
      "Use **Edit** or **Delete** on a story to change or remove it.",
    ],
    stuckTips: [
      'If you see "Title is required" or "Body is required", fill in both the Headline and the Full story.',
      'If "Pick a publish date & time" appears, set **Publish at (schedule)** before clicking **Schedule**.',
      'If you see "No permission to create news", ask an admin to give your role News access.',
    ],
  },
  {
    id: "comms-gallery",
    paths: ["/gallery", "/comms"],
    tab: "gallery",
    pageLabel: "Gallery",
    title: "Create photo albums and publish them to parents",
    module: "gallery",
    chipLabel: "How Gallery works",
    steps: [
      "Under **New album**, type the **Album title** (e.g. Annual day 2026). A **Description** is optional.",
      "Click **Create draft** or **Publish now**. To publish later, set **Publish at** and click **Schedule**.",
      "Click an album card to open it, then click **Add photos** to upload images.",
      "When the photos are in, click **Publish album** so parents can see it.",
      "Use **Delete** on a photo to remove it, or **Edit** / **Delete** on the album card.",
    ],
    stuckTips: [
      'If you see "Album title is required", type a title before you create the album.',
      "If **Add photos** is missing, click an album card first. Photos always go into the open album.",
      'If you see "Upload failed", check the files are images and try again.',
      'If "Pick a publish date & time" appears, fill in **Publish at** before clicking **Schedule**.',
    ],
  },
  {
    id: "comms-inbox",
    paths: ["/comms"],
    tab: "inbox",
    pageLabel: "Staff inbox",
    title: "Read and clear your staff notifications",
    module: "notifications",
    chipLabel: "How Inbox works",
    steps: [
      "Unread notifications are highlighted in gold.",
      "Click a notification to mark it read and go to the screen it links to.",
      "Use the search box to find a notification by title, body or status.",
      "Click **Mark all read** to clear every unread highlight.",
      "Click **Prune inbox** to remove older notifications.",
    ],
    stuckTips: [
      "If the list says no notifications match, click **Clear** next to the search box.",
      "If clicking a notification doesn't open a screen, it has no link. Do the work from that module directly.",
    ],
  },
  {
    id: "website",
    paths: ["/website"],
    pageLabel: "Website",
    title: "Edit the school website's pages, pictures and published items",
    module: "website",
    chipLabel: "How Website works",
    steps: [
      "On **Pages**, under **Add a page**, type the **Page title**. The **Address** fills in by itself.",
      "Tick **Front page** for the home page and pick a **Language**. Click **Add page**. New pages start as drafts.",
      "Open the row menu, choose **Edit page**, add content with **Add a block**, then click **Save … changes**.",
      "Click **Publish** when the page is ready. If it says **Ready for the director to publish**, the director has to publish it.",
      "On **Pictures & files**, click **Choose files** to upload, then write a description for each picture.",
      "On **Show on website**, click **Show on website** or **Take off the website** for each item.",
    ],
    stuckTips: [
      'If you see "Give the page a title.", type a Page title before clicking **Add page**.',
      'If "This page is not ready: …" appears, fix everything in the **Not ready to publish** list first.',
      'If you see "Your role cannot create website pages.", ask an admin to add the Website module to your role.',
      "If a picture won't show on the public site, give it a description and check that the family's consent hasn't been withdrawn.",
    ],
  },
  {
    id: "modules",
    paths: ["/modules"],
    pageLabel: "Modules",
    title: "Turn school modules on or off",
    module: "settings",
    chipLabel: "How Modules works",
    steps: [
      "The counter at the top shows how many of the switchable modules are on.",
      "Find the module in its group. Its status shows **ON** or **OFF**.",
      "Click **Enable** to turn a module on, or **Disable** to hide it from Home and universal search.",
      "Click **Open** on a module that is on to go straight to it.",
      "Use **Enable all** or **Disable all** to change everything at once. Home and Modules always stay on.",
    ],
    stuckTips: [
      "If a module has no **Disable** button, it is marked **Always on** and can't be switched off.",
      'If a module is missing from Home, check here. It may be OFF ("default off").',
    ],
  },

  // ───────────── Part B: Students ─────────────
  {
    id: "students-roster",
    paths: ["/students"],
    tab: "roster",
    pageLabel: "Students · Overview",
    title: "Session stats and bulk student import",
    module: "students",
    chipLabel: "How Overview works",
    steps: [
      "Check the session stats at the top of **Overview**.",
      "To import students, click **Download CSV template** and fill it in.",
      "Choose your file and click **Refresh preview** to check the rows.",
      "Click **Import students**. The result shows how many were imported new and how many were updated.",
    ],
    stuckTips: [
      'If you see "Choose a CSV file first", pick the file before clicking **Import students**.',
      'If "No rows imported — fix errors below" appears, fix the listed rows in your file and import again.',
      'If you see "Could not read Excel file", save the sheet as CSV and try again.',
      "Never use **DELETE ALL STUDENTS** unless the director asks. It erases the whole roster.",
    ],
  },
  {
    id: "students-register",
    paths: ["/students"],
    tab: "register",
    pageLabel: "Students · Register",
    title: "Search, filter and manage the student list",
    module: "students",
    chipLabel: "How Register works",
    steps: [
      "Use **Views** to open a ready-made work list, or filter by class, tags and session.",
      "Switch between **List** and **Cards** at the top right.",
      "Open a student's row menu and choose **View details** or **Household & siblings**.",
      "Use **Mark inactive** for a student who has left. The record stays on file.",
      "Click **+ Add student** to add a new student.",
    ],
    stuckTips: [
      "If a student is missing, check the session. The list only shows the selected session.",
      "If a banner says a family has no WhatsApp number, add it from the banner. Receipts and messages need it.",
    ],
  },
  {
    id: "students-update",
    paths: ["/students"],
    tab: "update",
    pageLabel: "Students · Update",
    title: "Update details, photos, RFID cards and portal logins",
    module: "students",
    chipLabel: "How Update works",
    steps: [
      "Search for a student by name, admission no or roll, then edit them in **Update details**.",
      "For photos class by class, use **Student photos by class** or **Parent photos by class**. You can upload or use the camera.",
      "To upload photos in bulk, name each file by admission no (e.g. BHB-2025-101.jpg) and upload under **Student images**.",
      "Name parent photo files ADMNO_father.jpg, ADMNO_mother.jpg or ADMNO_parent.jpg and upload under **Parent images**.",
      "Under **Biometric / RFID**, scan or type the card no and the device enrolment id.",
      "Set the parent portal **Login password** under **Portal username & password**.",
    ],
    stuckTips: [
      'If you see "Select a student", search for the student and pick them first.',
      'If the result says some images were skipped, or "No photos applied", check the file names match admission numbers.',
    ],
  },
  {
    id: "students-upgrade",
    paths: ["/students"],
    tab: "upgrade",
    pageLabel: "Students · Upgrade",
    title:
      "Change one student's section, class or type, or promote a whole class",
    module: "students",
    chipLabel: "How Upgrade works",
    steps: [
      "Choose **Single student** to change one child, or **Whole class** to promote a section to the next year.",
      "For one child, search the student and pick **Section only**, **Class + section** or **Type only**.",
      "Choose the new section, class or type and add a reason. Click **Change section**, **Upgrade class** or **Change type**.",
      "For a whole class, pick the **From** class and section, then the **To** year, class and section.",
      "Tick students (or click **Select all**) and click **Promote N student(s)**.",
      "Roll numbers reset in the new class. Re-assign them from the **Overview** tab.",
    ],
    stuckTips: [
      'If you see "Select a student first", search for the student and pick them before saving.',
      'If "Pick the new class and section" or "Pick the new section" appears, fill in the new class or section.',
      'If you see "Pick a different student type (e.g. NEW → PROMOTE)", choose a type other than the current one.',
      'If "All N promotion(s) failed — see details below" appears, read the **Failed** list, fix each student and retry.',
    ],
  },
  {
    id: "students-duplicates",
    paths: ["/students"],
    tab: "duplicates",
    pageLabel: "Students · Duplicates",
    title: "Find and merge duplicate student records",
    module: "students",
    chipLabel: "How Duplicates works",
    steps: [
      "Each group shows records that look like the same child (same name, DOB, parents, PEN or mobile).",
      "Click **Open** on a record to check it before you decide.",
      "Choose the record to keep, then click **Merge others into selected**.",
      "Use **Remove** only for a true duplicate. It deletes that record.",
    ],
    stuckTips: [
      "**Remove** asks you to confirm and cannot be undone. If you're unsure, use **Merge others into selected**.",
      "If the same child keeps showing up, open both records and correct the DOB or parent names.",
    ],
  },
  {
    id: "students-doc-verify",
    paths: ["/students"],
    tab: "doc_verify",
    pageLabel: "Students · Doc verify",
    title: "Approve or reject uploaded student documents",
    module: "students",
    chipLabel: "How Doc verify works",
    steps: [
      "Go through each uploaded document in the queue.",
      "For image uploads, click **Vision scan** to check the document against the student's record.",
      "Click **Use suggested remark** to copy in the scan's suggestion.",
      'Click **Approve (correct)**, or **Reject (wrong)** with a remark such as "Blurry Aadhaar — please re-upload".',
    ],
    stuckTips: [
      "Add a remark when you reject, so the parent or staff member knows what to re-upload.",
      'If you see "Vision scan needs an image upload (JPG/PNG)", check PDFs by eye.',
      'If you see "Vision scan failed" or "Unreadable scan", review the document manually.',
    ],
  },
  {
    id: "students-siblings",
    paths: ["/students"],
    tab: "siblings",
    pageLabel: "Students · Siblings",
    title: "Link or separate sibling households",
    module: "students",
    chipLabel: "How Siblings works",
    steps: [
      "**Real siblings** lists students who already share one household.",
      "**Possible siblings** shows likely matches by parent mobile or name. Expand one to confirm and link it.",
      "Children with the same father and mother names are flagged, even across households.",
      "Click **Separate** to give a wrongly linked child a family of their own.",
    ],
    stuckTips: [
      'If you see "Could not separate", refresh the page and try again.',
      "If no matches appear, check that parent mobiles and names are filled in on the student profiles.",
    ],
  },
  {
    id: "students-udise",
    paths: ["/students"],
    tab: "udise",
    pageLabel: "Students · UDISE+",
    title: "UDISE+ compliance: PEN, APAAR and Aadhaar gaps",
    module: "compliance",
    chipLabel: "How UDISE+ works",
    steps: [
      "**Robot & setup**: install the robot in Chrome and confirm the school's answers once.",
      "**Students: portal ↔ ERP**: tick the differences found on UDISE+ and apply them.",
      "**Class sheets**: class teachers collect height, weight, blood group and similar details.",
      "**Compliance worklist**: fix PEN, APAAR and Aadhaar gaps. Use **Export call list CSV** to phone families.",
      "**Teachers** and **School profile**: sync staff details and the school's UDISE+ profile.",
    ],
    stuckTips: [
      'If you see "No incomplete students with a phone number to export", add parent mobiles in the student profiles first.',
      'If it says "All active SIS students already have a UDISE+ PEN", nothing is waiting to be registered.',
    ],
  },

  // ───────────── Part B: Fees ─────────────
  {
    id: "fees-receipts",
    paths: ["/fees"],
    tab: "receipts",
    pageLabel: "Fees · Receipts",
    title: "Find, reprint, resend or void fee receipts",
    module: "fees",
    chipLabel: "How Receipts works",
    steps: [
      "In the **Receipt register**, filter by date, student, parent, class, section, mode or cashier.",
      "Type a receipt no, UTR / UPI ref or manual book no in the reference box.",
      "Click **Open** to preview a receipt, then **Send WhatsApp** or **Print**.",
      "Click **Void** only to cancel a wrong receipt. Its dues reopen.",
      "If a row says its lines don't add up, click **Re-attach** to repair it.",
    ],
    stuckTips: [
      "Voiding asks you to confirm. Any store items on the receipt go back to ISSUED (unpaid).",
      'If you see "Cannot send a voided receipt", issue a new receipt from **Collect** instead.',
      'If you see "Already voided", someone already cancelled that receipt. Refresh the list.',
    ],
  },
  {
    id: "fees-delivery",
    paths: ["/fees"],
    tab: "delivery",
    pageLabel: "Fees · Delivered",
    title: "Check whether WhatsApp receipts reached parents",
    module: "fees",
    chipLabel: "How Delivered works",
    steps: [
      "**Delivered** lists the receipts sent on WhatsApp and their delivery status.",
      "Look for **Delivered but not read** to follow up with the parent.",
      "Click **Open receipt** to resend or print it.",
      "Click **Copy mobile** to call the parent.",
    ],
    stuckTips: [
      'If you see "Could not read delivery status", wait a minute and reopen the tab.',
      "If a parent has no WhatsApp, set their number on **Collect**. It's saved for every message to that family.",
    ],
  },
  {
    id: "fees-cheques",
    paths: ["/fees"],
    tab: "cheques",
    pageLabel: "Fees · Cheques",
    title: "Track fee cheques from in hand to cleared",
    module: "fees",
    chipLabel: "How Cheques works",
    steps: [
      "**Cheques** lists every fee cheque as In hand, Deposited, Cleared or Bounced.",
      "Enter the **Pay-in slip** no and click **Mark deposited** when you bank it.",
      "Click **Mark cleared** once the bank credits the money.",
      "If a cheque comes back, enter the **Bounce reason** and click **Bounce & void receipt**. Its dues reopen.",
      "Click the receipt number to open the linked receipt.",
    ],
    stuckTips: [
      'If you see "Enter bounce reason", fill in the reason (e.g. Insufficient funds) before bouncing.',
      'If "Cleared cheques cannot be bounced here" appears, ask Accounts to reverse the cheque in the books.',
      'If you see "Only open cheques can be cleared", the cheque is already cleared or bounced.',
      'If "Linked receipt is missing or voided" appears, check the receipt on the **Receipts** tab first.',
    ],
  },
  {
    id: "fees-manual",
    paths: ["/fees"],
    tab: "manual",
    pageLabel: "Fees · Manual book",
    title: "Post receipts written in the paper fee book",
    module: "fees",
    chipLabel: "How Manual book works",
    steps: [
      "Use **Find student** to search by name, admission no or mobile.",
      "Tick the dues on the paper receipt, or click **Select all dues**.",
      "Enter the book series and leaf no from the paper receipt (e.g. FEE-BOOK-A/4521).",
      "Click **Add payment** for each mode until the total matches the selected dues.",
      "Click **Post to ledger**. The receipt opens so you can print it.",
    ],
    stuckTips: [
      'If you see "Enter book series & leaf no." or "Manual receipt # must be numeric", fix the leaf number.',
      "If it shows **Still need ₹…**, add another payment line until the totals match.",
      'If "Select payment mode & account" appears, choose the mode and account before you add the amount.',
      'If you see "Enter instrument / txn date" or "Enter bank name", fill those in for the cheque or UPI.',
    ],
  },
  {
    id: "fees-paylinks",
    paths: ["/fees"],
    tab: "paylinks",
    pageLabel: "Fees · Pay links",
    title: "Send UPI payment links and confirm payment",
    module: "fees",
    chipLabel: "How Pay links works",
    steps: [
      "Create a link from **Collect**: tick the dues and click **Send UPI link**.",
      "**Pay links** shows the open links. Switch the filter to see all of them.",
      "Click **Copy link** or **WhatsApp** to send it to the parent.",
      "When the money arrives, click **Confirm paid**. A receipt is posted.",
      "Click **Cancel** to withdraw a link that isn't needed.",
    ],
    stuckTips: [
      'If you see "No WhatsApp number on this household — set it on Fee Take", add the number on **Collect**.',
      'If "Could not close the online payment for this link — try again." appears, wait a moment and cancel again.',
      'If "Select dues to include on the payment link" appears on Collect, tick at least one due first.',
    ],
  },
  {
    id: "fees-dayclose",
    paths: ["/fees"],
    tab: "dayclose",
    pageLabel: "Fees · Day close",
    title: "Count the cash drawer and hand the day to Accounts",
    module: "fees",
    chipLabel: "How Day close works",
    steps: [
      "**Review day book**: check what was collected today by type and mode. Fix any mistakes first.",
      "**Count cash & submit**: enter the notes and coins and compare with **System cash**.",
      "Click **Save draft** to pause, or **Submit handover**. New receipts for that date are then locked.",
      "**Accounts receive**: Accounts clicks **Approve & receive**, or **Reject** with a reason.",
      "**History** shows past day-closes and their cash variance.",
    ],
    stuckTips: [
      'If you see "Cash variance needs a remark before submit", explain the difference before submitting.',
      'If "No receipts for this date — nothing to close" appears, check the date you picked.',
      'If you see "Day-close already submitted or approved", that date is closed. Open it from **History**.',
      "If it was rejected, recount the cash and submit again.",
    ],
  },
  {
    id: "fees-adjustments",
    paths: ["/fees"],
    tab: "adjustments",
    pageLabel: "Fees · Adjustments",
    title: "Waive dues, add ad-hoc charges, write off or settle leavers",
    module: "fees",
    chipLabel: "How Adjustments works",
    steps: [
      "Search for the student and select them.",
      "Pick a **Type**, such as **Waive line**, **Ad-hoc charge**, **Change fee group**, **Write-off** or **Stop future installments**.",
      "Choose the **Due line** or **Fee head**, the **Amount ₹**, a **Reason code** and a **Reason note**.",
      "Click **Save adjustment**. Larger amounts go to the Principal for approval.",
      "For a leaver, choose **Inactive — leaving the school** to stop future dues and mark them inactive.",
    ],
    stuckTips: [
      'If you see "Select a student", pick the student first.',
      'If "Tick at least one due line to waive" appears, tick the dues you want to waive.',
      'If you see "Nothing open to waive for this student.", there are no unpaid dues left to waive.',
      "If it says the amount goes to the Principal, the adjustment applies only after approval.",
    ],
  },
  {
    id: "fees-vouchers",
    paths: ["/fees"],
    tab: "vouchers",
    pageLabel: "Fees · Vouchers",
    title: "Add a one-off charge voucher for a student",
    module: "fees",
    chipLabel: "How Vouchers works",
    steps: [
      "Search for the student and select them.",
      "Choose the month or installment from **Select month…**.",
      "Pick the fee **Head…**, enter the amount, and set the **Due date** and **Reason**.",
      "Click **Create voucher · show on Fee Take**.",
      "Collect the charge on **Collect**. You can void an unused voucher from the list.",
    ],
    stuckTips: [
      'If you see "Select a student", pick the student before creating the voucher.',
      'If "Select the month / installment" appears, choose a month first.',
    ],
  },

  // ───────────── Part B: Accounts ─────────────
  {
    id: "accounts-vouchers",
    paths: ["/accounts"],
    tab: "vouchers",
    pageLabel: "Accounts · Vouchers",
    title: "Record expenses and journal vouchers",
    module: "accounts",
    chipLabel: "How Vouchers works",
    steps: [
      "Pick a form: **Quick**, **Multi-line**, **Voucher entry** or **Cheques**.",
      "In **Quick**, choose the **Head**, **Sub-head** and **Spent on**, then enter the amount and date.",
      "Pick **Paid by**. For anything other than cash, choose **Which bank** and enter the **Transaction ID**.",
      "Add a **Note** if you like, and click **Save expense**.",
      "Use **Multi-line** for many bills from one trip, and **Voucher entry** for full double-entry vouchers.",
    ],
    stuckTips: [
      "If **Save expense** won't post, a non-cash payment needs its bank and transaction ID first.",
      'If you see "The book refused this entry", check the head, amount and date, then try again.',
    ],
  },
  {
    id: "accounts-book",
    paths: ["/accounts"],
    tab: "book",
    pageLabel: "Accounts · Server book",
    title: "The school's position: cash, bank, income and payables",
    module: "accounts",
    chipLabel: "How Server book works",
    steps: [
      "Check **Cash in hand**, **At bank**, **Cheques in hand**, **Receivables** and **Payables**.",
      "Review **Income this year**, **Expenditure**, and the **Surplus** or **Deficit**.",
      "**Projection & coverage** compares desk records with what is in the book.",
      "Approvers can click **Run projection** to post desk records that are missing from the book.",
      "Check **Payables ageing** for vendor bills that are overdue.",
    ],
    stuckTips: [
      'If you see "Could not read the book" or "Could not reach the server", check your connection and reload.',
      "If rows show as **Refused**, fix the source entry, then run the projection again.",
    ],
  },
  {
    id: "accounts-recon",
    paths: ["/accounts"],
    tab: "recon",
    pageLabel: "Accounts · Bank recon",
    title: "Match the bank statement with the books",
    module: "accounts",
    chipLabel: "How Bank recon works",
    steps: [
      "Under **Bank reconciliation**, pick the bank account.",
      "Paste the statement CSV under **Import statement** and click **Import lines**.",
      "Click **Auto-match** to pair statement lines with book entries.",
      "Match anything left over by hand, then open **Reconciliation report** to check it reconciles.",
      "Further down, check the online-payment settlements and the gateway fee policy.",
    ],
    stuckTips: [
      'If you see "Pick the bank account first", choose the account before importing.',
      'If "Paste the statement CSV first" appears, paste the statement text into the box.',
      "Importing the same statement twice is safe. Lines that are already known are skipped.",
      'If you see "Settled but no voucher — press Pull now, then check the reason", click **Pull now**.',
    ],
  },
  {
    id: "accounts-daysheet",
    paths: ["/accounts"],
    tab: "daysheet",
    pageLabel: "Accounts · Day sheet",
    title: "Print the daily collection and expense sheet for signature",
    module: "accounts",
    chipLabel: "How Day sheet works",
    steps: [
      "Pick the **Date**.",
      "Check **Collections** and **Expenses** by payment mode.",
      "Review the **Net movement for the day**.",
      "Click **Print for signature** for the counter, the checker and the Principal.",
    ],
    stuckTips: [
      'If you see "The browser blocked the print window — allow pop-ups for this site.", allow pop-ups and print again.',
      "If a warning says the day has more entries than one read, don't sign the sheet. Tell the office.",
      'If "Could not read the day — try again." appears, reload the tab.',
    ],
  },
  {
    id: "accounts-dayclose",
    paths: ["/accounts"],
    tab: "dayclose",
    pageLabel: "Accounts · Day close",
    title: "Approve or reject the cashier's cash handover",
    module: "accounts",
    chipLabel: "How Day close works",
    steps: [
      "Cashiers submit their day close from Fee Take. Accounts approves it here.",
      "Open **Accounts receive** and compare **Physical counted** with **System cash** and **Variance**.",
      "Enter the receiver name and click **Approve & receive**. The cash moves to the main cash pool.",
      "Or click **Reject** with a reason so the cashier recounts.",
      "**History** shows earlier day-closes and their variance.",
    ],
    stuckTips: [
      'If you see "No submitted handover waiting for approval", the cashier hasn\'t submitted yet.',
      'If "Receiver name is required" appears, enter your name before approving.',
      'If you see "Add a reason when rejecting", type why the count is wrong.',
    ],
  },
  {
    id: "accounts-closing",
    paths: ["/accounts"],
    tab: "closing",
    pageLabel: "Accounts · Closing balances",
    title: "Bring the book in line with the cash and bank you counted",
    module: "accounts",
    chipLabel: "How Closing balances works",
    steps: [
      "Enter the **Cash in hand** you counted and the **Bank** balance for the date.",
      "Click **Check the difference** to compare them with the book.",
      "Review **What will be posted**, then click **Post the closing**.",
      "If it says **The book already agrees**, there is nothing to post.",
    ],
    stuckTips: [
      "To change a closing that's already posted, reverse that voucher in **Vouchers** first.",
      'If "Could not post the closing balances — try again." appears, reload and post again.',
    ],
  },
  {
    id: "accounts-bills",
    paths: ["/accounts"],
    tab: "bills",
    pageLabel: "Accounts · Bills & AP",
    title: "Record vendor bills and pay them",
    module: "accounts",
    chipLabel: "How Bills & AP works",
    steps: [
      "Select the vendor and enter the **Bill / invoice number**, date and due date.",
      "Add item lines with **+ Add line**: qty, rate, tax and discount.",
      "Click **Create bill**.",
      "Under **Unified payables**, click **Pay** or **Mark paid** once the bill is settled.",
      "Click **Sync transport** to bring in transport payables.",
    ],
    stuckTips: [
      'If you see "Select a vendor — add vendors under Masters → Vendors", add the vendor first.',
      'If "Add at least one line item with a name" appears, give each line an item name.',
    ],
  },
  {
    id: "accounts-masters",
    paths: ["/accounts"],
    tab: "masters",
    pageLabel: "Accounts · Masters",
    title: "Set up bank accounts, expense heads, tags and vendors",
    module: "accounts",
    chipLabel: "How Accounts masters works",
    steps: [
      "**Bank & cash accounts**: add the school's bank accounts and cash drawers first.",
      "**Expense heads**: a category with sub-heads (e.g. Utilities → Electricity, Diesel).",
      "**Spend tags**: what an expense was for, such as Bus-1, Hostel or Annual Function.",
      "**Accounts, categories & vendors**: the account list, categories and vendors that bills are paid to.",
    ],
    stuckTips: [
      "If a vendor is missing in **Bills & AP**, add it under **Accounts, categories & vendors**.",
      "If an expense can't find its head, add the head under **Expense heads** first.",
    ],
  },

  // ───────────── Part B: Exams ─────────────
  {
    id: "exams-marks",
    paths: ["/exams"],
    tab: "marks",
    pageLabel: "Exams · Mark entry",
    title: "Enter, save and lock marks",
    module: "exams",
    chipLabel: "How Mark entry works",
    steps: [
      "Select the exam, class and section at the top.",
      "Enter marks or grades for each subject. Mark absent students and add a reason.",
      "Click **Save marks** regularly.",
      "When the marks are checked, click **Save & lock**. A locked sheet can't be edited.",
      "To correct a locked sheet, click **Unlock** and give a reason. The reason is recorded.",
    ],
    stuckTips: [
      'If you see "Select exam, class and section", pick all three first.',
      "If no exams appear in the list, create them under **Exams & policy**.",
      "If a message says marks cannot exceed the maximum, fix that cell. It's above the paper's max marks.",
      'If "Give a reason for unlocking (at least a few words)" appears, write a fuller reason.',
    ],
  },
  {
    id: "exams-setup",
    paths: ["/exams"],
    tab: "setup",
    pageLabel: "Exams · Exams & policy",
    title: "Set exam policy, grading schemes and session exams",
    module: "exams",
    chipLabel: "How Exams & policy works",
    steps: [
      "**School policy**: set the pass % and default max marks, then click **Save policy**.",
      "**Assessment schemes**: marks or grades, grade bands and subject splits for each class band.",
      "**Session exams**: enter a code and name, then click **Create exam**.",
      "**Report cards**: choose the report-card template for each class band.",
      "Use **Edit**, **Activate** / **Deactivate** or **Delete** on an exam in the list.",
    ],
    stuckTips: [
      'If you see "Exam code is required (max 12 chars)" or "Exam name is required", fill in both.',
      'If "Exam code … already exists" appears, use a different code for this session.',
      'If you see "End date cannot be before start date", fix the dates.',
      'If "Cannot change code — student marks already saved for this exam" appears, keep the code and edit other fields.',
    ],
  },
  {
    id: "exams-datesheet",
    paths: ["/exams"],
    tab: "datesheet",
    pageLabel: "Exams · Date-sheet",
    title: "Plan which paper is on which day for each class",
    module: "exams",
    chipLabel: "How Date-sheet works",
    steps: [
      "Click **Add exam day** and pick the date.",
      "In a class's cell, add a paper: subject, start time, duration and an optional note. Click **Save**.",
      "Click a paper to change it, or **Clear** to remove it.",
      "Use **Move every paper on** a day to shift the whole day to another date.",
    ],
    stuckTips: [
      'If you see "Pick a date for the new exam day.", choose a date before adding the day.',
      'If "This class already has an overlapping exam sitting" appears, change the start time or the date.',
      "If the date is before or after the exam or session dates, pick a date inside them.",
      'If you see "Duration must be between 1 and 480 minutes", fix the duration.',
    ],
  },
  {
    id: "exams-seating",
    paths: ["/exams"],
    tab: "seating",
    pageLabel: "Exams · Seating",
    title: "Seat students across rooms and print bench slips",
    module: "exams",
    chipLabel: "How Seating works",
    steps: [
      "Select the exam.",
      "Under **Rooms**, enter the **Room name** and **Benches**, then click **Add room**.",
      "Set **Students per bench** and check the **Seating plan**.",
      "Click **Save this plan**, or **Regenerate & save**.",
      "Export as **CSV**, **Excel** or **PDF**, or click **Print bench slips**.",
    ],
    stuckTips: [
      'If you see "Select an exam first", pick the exam at the top.',
      'If "This plan breaks the seating rule … Nothing saved." appears, add rooms or change students per bench.',
      "If a room can't be removed because children are seated in it, clear the saved plan first.",
      'If you see "Nothing to seat yet", add rooms and check that this session has students.',
    ],
  },
  {
    id: "exams-papers",
    paths: ["/exams"],
    tab: "papers",
    pageLabel: "Exams · Question papers",
    title: "Set, build and print question papers",
    module: "exams",
    chipLabel: "How Question papers works",
    steps: [
      "Click **New paper** and choose the exam, class and subject.",
      "Add sections, then fill in questions by hand, with **+ AI Qs**, or with **+ From bank**.",
      "Click **Save paper**.",
      "Click **+ Clone set** to make set B, C and so on (up to 5 sets).",
      "Click **Print** for a copy with the school header.",
    ],
    stuckTips: [
      'If you see "Select class and subject" or "Select exam", fill in the paper\'s details first.',
      'If "Add at least one set (A/B/C…)" appears, create a set before saving.',
      'If you see "Maximum 5 sets (A–E)", you can\'t add another set. Edit an existing one instead.',
      'If "Choose an image file" appears, upload a JPG or PNG for the question picture.',
    ],
  },
  {
    id: "exams-admitcards",
    paths: ["/exams"],
    tab: "admitcards",
    pageLabel: "Exams · Admit cards",
    title: "Print admit cards",
    module: "exams",
    chipLabel: "How Admit cards works",
    steps: [
      "Pick the **Exam term**, **Class** and **Section**.",
      "Tick the students, or click **Select all**.",
      "Click **Print N admit card(s)**.",
    ],
    stuckTips: [
      'If you see "Pick an exam term.", choose the exam first.',
      'If "Select at least one student." appears, tick at least one student.',
      "If a student's card is held (HOLD_ADMIT_CARD), clear their dues or get a Principal override.",
    ],
  },
  {
    id: "exams-reports",
    paths: ["/exams"],
    tab: "reports",
    pageLabel: "Exams · Report cards",
    title: "Preview and print report cards",
    module: "exams",
    chipLabel: "How Report cards works",
    steps: [
      "Select the exam, class and section at the top.",
      "Click a student in the list to preview their report card.",
      "Click **Print report card**.",
      "**Report held** next to a name means there's a fee hold on that child.",
    ],
    stuckTips: [
      "If printing is blocked, clear the dues or lift HOLD_REPORT_CARD with the Principal PIN.",
      "If the list is empty, select the class and section above.",
    ],
  },
  {
    id: "exams-results",
    paths: ["/exams"],
    tab: "results",
    pageLabel: "Exams · Results",
    title: "Check results and promote students",
    module: "exams",
    chipLabel: "How Results works",
    steps: [
      "Select the exam, class and section. Use Annual or Half-yearly for promotion decisions.",
      "Review pass / fail and attendance. **Edit** attendance if needed, or click **Use registers**.",
      "Click **Auto suggest** to fill in promotion decisions and the next class.",
      "Click **Apply promotions to SIS**.",
      "Click **Print result sheet**.",
    ],
    stuckTips: [
      "If the screen asks you to select exam, class and section, fill in all three.",
      "If edited attendance looks wrong, click **Use registers** to go back to the register figures.",
      "If promotions report errors, fix the students named and apply again.",
    ],
  },

  // ───────────── Part B: Masters ─────────────
  {
    id: "masters-classes",
    paths: ["/masters"],
    tab: "classes",
    pageLabel: "Masters · Classes & sections",
    title: "Set up the classes, sections and class teachers",
    module: "masters",
    chipLabel: "How Classes works",
    steps: [
      "Classes are grouped: Pre-Primary, Primary, Middle, Secondary and Senior.",
      "Type a new class (e.g. XIII) and click **Add class**. It's created with sections A and B.",
      "Select a class, then add a section (e.g. C).",
      "Use **Edit class** or **Rename section** to change names, and **Inactivate** to retire one.",
    ],
    stuckTips: [
      'If you see "Class already exists", that class is already set up. Edit it instead.',
      'If "Section already exists" appears, use a different letter or rename the existing section.',
    ],
  },
  {
    id: "masters-academic",
    paths: ["/masters"],
    tab: "academic",
    pageLabel: "Masters · Session",
    title: "Academic years, terms and school-closure notices",
    module: "masters",
    chipLabel: "How Session works",
    steps: [
      "Click **Add academic year** and enter a code (e.g. 2026-27).",
      "Click **Set current** to make that year the session every screen works in.",
      "Add terms with **Add term** (e.g. code T1).",
      "To tell families about a closure, use **Announce closure** or **Announce holiday**, then **Preview reach**.",
      "Click **Send to N families** to send it.",
    ],
    stuckTips: [
      'If you see "Could not send" or "Could not reach the server", check your connection and send again.',
      "If other screens show the old year, click **Set current** on the new year.",
    ],
  },
  {
    id: "masters-holidays",
    paths: ["/masters"],
    tab: "holidays",
    pageLabel: "Masters · Holidays",
    title: "Build and publish the holiday calendar",
    module: "masters",
    chipLabel: "How Holidays works",
    steps: [
      "In the UP govt calendar step, approve rows (or all gazetted and national holidays). Approved rows publish straight away.",
      "**Build policy**: draft a holiday rule with its scope, one-off or weekly, and full or half day.",
      "**Publish drafts**: click **Publish** so attendance uses the rule.",
      "**Published**: notify families, or click **Unpublish (back to drafts)**.",
    ],
    stuckTips: [
      "If attendance still counts a holiday as a working day, check the rule is Published and not a draft.",
      "If a government holiday is missing, check the UP govt calendar list for rows that are still pending.",
    ],
  },
  {
    id: "masters-fee-structure",
    paths: ["/masters"],
    tab: "fee-structure",
    pageLabel: "Masters · Fee structure",
    title: "Set fee amounts for each group and publish them to Fee Take",
    module: "masters",
    chipLabel: "How Fee structure works",
    steps: [
      "Select a fee group.",
      "Add heads to each month with **+ Add fee head** and set the **Amount ₹** (a default or a class override).",
      "Use **Copy → schedule** to place a head across the months its frequency needs.",
      "Click **Publish for Fee Take** to make the structure live at the counter.",
      "Use **Sync this group** or **Assign to matching students** so students get the group's fees.",
    ],
    stuckTips: [
      'If you see "Select a fee group", pick one from the list first.',
      "If the group shows **Not published yet**, click **Publish for Fee Take**.",
      'If it says "All students already match type + class fee groups", nobody needs syncing.',
    ],
  },
  {
    id: "masters-installments",
    paths: ["/masters"],
    tab: "installments",
    pageLabel: "Masters · Due dates",
    title: "Set when each month's fees fall due",
    module: "masters",
    chipLabel: "How Due dates works",
    steps: [
      "Pick the due pattern: Monthly Apr–Mar, Quarterly or Half-yearly.",
      "Set the **Due day each month** to apply it to every month.",
      "Change single dates under **Due dates (edit individually)**.",
      "Turn months on or off for collection, then attach heads in **Fee structure**.",
    ],
    stuckTips: [
      "If a month doesn't appear on Fee Take, check it's switched on here.",
      "If dues have no amount, attach the fee heads to that installment in **Fee structure**.",
    ],
  },
  {
    id: "masters-concessions",
    paths: ["/masters"],
    tab: "concessions",
    pageLabel: "Masters · Concessions",
    title: "Set discount policies and grant them to students",
    module: "masters",
    chipLabel: "How Concessions works",
    steps: [
      "Click **Add concession**. Pick the kind (e.g. SIBLING, STAFF, MERIT), percent or amount, and fee heads.",
      "Write the ground for the discount and click **Save concession**.",
      "Assign students to the policy, such as siblings, staff wards, RTE / EWS or transport riders.",
      "A principal, admin or owner must **Approve** each grant before it applies in Fee Take.",
    ],
    stuckTips: [
      'If you see "Concession code already exists", use a different code.',
      'If "Selected students already have this grant" appears, those students are already covered.',
      'If you see "Only a principal, admin or owner can approve or reject", ask one of them to approve.',
    ],
  },
  {
    id: "masters-roles",
    paths: ["/masters"],
    tab: "roles",
    pageLabel: "Masters · Roles & permissions",
    title: "Control what each staff member can see and do",
    module: "settings",
    chipLabel: "How Roles works",
    steps: [
      "Select a role, click **Open permission matrix**, and switch module × action cells on or off.",
      "Click **Clone role** to create a custom role from a template.",
      "Click **Assign role**: pick the staff member and role, an optional expiry, and a note (e.g. substitute XI-A).",
      "Use **Copy access from staff** to give one person another person's role assignments.",
      "Check **Permission change audit** to see who changed what.",
    ],
    stuckTips: [
      'If you see "Pick staff and role", choose both before assigning.',
      'If "Pick source and target staff" appears, choose both people before copying.',
      'If you see "Cannot deactivate Principal built-in", leave the built-in Principal role on.',
    ],
  },
  {
    id: "masters-wa-templates",
    paths: ["/masters"],
    tab: "wa-templates",
    pageLabel: "Masters · WhatsApp templates",
    title: "Create WhatsApp templates and get them approved by Meta",
    module: "wa_templates",
    chipLabel: "How WA templates works",
    steps: [
      "Check the approved templates in the list. Click **Sync from Meta** to refresh their status.",
      "Create a template, write the content (or click **Suggest content**), then click **Create & submit to Meta**.",
      "If a template is rejected, edit it and click **Re-submit to Meta** or **Update on Meta (re-review)**.",
      "Under sender numbers, click **Add a number** and choose which module sends from which number.",
    ],
    stuckTips: [
      'If it says "No approved templates yet", create a template and submit it to Meta first.',
      'If you see "Session is closed — templates are read-only", switch to the current session.',
      'If "Make another number the default before pausing this one" appears, set a new default first.',
      'If you see "Submit failed" or "Sync failed", wait a minute and try again.',
    ],
  },

  // ───────────── Part B: Attendance ─────────────
  {
    id: "attendance-month",
    paths: ["/attendance"],
    tab: "month",
    pageLabel: "Attendance · Month register",
    title: "Mark or correct a whole month in one grid",
    module: "attendance",
    chipLabel: "How Month register works",
    steps: [
      "Pick the **Class** and **Month**.",
      "Tap cells to set P, A, L, HD or LE. Tap a day's header to mark all blanks Present.",
      "Click **Save N change(s)**.",
      "Sort by roll number or by name, and export the register if you need a copy.",
    ],
    stuckTips: [
      'If you see "No class to show — you are not a class teacher of any section this session", ask the office.',
      'If "Could not load the month" appears, reload and pick the class again.',
      "If cells show **Not saved**, click **Save N change(s)** before leaving.",
    ],
  },
  {
    id: "attendance-staff",
    paths: ["/attendance"],
    tab: "staff",
    pageLabel: "Attendance · Staff",
    title: "Staff attendance, punches and corrections",
    module: "attendance",
    chipLabel: "How Staff attendance works",
    steps: [
      "Search for staff by name, emp code or RFID.",
      "Use **Direct mark** to set one person's status for the day, then click **Save direct mark**.",
      "Use **Adjust attendance** or **Adjust half-day** to change a mark that's already there.",
      "Click **Sync leave** to bring approved leave into attendance.",
      "Staff can **Punch in** from **My punch**.",
    ],
    stuckTips: [
      'If you see "Only admin can direct-mark" or "Only admin can adjust attendance", ask an admin.',
      'If "No active staff in roster" appears, add staff on the Staff screen first.',
    ],
  },
  {
    id: "attendance-exceptions",
    paths: ["/attendance"],
    tab: "exceptions",
    pageLabel: "Attendance · Exceptions",
    title: "Resolve attendance exceptions and parent disputes",
    module: "attendance",
    chipLabel: "How Exceptions works",
    steps: [
      "Filter by kind: Absent · no WA, Late on leave, Present on leave or Parent dispute.",
      "Add a resolve note and click **Resolve**.",
      "Click **Rebuild** to regenerate the list from the registers and leave.",
      "For a parent's complaint, pick the student, write what they said, and click **File dispute**.",
    ],
    stuckTips: [
      'If you see "Pick a student for the parent dispute", choose the student first.',
      "If the list looks out of date, click **Rebuild**.",
    ],
  },

  // ───────────── Part B: Admissions ─────────────
  {
    id: "admissions-enquiry",
    paths: ["/admissions"],
    tab: "enquiry",
    pageLabel: "Admissions · Walk-in enquiry",
    title: "Capture a walk-in family and their children",
    module: "admissions",
    chipLabel: "How Walk-in enquiry works",
    steps: [
      "**Household**: enter the enquiry date, **Primary mobile**, father or guardian, locality and address.",
      "If the mobile matches an existing family, the child is linked to them as a sibling.",
      "Add each child: **Child name**, **Class sought**, date of birth and previous school.",
      "Click **Save enquiry + household**.",
    ],
    stuckTips: [
      'If you see "Add at least one child name", fill in the first child.',
      'If "Class sought is required for the first child" appears, pick a class.',
      'If you see "Guardian mobile must be 10 digits", fix the number.',
      'If "Guardian name is required" appears, fill in the father or guardian name.',
    ],
  },
  {
    id: "admissions-leads",
    paths: ["/admissions"],
    tab: "leads",
    pageLabel: "Admissions · Lead details (CRM)",
    title: "Work the enquiry pipeline",
    module: "admissions",
    chipLabel: "How Leads works",
    steps: [
      "Filter by My leads, Due today, Overdue, Unassigned, status, locality or lead date.",
      "Open a lead and use **Call & write it up** or **Log a follow-up**.",
      "Use **WhatsApp the family**. Bulk sending opens 12 families per click.",
      "Click **Move to Registered** when the family is ready.",
      "Click **Check admitted in SIS** to mark leads that are already students.",
    ],
    stuckTips: [
      'If you see "Cannot follow up closed leads", reopen the lead or pick an open one.',
      'If "Still needed: …" appears, finish the listed items before registering.',
      'If "All leads must share the same 10-digit mobile to merge" appears, only merge leads from the same family.',
    ],
  },
  {
    id: "admissions-registration",
    paths: ["/admissions"],
    tab: "registration",
    pageLabel: "Admissions · Registration",
    title: "Take the registration fee and create the student record",
    module: "admissions",
    chipLabel: "How Registration works",
    steps: [
      "**Take registration**: pick the child from the **Registration queue — from Lead CRM**.",
      "Click **Take fee** and collect the **Registration fee** in any mode (partial is OK), or record a **Principal waiver**.",
      "**Send to student record** creates the student in SIS with an admission no and SRN.",
      "Use **New registration — family / siblings** to register several children from one family.",
      "Use **WhatsApp the family** to message the parents.",
    ],
    stuckTips: [
      'If you see "Take registration fee first (or waive), then Send to student record", collect or waive the fee.',
      'If "Set registration fee amount first" appears, enter the fee amount.',
      'If you see "Assign a section before enrollment", pick a section.',
      'If "This student has no 10-digit parent mobile — add it in Students first" appears, add the mobile.',
    ],
  },
  {
    id: "admissions-import",
    paths: ["/admissions"],
    tab: "import",
    pageLabel: "Admissions · Upload leads",
    title: "Upload older leads from CSV or Excel",
    module: "admissions",
    chipLabel: "How Upload leads works",
    steps: [
      "Paste CSV rows, or choose an Excel or CSV file (child, guardian, mobile and so on).",
      "Set the default source, status and session tags.",
      "Click **Upload leads**. Click **Load sample CSV** to see the format.",
      "Or click **Load Field + Survey Excel seed** to load the survey file stored on the server.",
    ],
    stuckTips: [
      'If you see "No usable lead rows found.", check the file has child, guardian and mobile columns.',
      'If "Could not read Excel workbook" appears, save the file as CSV and try again.',
      'If you see "Your role cannot import leads.", ask an admin for Admissions create access.',
    ],
  },
  {
    id: "admissions-campaigns",
    paths: ["/admissions"],
    tab: "campaigns",
    pageLabel: "Admissions · WA campaigns",
    title: "Send WhatsApp campaigns to lead lists",
    module: "admissions",
    chipLabel: "How WA campaigns works",
    steps: [
      "**Audience lists**: filter the CRM leads, name the list, and click **Build list**.",
      "**Campaigns**: click **New campaign**, choose a list and a template, and set the schedule.",
      "Click **Enqueue** on the campaign to build its send queue.",
      "**Queue & dispatch**: click **Dispatch due (live)** and check each message's status.",
    ],
    stuckTips: [
      'If you see "Name the list", type a list name before building it.',
      'If "Select a campaign on the Campaigns tab" appears, pick a campaign first.',
      'If you see "Could not reach WhatsApp dispatch API", check the WhatsApp setup and try again.',
    ],
  },

  // ───────────── Part B: Comms (other tabs) ─────────────
  {
    id: "comms-whatsapp",
    paths: ["/comms"],
    tab: "whatsapp",
    pageLabel: "Comms · WhatsApp",
    title: "Send approved WhatsApp templates to parents and staff",
    module: "notices",
    chipLabel: "How WhatsApp works",
    steps: [
      "Sections: **Send message**, **Chats**, **Class groups**, **Delivered**, **Numbers to fix**, **Usage & cost**, and more.",
      "In **Send message**, pick who it goes to: Parents, Staff, Fee defaulters or Pick students.",
      "Choose an approved template.",
      "Click **Check audience**, then **Send to N**.",
      "Fix missing or wrong numbers in **Numbers to fix**.",
    ],
    stuckTips: [
      'If you see "Could not work out the audience", change the filters and click **Check audience** again.',
      'If "The send failed" appears, check the template is approved in Masters → WhatsApp templates.',
      "Opted-out numbers and numbers not on WhatsApp are left out automatically.",
    ],
  },
  {
    id: "comms-social",
    paths: ["/comms"],
    tab: "social",
    pageLabel: "Comms · Social",
    title: "Cross-post news, albums and notices to social media",
    module: "notices",
    chipLabel: "How Social works",
    steps: [
      "**Connect accounts**: click **Connect with Facebook**, or enter tokens. Add Telegram using a token from @BotFather.",
      "Click **Send test post** to check the connection.",
      "**Cross-post rules**: choose what posts automatically when you publish.",
      "**Queue & log**: see scheduled posts and recent cross-posts. Click **Refresh** to update.",
    ],
    stuckTips: [
      'If you see "Could not connect Page", reconnect and pick the right Facebook Page.',
      'If "Test post failed" appears, check the saved credentials and try again.',
      'If it says "No cross-posts yet", publish news or an album with social posting switched on.',
    ],
  },
  {
    id: "comms-email",
    paths: ["/comms"],
    tab: "email",
    pageLabel: "Comms · Email",
    title: "Send school email through Google Workspace",
    module: "notices",
    chipLabel: "How Email works",
    steps: [
      "Follow the one-time setup on screen: GCP project, Gmail API and domain-wide delegation.",
      "Enter the **Display name** and click **Save**.",
      "Click **Send test** to check that email sends.",
    ],
    stuckTips: [
      'If you see "Test failed from …", ask the Workspace admin to finish the delegation step.',
      'If "Could not load email settings" appears, reload the page.',
    ],
  },
  {
    id: "comms-answers",
    paths: ["/comms"],
    tab: "answers",
    pageLabel: "Comms · Answer book",
    title: "Approved answers the parent WhatsApp bot can give",
    module: "notices",
    chipLabel: "How Answer book works",
    steps: [
      "Under **Write an answer**, type the question the way a parent would ask it, then the school's answer.",
      "Click **Save as proposed**. It answers nobody until it's approved.",
      "An approver clicks **Approve**, and parents start getting this answer.",
      "Click **Retire** to stop using an answer.",
    ],
    stuckTips: [
      'If it says "Saved — it answers nobody until it is approved", ask an approver to click **Approve**.',
      'If you see "That did not work", click **Refresh** and try again.',
    ],
  },

  // ───────────── Part B: Transport ─────────────
  {
    id: "transport-riders",
    paths: ["/transport"],
    tab: "riders",
    pageLabel: "Transport · Riders",
    title: "Put students on a bus route, or take them off",
    module: "transport",
    chipLabel: "How Riders works",
    steps: [
      "Search for the student by name, admission no or mobile.",
      "Pick the **Route**, **Stop**, service (Both ways or one way) and **Effective from** date.",
      "Check the **Dues preview**. If the fee is different, enter an **Override reason**.",
      "Click **Assign to route**. You can add siblings to the same assignment.",
      "Use **Change** or **End** on an existing assignment.",
    ],
    stuckTips: [
      'If you see "Select a stop on this route", choose a stop.',
      'If "Effective from date is required" appears, set the start date.',
      'If you see "Fee override differs from expected — enter a reason", fill in the override reason.',
      'If it says "No driver / attendant mapped", set them in Staff → Duties.',
    ],
  },
  {
    id: "transport-requests",
    paths: ["/transport"],
    tab: "requests",
    pageLabel: "Transport · Requests",
    title: "Handle transport requests from parents",
    module: "transport",
    chipLabel: "How Requests works",
    steps: [
      "Requests parents send from the app appear here straight away.",
      "Filter by **New & contacted**, **Assigned** or **Declined**.",
      "Click **WhatsApp** to message the family.",
      "Add a note and mark the request **Contacted**, **Assigned** or **Decline**.",
      "Assign the actual route on **Riders** or **Planner**.",
    ],
    stuckTips: [
      'If you see "Could not load requests", reload the tab.',
      'If "Could not update" appears, try the button again in a moment.',
    ],
  },
  {
    id: "transport-routes",
    paths: ["/transport"],
    tab: "routes",
    pageLabel: "Transport · Routes",
    title: "Set up routes, stops and the transport fee policy",
    module: "transport",
    chipLabel: "How Routes works",
    steps: [
      "**Routes, stops & runs**: click **Add route** and add stops in boarding order with road distance.",
      "Set the bus and runs, then click **Save route**.",
      "**Fee policy for the year**: choose a flat route fee, per km, or distance slabs.",
      "Use **Take off the road** to stop using a route.",
    ],
    stuckTips: [
      'If you see "Add at least one distance slab", add a slab for the slab fee policy.',
      'If "Code and name required" appears, fill in both fields for the route.',
    ],
  },
  {
    id: "transport-fleet",
    paths: ["/transport"],
    tab: "fleet",
    pageLabel: "Transport · Fleet",
    title: "Add and manage vehicles",
    module: "transport",
    chipLabel: "How Fleet works",
    steps: [
      "Click **Add vehicle**. Enter the Registration, Name, Fuel, Odometer and Seat capacity.",
      "Pick the driver from staff, or choose an outside driver.",
      "Click **Save vehicle**.",
    ],
    stuckTips: [
      'If you see "Registration number required", fill in the registration.',
      "If a driver has no mobile on their staff record, they can't sign in. Add the mobile in Staff.",
    ],
  },
  {
    id: "transport-fuel",
    paths: ["/transport"],
    tab: "fuel",
    pageLabel: "Transport · Fuel",
    title: "Log refills and depot fuel purchases",
    module: "transport",
    chipLabel: "How Fuel works",
    steps: [
      "**Log refill**: pick the vehicle, then enter the odometer km, quantity and amount.",
      "Choose depot stock (Mode A) or pump (Mode B), then click **Save refill**.",
      "**Depot purchase (Mode A)**: enter the quantity and rate, then click **Post purchase**.",
    ],
    stuckTips: [
      'If you see "Vehicle is in workshop — refill blocked", finish the service job first.',
      'If "Quantity required" or "Select depot location" appears, fill in those fields.',
      "If it says **Refill logged (mileage anomaly)**, check the odometer reading.",
    ],
  },
  {
    id: "transport-service",
    paths: ["/transport"],
    tab: "service",
    pageLabel: "Transport · Service",
    title: "Repair requests and workshop jobs",
    module: "transport",
    chipLabel: "How Service works",
    steps: [
      "**Repair request**: pick the vehicle, describe the symptom and estimate, then click **Submit request**.",
      "**Open service / repair job**: click **Open job**. The vehicle shows as in the workshop.",
      "Under **Open jobs & requests**, click **Approve** on requests or **Complete** on finished jobs.",
    ],
    stuckTips: [
      'If you see "Describe the fault", fill in the symptom.',
      'If it says "Request needs Principal approval (over threshold)", wait for the Principal to approve.',
    ],
  },
  {
    id: "transport-board",
    paths: ["/transport"],
    tab: "board",
    pageLabel: "Transport · Boarding",
    title: "Mark who boarded the bus",
    module: "transport",
    chipLabel: "How Boarding works",
    steps: [
      "Pick the route, date and trip.",
      "Under **Authorized riders**, mark each child **Board**, **Offboard** or **Absent**.",
      "Use **Report unauthorized** for a child who isn't on this route.",
    ],
    stuckTips: [
      'If you see "Pick a route to mark boarding.", choose a route first.',
      'If "Location permission denied" appears, allow location access in the browser and try again.',
    ],
  },
];
