/**
 * Step-by-step guides for the student-life and office screens: vault,
 * document maker, RTE, complaints, discipline, health, ID cards, library,
 * visitors and the screens still on the roadmap. Joined into the guide list
 * by lib/erpAiPageGuides.ts.
 */

import type { ErpAiPageGuideDef } from "@/lib/erpAiPageGuideTypes";

const RTE_STEPS = [
  "On **Seats**, pick a **Class**, **Type** and **Total seats**, then **Save seat**. **Seed all classes** fills them at once.",
  "Open **Govt list** and **Upload .xls / .xlsx / .csv** of the AllottedSeat list, or paste it and click **Import paste**.",
  "To add one child by hand, fill Govt app no. and Child name, then click **Add to list**.",
  "On a row, open the actions menu and choose **Take admission**. Pick **Collect fee**, **Waive** or **No fee**.",
  "Click **Confirm admission**, then use **Send to SIS** from the row actions to create the student record.",
  "For an existing student, go to **Enrolled**, pick Class, Section and Student, then click **Assign RTE**.",
  "Use **Reports** to pick a **Format** and **Export**. Use **Settings** then **Save settings** for waiver rules.",
];
const RTE_TIPS = [
  "If you see 'Govt RTE application number is required before SIS', enter the govt app no. on the application first.",
  "If you see 'Collect or mark registration fee paid before sending to SIS', use Collect fee, Waive or No fee first.",
  "If you see 'Assign a section (Masters) before SIS send', set up sections for that class in Masters.",
  "If the screen says 'RTE / EWS is disabled', click **Open Modules** and switch the module back on.",
];

/** A roadmap placeholder: nothing to do on the screen yet. */
function comingSoon(
  id: string,
  path: string,
  pageLabel: string,
  title: string,
  module: ErpAiPageGuideDef["module"],
  what: string,
): ErpAiPageGuideDef {
  return {
    id,
    paths: [path],
    pageLabel,
    title,
    module,
    chipLabel: `How ${pageLabel} works`,
    steps: [
      `Open ${pageLabel}. The page shows **On the roadmap** because this module is not built yet.`,
      `There are no ${what} buttons here yet, so there is nothing to enter.`,
      "The module is listed in **Settings → Modules** so you know it is coming.",
      "It will appear in the main menu once it is released.",
    ],
    stuckTips: [
      `If you expected to use ${pageLabel} here, this is not possible yet. The screen is only a placeholder.`,
      `If you cannot find ${pageLabel} in the main menu, that is expected. It only shows under Settings → Modules for now.`,
    ],
  };
}

export const PAGE_GUIDES_B: ErpAiPageGuideDef[] = [
  {
    id: "vault",
    paths: ["/vault"],
    pageLabel: "Document vault",
    title: "Store statutory certificates and get alerts before they expire",
    module: "vault",
    chipLabel: "How the document vault works",
    steps: [
      "Open the **Add** tab, pick the certificate **Type** and enter a **Title**.",
      "Fill **Issued on**, **Expires on** and **Remind (days)**, plus the **Owner role** (principal, admin…).",
      "Paste a **File URL** or use **Or upload image / PDF** to attach the scan, then click **Save**.",
      "Find any record on the **Documents** tab using **Search**, **Type** and **Status** (Expired, Due soon, OK).",
      "Click **Edit** on a row to change it, then **Update**. Use **Cancel edit** to drop your changes.",
      "On **Alerts**, enter recipient mobiles, click **Save recipients**, then **Send digest** or **Copy message**.",
      "Use the **Reports** tab: choose Excel or PDF under **Format**, then click **Export** on the report you need.",
    ],
    stuckTips: [
      "If you see 'Title required', type a title on the Add tab before you click Save.",
      "If you see 'File too large (max 1.5 MB)' or 'Choose an image or PDF', upload a smaller JPG/PNG/PDF or paste a File URL.",
      "If you see 'Add at least one 10-digit mobile', enter 10-digit numbers separated by commas in Recipient mobiles.",
      "If **Send digest** is greyed out or says 'No expiry alerts to send', no documents are expired or due soon.",
    ],
  },
  {
    id: "document-maker",
    paths: ["/documents"],
    pageLabel: "Document maker",
    title: "Draft letters, notices and meeting minutes with AI on school letterhead",
    module: "documents",
    chipLabel: "How the document maker works",
    steps: [
      "Choose **Letter / notice** or **Meeting minutes** at the top of the Compose box.",
      "Pick the **Language**: English, Hindi or English + Hindi.",
      "For a letter, choose the **Document type** and type names, dates and reference numbers in **Details for AI**.",
      "Click **AI generate**, then check the result in the **Preview** panel on the right.",
      "For minutes, paste rough notes in **Notes / transcript**, click **Draft minutes**, then edit the agenda and action items.",
      "When the preview looks right, click **Print PDF** to download it with letterhead and signatures.",
    ],
    stuckTips: [
      "If **AI generate** is greyed out with 'Ask your principal for Document maker → Create permission', ask for Create access.",
      "If you see 'Network error — try again' or 'Generation failed', check your connection and click **AI generate** again.",
      "If **Print PDF** does not appear, generate a document first; you also need Export permission for Document maker.",
      "If minutes show 'Minutes failed', shorten or tidy the notes and click **Draft minutes** again.",
    ],
  },
  {
    id: "rte-ews",
    paths: ["/admissions"],
    tab: "rte",
    pageLabel: "RTE / EWS",
    title: "Manage RTE / EWS seats, the govt allotted list and admissions",
    module: "rte",
    chipLabel: "How RTE / EWS admissions work",
    steps: RTE_STEPS,
    stuckTips: RTE_TIPS,
  },
  {
    id: "rte-ews-page",
    paths: ["/rte"],
    pageLabel: "RTE / EWS",
    title: "Manage RTE / EWS seats, the govt allotted list and admissions",
    module: "rte",
    chipLabel: "How RTE / EWS admissions work",
    steps: RTE_STEPS,
    stuckTips: RTE_TIPS,
  },
  comingSoon("alumni", "/alumni", "Alumni", "Alumni directory and engagement (coming soon)", "alumni", "alumni"),
  comingSoon("canteen", "/canteen", "Canteen / POS", "Cashless canteen point of sale (coming soon)", "canteen", "sale, menu or wallet"),
  {
    id: "complaints",
    paths: ["/complaints"],
    pageLabel: "Complaints",
    title: "Triage, assign and resolve parent complaints",
    module: "complaints",
    chipLabel: "How complaints work",
    steps: [
      "Open **All tickets** and narrow the list with the **Category** and **Status** filters.",
      "On a ticket, pick a staff member in the **Unassigned** dropdown to assign it.",
      "Change the status dropdown as work moves along.",
      "Type what was done in **Resolution note…**, then click **Mark resolved**.",
      "Check **My tickets** for complaints assigned to you.",
      "On **AI reports**, read AI tutor replies that parents flagged, then click **Mark reviewed** or **Dismiss**.",
      "Teachers see an **Open** / **Resolved** list for their classes. Use **Take it up**, **Mark in progress** and **Mark resolved**.",
    ],
    stuckTips: [
      "If you see 'Add a resolution note before marking resolved.', type a note in the box first, then click Mark resolved.",
      "If My tickets says 'No tickets assigned to you.', ask the office to assign tickets to your staff record.",
      "If the dropdowns and buttons are greyed out, your role is read-only for Complaints. Ask the principal for edit access.",
      "If complaints sent on WhatsApp are missing, reload the page. They are fetched again each time the page loads.",
    ],
  },
  {
    id: "discipline",
    paths: ["/discipline"],
    pageLabel: "Discipline",
    title: "Log incidents, track merit/demerit points and notify parents",
    module: "discipline",
    chipLabel: "How discipline works",
    steps: [
      "On **Log incident**, search the student by name or admission no and click their name (use **Change** to swap).",
      "Set **Date** and **Category** and enter **Points**. Negative is a demerit, positive is a merit.",
      "Write or dictate the **Description**, then click **Log incident**.",
      "Open **All incidents** and filter by **Category**, **Status**, **From** and **To**. Set the escalation level in the table.",
      "Use the row menu to **Notify parent** on WhatsApp, or **Delete** a wrong entry.",
      "Open **By student** to see total points this AY, the suggested escalation and full history.",
    ],
    stuckTips: [
      "If you see 'Pick a student.', choose a student from the search results before logging.",
      "If you see 'Points must be between -20 and 20.', enter a smaller number.",
      "If you see 'Escalating past Warning needs the Approve permission.', ask the principal to raise the level.",
      "If you see 'No WhatsApp number on file', add the parent's mobile in the student record, then notify again.",
    ],
  },
  {
    id: "health",
    paths: ["/health"],
    pageLabel: "Health",
    title: "Record sick-room visits, medications and vaccinations",
    module: "health",
    chipLabel: "How the health desk works",
    steps: [
      "On **Log visit**, search and pick the student, then set **Date** and **Time**.",
      "Fill **Reason**, **Symptoms** and **Action taken**. Tick **Referred to hospital** if needed, then click **Log visit**.",
      "Check past visits on **Visit log**. Use the row menu to **Notify parent** or **Delete**.",
      "On **Medications**, pick the student and enter **Medicine name**, **Dosage**, **Schedule** and dates. Click **Add medication**.",
      "On **Vaccinations**, enter **Vaccine name**, **Dose #** and **Date given**, then click **Record vaccination**.",
      "Open **By student** to see the blood group, emergency contact and all health records together.",
    ],
    stuckTips: [
      "If you see 'Pick a student.', click a name from the search results before saving.",
      "If you see 'Medicine name is required.' or 'Vaccine name is required.', fill that field first.",
      "If you see 'No WhatsApp number on file', add the parent's mobile in the student record before notifying.",
      "If you see 'Not saved — your role cannot change health records here…', ask the principal, or check the year is open.",
    ],
  },
  comingSoon("hostel", "/hostel", "Hostel", "Boarding, room allocation and mess (coming soon)", "hostel", "room or mess"),
  {
    id: "id-cards",
    paths: ["/id-cards"],
    pageLabel: "ID cards",
    title: "Design and print student and staff ID cards",
    module: "id_cards",
    chipLabel: "How ID cards work",
    steps: [
      "Open **Card design**, choose **Student cards** or **Staff cards**, and pick **Landscape** or **Portrait**.",
      "Choose **Front only** or **Front & back**, set what shows on each side, then click **Save card design**.",
      "On **Student ID cards**, filter by class and section, then tick students or click **Select all**.",
      "Click **Print N card(s)** to generate the printable cards.",
      "On **Staff ID cards**, filter by department or designation, select staff and click **Print N card(s)**.",
      "Use **Clear** to untick everyone and start a new batch.",
    ],
    stuckTips: [
      "If you see 'Select at least one student.' or 'Select at least one staff member.', tick at least one name first.",
      "If the list says 'No active students match this filter.', change the class or section filter, or pick All classes.",
      "If a big batch is slow, print smaller groups. Batches with parent photos on front and back take longer.",
    ],
  },
  {
    id: "library",
    paths: ["/library"],
    pageLabel: "Library",
    title: "Catalogue books, issue and return copies, and track loans",
    module: "store",
    chipLabel: "How the library works",
    steps: [
      "On **Catalogue**, click **+ Add item**, fill **Title**, Author, ISBN and **Quantity (copies)**, then **Save**.",
      "Enter an ISBN and click **Fetch details** to fill the title, author and publisher for you.",
      "On **Issue / Return**, choose Student or Staff, find the borrower, then **Scan accession** or **Pick title**.",
      "Set **Issue date** and **Due date (optional)** and the condition, then click **Issue**.",
      "To take a book back, click **Return** under Open loans, record the condition, then **Confirm return**.",
      "Use **History** to filter loans and **Remind on WA** for overdue books. Export lists from **Reports**.",
      "Upload supplier bills on **Procurement** with **Save document**. Add online books on **E-books**.",
    ],
    stuckTips: [
      "If you see 'Title is required', fill the Title field before clicking Save.",
      "If you see 'Student already has N books issued', return one of their open loans before issuing another.",
      "If you see 'Copy not available', that copy is already issued or damaged. Pick another accession number.",
      "If you see 'Cannot delete — copies are currently issued', return all copies of that title first.",
    ],
  },
  comingSoon("scholarships", "/scholarships", "Scholarships", "Scholarship awards and disbursement tracking (coming soon)", "scholarships", "award or payout"),
  comingSoon("sports", "/sports", "Sports", "House points, teams and co-curricular records (coming soon)", "sports", "house, team or points"),
  {
    id: "visitors",
    paths: ["/visitors"],
    pageLabel: "Visitors",
    title: "Check visitors in and out, and manage early-pickup gate passes",
    module: "visitors",
    chipLabel: "How the visitor desk works",
    steps: [
      "On **Visitor register**, fill **Visitor name**, **Mobile**, **Purpose** and **Person to meet**, then click **Check in**.",
      "When the visitor leaves, open the row menu and choose **Check out**. Use **Print pass** for a paper pass.",
      "Open **Gate QR**, then **Show QR to visitor** or **Print gate poster** so visitors can check in themselves.",
      "On **Gate passes**, pick the student, set the date, pickup time and **Reason**, then click **Log gate pass**.",
      "From the gate-pass row menu, use **Notify parent**, **Approve**, then **Mark picked up**.",
      "See who is on gate duty in **Gate duty today**. Click **हिन्दी** to switch the screen to Hindi.",
    ],
    stuckTips: [
      "If you see 'Visitor name is required.', type the visitor's name before clicking Check in.",
      "If you see 'Pick a student.' or 'Reason is required.' on a gate pass, choose a student and fill the Reason.",
      "If you see 'No WhatsApp number on file', add the parent's mobile in the student record, then notify again.",
      "If Gate duty today says 'Nobody is assigned to gate duty today', set it up from Staff → Duty roster.",
    ],
  },
];
