/**
 * Step-by-step guides for the teaching screens: online classes, teaching &
 * syllabus, my class, student leave, PTM, events, certificates, reports and
 * the academic screens still on the roadmap. Joined into the guide list by
 * lib/erpAiPageGuides.ts.
 */

import type { ErpAiPageGuideDef } from "@/lib/erpAiPageGuideTypes";

export const PAGE_GUIDES_C: ErpAiPageGuideDef[] = [
  {
    id: "online-classes",
    paths: ["/online-classes"],
    pageLabel: "Online classes",
    title: "Schedule a live class for a section, tell parents, and see who joined",
    module: "online_classes",
    chipLabel: "How online classes work",
    steps: [
      "To use Google Meet, click **Connect Google to create Meet rooms** at the top right. Do this once.",
      "Click **Schedule a class**. Pick the **Class & section**, **Subject**, **Teacher (host)** and **Date**.",
      "Choose a **Bell period (fills the time)**, or pick **Custom time** and set **Starts** and **Ends**.",
      "Under **Where**, choose **Google Meet**, or choose **Paste a link** and paste a Meet/Zoom/Teams link.",
      "Tick **Announce to the section's parents now** if parents should get a notice, then click **Schedule**.",
      "Use the **Today**, **This week**, **Upcoming** and **Past** tabs. From a row's menu, use **Start class** or **Open the room**.",
      "After class, open **Who joined** → **Mark register from this class** → **Save register**. Then use **Class summary & homework**.",
    ],
    stuckTips: [
      "If you see \"Paste the meeting link.\", choose **Paste a link** and paste the full https:// meeting link.",
      "If it says the link is not one the school can send to parents, use a Google Meet, Zoom, Teams, YouTube or Jitsi link.",
      "If you see \"The class must end after it starts.\", fix **Starts**/**Ends**, or pick a **Bell period** instead.",
      "If Meet is greyed out, click **Connect Google** (top right). For another teacher's class, paste the link they made.",
    ],
  },
  {
    id: "teaching",
    paths: ["/teaching"],
    pageLabel: "Teaching & syllabus",
    title: "Log what was taught each period, track the syllabus and write lesson plans",
    module: "teaching",
    chipLabel: "How teaching & syllabus works",
    steps: [
      "On the **Period log** tab, pick the **Date**. Office staff can also choose a **Teacher**.",
      "For each period, click **Taught**. Or open **Period actions** and choose **Mark not taught**.",
      "On **Syllabus**, pick the **Class** and **Subject**. Click **Fill from the book** to load chapters.",
      "Use **Chapter actions** to choose **Mark complete**, **Mark part done** or **Mark not started**.",
      "On **Lesson plans**, click **New lesson plan**. Optionally click **Draft with AI**, then edit and **Save lesson plan**.",
      "Open **Coverage**, set **From** and **To**, and compare periods scheduled, taught and logged for each teacher.",
    ],
    stuckTips: [
      "If you see \"No published timetable for this year\", ask the office to publish the timetable first.",
      "If it says \"No classes are linked to you yet\", ask the office to add them in Staff → Duties.",
      "If you see \"Pick a class and subject first\", choose both above the list before **Fill from the book**.",
      "If it says this login is not linked to a staff record, ask the office to link it in Staff → Login.",
    ],
  },
  {
    id: "question-bank",
    paths: ["/question-bank"],
    pageLabel: "Question bank",
    title: "Reusable exam question bank (not built yet)",
    module: "question_bank",
    chipLabel: "How the question bank works",
    steps: [
      "This page only says **On the roadmap**. You can't add questions here yet.",
      "For now, set exam papers in **Exams** on the **Question papers** tab.",
      "Keep good questions in your saved papers so you can use them again later.",
      "Check back after an update. The office will make this module visible once it's ready.",
    ],
    stuckTips: [
      "If you only see \"On the roadmap\", that's expected. This module isn't built yet.",
      "If you can't open Exams → Question papers, ask the office for Exams access.",
    ],
  },
  {
    id: "my-class",
    paths: ["/my-class"],
    pageLabel: "My class",
    title: "Fix your class's WhatsApp numbers, details and photos",
    module: "students",
    chipLabel: "How My class works",
    steps: [
      "If you teach more than one class, choose it in **Pick a class…**.",
      "Use the filters: **WhatsApp to fix**, **All children** or **Class sheet (UDISE+)**.",
      "Open a child. Type the 10-digit number, click **Check on WhatsApp**, then **Save number**.",
      "Under **Photo**, click **Take photo**, or **Retake / change photo** to replace it.",
      "Fix fields under **Child** and click **Save child's details**.",
      "Fix parent and address fields under **Family** and click **Save family details**.",
    ],
    stuckTips: [
      "If you see \"This number is NOT on WhatsApp\", ask the family for their WhatsApp number.",
      "If you see \"This child has no family record — ask the office\", the office must link a family first.",
      "If you see \"Nothing changed\", no field was edited, so nothing was saved.",
      "If saving fails because someone else changed the record, the list reloads. Make your change again.",
    ],
  },
  {
    id: "student-leave",
    paths: ["/student-leave", "/attendance"],
    tab: "leave",
    pageLabel: "Student leave",
    title: "Approve or reject parents' leave requests, and apply leave for a student",
    module: "student_leave",
    chipLabel: "How student leave works",
    steps: [
      "Open **Attendance** → **Student leave**. The old /student-leave link brings you here too.",
      "Open the **Pending** tab to see new requests from parents.",
      "Read the dates and reason, then click **Approve** or **Reject**. Teachers can add a note to the parent.",
      "To apply for a parent, open **Apply (staff)**. Pick the **Student**, **Leave type**, **From**/**To** and **Reason**.",
      "Click **Submit request**. To change a pending request, click **Edit**, then **Save changes**.",
      "On **Reports**, set **From**, **To** and **Format** (Excel/PDF), then click **Export**.",
    ],
    stuckTips: [
      "If you see \"Select student\" or \"Reason required\", fill those fields before submitting.",
      "If you see \"To date must be on or after from date\", fix the **From**/**To** dates.",
      "If you see \"Half-day leave is for a single date\", make From and To the same day.",
      "If you see \"Only pending requests can be edited\" or \"Already decided\", that request is already approved or rejected.",
    ],
  },
  {
    id: "ptm",
    paths: ["/ptm"],
    pageLabel: "PTM scheduler",
    title: "Run parent–teacher meetings from event to slots, bookings and feedback",
    module: "ptm",
    chipLabel: "How PTM works",
    steps: [
      "On **Events**, fill in **Name**, **Date**, **Mode** and **Classes**, then click **Create event**.",
      "Pick it under **Active event**. On **Slots**, choose the **Teacher**, type **Start times** and **Room / link**, then **Add slots**.",
      "On **Bookings**, see who booked. Use **Confirm WA**, **Remind** or **Remind all booked** to message parents.",
      "After each meeting, click **Complete** or **No-show** on the booking.",
      "On **Feedback**, pick the **Booking**, fill **Strengths**, **Areas to improve** and **Follow-up**, then **Save feedback**.",
      "On **Reports**, choose the **Export format** and click **Export**.",
    ],
    stuckTips: [
      "If you see \"Select a PTM event first\", pick one under **Active event** before adding slots.",
      "If you see \"Write at least one of strengths, areas or follow-up\", fill one field before saving.",
      "If you see \"No WhatsApp mobile on household\", add the parent's mobile in the student's family record.",
      "If teachers see \"PTM events are set by the office\", the office creates the event. Teachers add their own slots.",
    ],
  },
  {
    id: "ptm-slots",
    paths: ["/ptm"],
    tab: "slots",
    pageLabel: "PTM slots",
    title: "Add the meeting times each teacher offers parents",
    module: "ptm",
    chipLabel: "How PTM slots work",
    steps: [
      "First choose the PTM under **Active event** at the top.",
      "In **Add slots**, pick the **Teacher**. Teachers add only their own slots.",
      "In **Start times**, type the times separated by commas, e.g. 09:00, 09:15, 09:30.",
      "Enter the **Room / link** and click **Add slots**.",
      "To remove a slot, delete it from the list and confirm \"Delete this slot?\".",
    ],
    stuckTips: [
      "If you see \"Create an event first.\", go to the **Events** tab and create the PTM.",
      "If it says your login is not linked to a staff record, ask the office to link it.",
      "If you see \"No PTM event includes your classes yet\", ask the office to add your classes to the event.",
    ],
  },
  {
    id: "events",
    paths: ["/events"],
    pageLabel: "Events & calendar",
    title: "Add school events, show them on the calendar and collect WhatsApp RSVPs",
    module: "events",
    chipLabel: "How events work",
    steps: [
      "Open the **Events** tab. Fill in **Title**, **Start date**, **Kind**, **Start time** and **Location**.",
      "Choose the **Classes** (leave blank for all). Optionally **Link photo album** and add a **Description**.",
      "Tick **Collect WhatsApp RSVP for this event** if you want replies, then click **Create event**.",
      "On the event card, click **Send RSVP** to ask families on WhatsApp.",
      "On **RSVPs**, pick the **Event** to see each family's reply or **Pending**.",
      "Use **Calendar** for **This week** and **This month**, and **Dashboard** for a summary.",
    ],
    stuckTips: [
      "If you see \"Title and start date are required\", fill both before **Create event**.",
      "If you see \"Could not send RSVP prompts\", make sure RSVP is on for the event and try again.",
      "If you see \"Could not save event\", check your connection and click **Save changes** again.",
    ],
  },
  {
    id: "events-interschool",
    paths: ["/events"],
    tab: "interschool",
    pageLabel: "Inter-school events",
    title: "Run an inter-school competition: registrations, results and certificates",
    module: "events",
    chipLabel: "How inter-school events work",
    steps: [
      "Click **+ New event**. On **Setup**, fill in **Event name**, **Venue**, **Event date** and **Registration closes**.",
      "Add categories with **+ Category**, set **Entry fee** and **Status**, then click **Create event**.",
      "Set **Status** to **Open — registration live** to publish the page. Share it with **Share on WhatsApp**.",
      "On **Participants**, pick a class and category, choose your students, then click **Add to event**.",
      "On **Results**, enter scores, click **Save**, then **Lock & publish results**.",
      "On **Certificates**, click **Issue / refresh certificates**. Use **Publicity** for captions and **Post to channels**.",
    ],
    stuckTips: [
      "If you see \"Set status to Open to publish the page\", change **Status** to Open and save.",
      "If **Add to event** is greyed out, tick at least one student and pick a category.",
      "Locking results makes the scoreboard public. To reopen, you must give a reason, and it shows publicly.",
    ],
  },
  {
    id: "certificates",
    paths: ["/certificates"],
    pageLabel: "Certificates",
    title: "Issue TC, bonafide, character, no-dues and fee certificates, and keep the register",
    module: "certificates",
    chipLabel: "How certificates work",
    steps: [
      "On **Issue & register**, step **Student**: use **Find student** (name, admission no. or mobile). Check PEN and APAAR ID.",
      "Step **Certificate type**: pick the type, e.g. Transfer certificate (TC) or Bonafide. Set **Issue date** and **Conduct**.",
      "Step **Details**: fill what this type needs, e.g. TC fields or **Period from**/**Period to** for fees paid.",
      "Optional, step **Draft (AI)**: click **Generate certificate (AI)** and edit the text.",
      "Step **Preview & issue**: check open dues and holds, add remarks, then click **Issue & print**.",
      "Use **Recent issues** to **Print** again or **Void** a certificate. Exports are on **Reports**.",
    ],
    stuckTips: [
      "If you see \"Pick a student first — step 1 · Student\", find and select the student before issuing.",
      "If a TC needs a leaving date, reason or first-admission date, fill it in step 3 · **Details**.",
      "If it shows \"Open dues … settle … or collect before TC\", collect the fees first. Or a Principal can use **Unlock with Principal PIN**.",
      "If you see \"No paid amount in the selected period\", widen **Period from**/**Period to** for the fees-paid certificate.",
    ],
  },
  {
    id: "reports",
    paths: ["/reports"],
    pageLabel: "Reports Center",
    title: "Find any module report and export it to Excel or PDF in one place",
    module: "home",
    chipLabel: "How the Reports Center works",
    steps: [
      "Open the **Catalog** tab. Type in **Search reports**, or filter with **All modules**.",
      "On the report you need, click **Run here**, or **Open module** to go to its screen.",
      "Or open a module tab (e.g. Fees, Students). Set the dates and **Format** (Excel/PDF).",
      "Click **Export** next to the report you want.",
      "Use **Recent** to reopen reports you ran before. Click **Clear** to empty that list.",
    ],
    stuckTips: [
      "If it says \"Your role has no module export access\", ask the Admin to give you export rights.",
      "If you see \"No reports match this search\", clear the search or set the filter back to **All modules**.",
      "If you see \"Pick an exam term first\", choose the term before **Export**.",
      "If you see \"Your role can view homework but not download reports\", ask the Admin for export access.",
    ],
  },
  {
    id: "cbse-loc",
    paths: ["/cbse-loc"],
    pageLabel: "CBSE LOC",
    title: "CBSE List of Candidates and board registration (not built yet)",
    module: "cbse_loc",
    chipLabel: "How CBSE LOC works",
    steps: [
      "This page only says **On the roadmap**. You can't make LOC files here yet.",
      "For now, keep each Class 9–12 student's details right in **Students**: name, date of birth, parents and subjects.",
      "On **Certificates** → **Issue & register**, check that each student's PEN and APAAR ID are filled in.",
      "Check back after an update. The office will make this module visible once it's ready.",
    ],
    stuckTips: [
      "If you only see \"On the roadmap\", that's expected. This module isn't built yet.",
      "If a student's PEN or APAAR ID is missing, add it now so board registration is easier later.",
    ],
  },
];
