/**
 * Step-by-step guides for staff, store, purchase, trust and the student-life
 * screens (director, 9 Oct 2026: "a guide in every module"). Written from
 * each screen's own tabs, buttons and validation messages; `stuckTips` are
 * the screen's real error texts and what to do about them. Joined into the
 * guide list by lib/erpAiPageGuides.ts.
 */

import type { ErpAiPageGuideDef } from "@/lib/erpAiPageGuideTypes";

export const PAGE_GUIDES_A: ErpAiPageGuideDef[] = [
  {
    id: "staff-roster",
    paths: ["/staff"],
    pageLabel: "Staff",
    title: "Keep the staff register: add, import, filter and update staff",
    module: "staff",
    chipLabel: "How Staff works",
    steps: [
      "Open the **Roster** tab to see the staff cards, charts and the full staff list.",
      "Click **Add staff** (or **Add** in the toolbar) to open a new staff profile form.",
      "Fill the **Basic** tab (employee code, full name, mobile), then the **Employment**, **IDs** and **Bank** tabs, and click **Save profile**.",
      "To add many people at once, click **Import**, use **Download template**, choose the file, then click **Import staff**.",
      "Use the search box and the **Stream**, **Status**, **Department** and **Designation** filters to find people.",
      "Open a row's menu for **View & edit details**, **Attendance history**, **Salary & payslips** or **Send WhatsApp**.",
      "Tick several rows to **Mark active**, **Mark inactive** or **Send WhatsApp** in bulk; use **Download** for a CSV of the roster.",
    ],
    stuckTips: [
      "If you see \"Fix the highlighted fields before saving\", check the tab it jumps to: code and name are required, and mobile must be 10 digits.",
      "If you see \"Employee code … already exists\", give this person a different employee code on the **Basic** tab.",
      "If PAN or IFSC is rejected, use the formats AAAAA9999A (PAN) and ABCD0XXXXXX (IFSC); Aadhaar must be 12 digits.",
      "If the import says \"No rows imported — fix errors below\", correct the rows listed under the preview and choose the file again.",
    ],
  },
  {
    id: "staff-leave",
    paths: ["/staff"],
    tab: "leave",
    pageLabel: "Staff · Leave",
    title: "Request, approve and adjust staff leave",
    module: "staff",
    chipLabel: "How staff leave works",
    steps: [
      "Open the **Leave** tab on the Staff screen.",
      "To ask for leave, pick the type and dates under **Request leave** and click **Submit request**.",
      "Approvers open **Manage** and click **Approve L1** (then **Approve L2** where a second level is set up) or reject.",
      "To record leave without the approval queue, use **Direct leave** and click **Grant direct leave**.",
      "To change dates, type or half-day on a leave, use **Adjust leave** or **Adjust half-day** and click **Save adjustment**.",
      "Use **Allot leave days** to set each person's yearly leave quota.",
    ],
    stuckTips: [
      "If you see \"Insufficient … balance\", the person has used up that leave type; pick another type or allot more days first.",
      "If you see \"To date must be on or after from date\", fix the date range and submit again.",
      "If you see \"Only principal / admin can manage leave\", ask the principal or an admin to approve or adjust it.",
    ],
  },
  {
    id: "my-pay",
    paths: ["/my-pay"],
    pageLabel: "My pay & attendance",
    title: "See your own attendance, leave, payslips and advances",
    module: "home",
    chipLabel: "How My pay works",
    steps: [
      "Open the **Attendance** tab and use the arrow buttons to move between months.",
      "Tap any day on the calendar to see its status and your in and out times.",
      "Open **Leave**, choose the type, **From** and **To** dates (or tick **Half day**), add a reason and tap **Apply**.",
      "Under **My requests**, tap **Withdraw** on a pending request you no longer need.",
      "Open **Payslips** and tap a month to see earnings, deductions and net pay.",
      "Open **Advances** to see your outstanding advance and what has been recovered.",
    ],
    stuckTips: [
      "If a day shows \"Not marked\", payroll counts it as absent; ask the office to correct it before the payroll run.",
      "If you see \"Not saved — could not reach the school server\", check your internet connection and tap **Apply** again.",
      "If Payslips says \"No payslips yet\", the office has not run payroll for you; check again after the month's payroll.",
    ],
  },
  {
    id: "store-purchase-overview",
    paths: ["/inventory", "/store"],
    pageLabel: "Store & purchase",
    title: "Set up the school store, sell at the counter and buy stock",
    module: "store",
    chipLabel: "How Store works",
    steps: [
      "First time? Follow the **Store setup** steps: **Setup**, **Vendors**, **Catalogue**, **Kits by class**, then **Purchase**.",
      "In **Setup**, add categories (**New category**), units (**New unit**) and stock locations (**New location**).",
      "In **Vendors**, click **New vendor**, fill name, phone, GSTIN and payment terms, and click **Save vendor**.",
      "In **Catalogue**, click **New item** (or **Import sheet** for many), set the school sale price and GST, and click **Save item**.",
      "In **Kits by class**, click **New kit**, add items and the classes it belongs to, and click **Save kit**.",
      "Use **Counter** daily to sell, **Stock** to check what is on hand and **Reports** for registers and margins.",
    ],
    stuckTips: [
      "If you see \"Could not load the store\", click **Try again**; if it keeps failing, check your connection.",
      "If you see \"Item name is required\" or \"Vendor name is required\", fill the name before saving.",
      "If a catalogue import says \"Nothing to import yet — paste your sheet above.\", paste or choose your sheet first.",
      "If a tab you expect is missing, your login only has some store functions; ask an admin for access.",
    ],
  },
  {
    id: "store-counter",
    paths: ["/inventory", "/store"],
    tab: "counter",
    pageLabel: "Store · Counter",
    title: "Sell books, uniform and kits to a student, staff member or walk-in",
    module: "store",
    chipLabel: "How the Counter works",
    steps: [
      "Open **Counter** and choose **New sale**.",
      "Pick **Student**, **Staff** or **Walk-in**, then search the student by name, admission no., roll or parent's phone.",
      "Click the suggested kit under **Kits for** the class, or use **Add an item…** to add items one by one.",
      "Adjust **Qty** and discount on each line; use **Remove** to drop a line.",
      "Under **Payment**, choose the mode and enter **Amount taken**; leave less than the total to bill the rest.",
      "Click **Complete sale** to save and get the receipt.",
      "Use **Sales** or **Unpaid** to **Collect the balance**, **Return items** or **Cancel this sale**.",
    ],
    stuckTips: [
      "If you see \"Add the transaction ID for every payment that is not cash\", enter the UPI, card or cheque reference.",
      "If you see \"More than the total — reduce the amount taken\", lower the amount so it does not exceed the bill.",
      "If a line says the discount is \"Above the …% allowed on this item\", reduce that discount or the sale will be refused.",
      "If you see \"A walk-in sale needs a buyer name\" or \"Choose the student this sale is for\", fill in the buyer first.",
    ],
  },
  {
    id: "store-purchase",
    paths: ["/inventory", "/purchase", "/store"],
    tab: "purchase",
    pageLabel: "Store · Purchase",
    title: "Order from vendors, receive goods into stock and pay vendor bills",
    module: "purchase",
    chipLabel: "How Purchase works",
    steps: [
      "Open the **Purchase** tab and go to **Orders**; click **New order**.",
      "Pick the **Vendor**, add lines with **Add an item…**, set **Qty**, **Rate** and **GST**, then click **Save order**.",
      "From the order's menu use **Send for approval**, **Approve** and then **Send to vendor**.",
      "When goods arrive, open **Receive goods**, pick the order (or leave empty for a cash purchase) and click **Post receipt**.",
      "Open **Bills to pay**, click **Pay** on a bill, fill amount, date and mode, then click **Record payment**.",
      "For damaged or wrong goods, open **Returns**, click **New return**, pick the goods receipt and click **Post return**.",
    ],
    stuckTips: [
      "If you see \"This order is above the approval limit — submit it for approval first\", use **Send for approval** and wait for **Approve**.",
      "If you see \"A purchase order needs at least one line\" or \"A vendor is required\", add a vendor and at least one item.",
      "If you see \"Enter a received quantity on at least one line\", type how many arrived before clicking **Post receipt**.",
      "If a payment is refused, the amount \"Cannot be more than the outstanding balance\"; check the bill's balance.",
    ],
  },
  {
    id: "store-stock",
    paths: ["/inventory", "/store"],
    tab: "stock",
    pageLabel: "Store · Stock",
    title: "Check stock on hand, move stock and record physical counts",
    module: "store",
    chipLabel: "How Stock works",
    steps: [
      "Open the **Stock** tab; **On hand** shows each item's quantity, average cost and value.",
      "Use the location filter to see one store room, or **All locations**.",
      "From an item's menu, choose **Stock history** to see every movement in and out.",
      "Choose **Move between locations**, set **From**, **To** and **Quantity**, and save.",
      "Choose **Physical count**, enter the **Counted quantity** and a **Reason**, and click **Record count**.",
      "Switch to **Asset register** for tagged items such as furniture and equipment.",
    ],
    stuckTips: [
      "If you see \"Only … in stock at the source location\", move a smaller quantity or pick another source location.",
      "If you see \"Source and destination must be different\", choose a different **To** location.",
      "If you see \"A reason is required for a stock adjustment\", type why the count differs before recording it.",
    ],
  },
  {
    id: "trust-construction",
    paths: ["/trust"],
    pageLabel: "Trust · Construction",
    title: "Track trust building projects: BOQ, materials, labour, bills and CWIP",
    module: "trust",
    chipLabel: "How Trust works",
    steps: [
      "Open **Projects**, enter the project name and sanctioned budget, and click **Save project**.",
      "In **Works**, pick the project and add BOQ lines with **Add work**.",
      "Record site materials in **Materials** with **Save material**, and daily labour in **Labour** with **Save labour**.",
      "In **Allotments**, assign a work to staff or a contractor with **Allot**; later **Verify completed work**.",
      "In **Bills & CWIP**, **Save contractor**, **Create WO**, **Submit RA**, then **Approve** and **Pay** the RA bill.",
      "When the project is done, click **Capitalise project** to move its cost into fixed assets.",
      "Use **Reports** to export project reports as **Excel** or **PDF**.",
    ],
    stuckTips: [
      "If you see \"Select a project first\", pick the project at the top of the tab before adding lines.",
      "If you see \"Add a contractor first\" or \"Create a work order first\", complete those steps in **Bills & CWIP** in order.",
      "If you see \"Bill must be approved before payment\", click **Approve** on the RA bill, then **Pay**.",
      "If you see \"No spent amount to capitalise\", pay at least one bill or cost line before capitalising.",
    ],
  },
  {
    id: "budget",
    paths: ["/budget"],
    pageLabel: "Operating budget",
    title: "Annual budget planning vs. actuals (coming soon)",
    module: "opex_budget",
    chipLabel: "How Budget works",
    steps: [
      "This screen is on the roadmap and is not built yet, so there is nothing to fill in here.",
      "It is shown in **Settings → Modules** only so you know it is coming.",
      "Until it ships, track spending in the Accounts module.",
    ],
    stuckTips: [
      "If you see \"On the roadmap\", that is expected; the screen has no actions yet.",
      "If you need budget figures now, ask the accounts office for an Accounts report.",
    ],
  },
];
