/**
 * Bilingual strings for the gate visitor flow (public /visit page, the
 * printed gate poster, and the reception register). Hindi is written for a
 * gateman / parent who may not read English; keep sentences short.
 */

export type VisitorLang = "en" | "hi";

export const VISITOR_PURPOSE_HI: Record<string, string> = {
  admission: "एडमिशन पूछताछ",
  meeting: "स्टाफ से मिलना",
  vendor: "वेंडर / सप्लायर",
  delivery: "डिलीवरी",
  job_interview: "नौकरी इंटरव्यू",
  other: "अन्य",
};

export const VISITOR_STRINGS = {
  en: {
    appTitle: "Visitor check-in",
    schoolGate: "School gate",
    langToggle: "हिन्दी में देखें",
    step1: "Enter your mobile number",
    mobilePlaceholder: "10-digit mobile number",
    next: "Next",
    checking: "Checking…",
    welcome: "Welcome",
    weFound: "We found you in our records",
    parentOf: "Parent / guardian of",
    admissionLead: "Admission enquiry for",
    notOnFile: "You are not in our records yet — please enter your name",
    yourName: "Your name",
    purpose: "Purpose of visit",
    personToMeet: "Whom do you want to meet? (optional)",
    checkIn: "Check in",
    checkingIn: "Checking in…",
    checkedIn: "You are checked in",
    alreadyIn: "You are already checked in today",
    visitorNo: "Visitor number",
    inTime: "In time",
    outTime: "Out time",
    showAtGate: "Show this screen at the gate. Scan the same QR when you leave to check out.",
    checkOut: "Check out",
    checkingOut: "Checking out…",
    checkedOut: "Checked out. Thank you for visiting.",
    checkOutPrompt: "Leaving? Enter your mobile number to check out.",
    startOver: "New visitor",
    error: "Something went wrong. Please ask at the reception.",
    invalidMobile: "Enter a valid 10-digit mobile number",
    stage: "Stage",
    classLabel: "Class",
    keepPhone: "Please keep your phone with you during the visit.",
    printedBy: "Generated by BHB International School ERP",
  },
  hi: {
    appTitle: "विज़िटर चेक-इन",
    schoolGate: "स्कूल गेट",
    langToggle: "View in English",
    step1: "अपना मोबाइल नंबर लिखें",
    mobilePlaceholder: "10 अंकों का मोबाइल नंबर",
    next: "आगे",
    checking: "जाँच हो रही है…",
    welcome: "स्वागत है",
    weFound: "आपका रिकॉर्ड हमारे पास मिला",
    parentOf: "अभिभावक हैं —",
    admissionLead: "एडमिशन पूछताछ —",
    notOnFile: "आपका रिकॉर्ड नहीं मिला — कृपया अपना नाम लिखें",
    yourName: "आपका नाम",
    purpose: "आने का उद्देश्य",
    personToMeet: "किससे मिलना है? (वैकल्पिक)",
    checkIn: "चेक-इन करें",
    checkingIn: "चेक-इन हो रहा है…",
    checkedIn: "आपका चेक-इन हो गया",
    alreadyIn: "आज आपका चेक-इन पहले से है",
    visitorNo: "विज़िटर नंबर",
    inTime: "आने का समय",
    outTime: "जाने का समय",
    showAtGate: "यह स्क्रीन गेट पर दिखाएँ। जाते समय वही QR स्कैन करके चेक-आउट करें।",
    checkOut: "चेक-आउट करें",
    checkingOut: "चेक-आउट हो रहा है…",
    checkedOut: "चेक-आउट हो गया। पधारने के लिए धन्यवाद।",
    checkOutPrompt: "जा रहे हैं? चेक-आउट के लिए मोबाइल नंबर लिखें।",
    startOver: "नया विज़िटर",
    error: "कुछ गड़बड़ हुई। कृपया रिसेप्शन पर पूछें।",
    invalidMobile: "सही 10 अंकों का मोबाइल नंबर लिखें",
    stage: "स्थिति",
    classLabel: "कक्षा",
    keepPhone: "कृपया विज़िट के दौरान अपना फ़ोन साथ रखें।",
    printedBy: "BHB International School ERP द्वारा जारी",
  },
} as const;

export type VisitorStrings = { [K in keyof (typeof VISITOR_STRINGS)["en"]]: string };

export function visitorStrings(lang: VisitorLang): VisitorStrings {
  return VISITOR_STRINGS[lang];
}

/** Gate poster steps — printed under the QR in both languages. */
export const GATE_POSTER_STEPS = {
  en: [
    "Scan this QR with your phone camera.",
    "Enter your mobile number.",
    "Choose why you are visiting and press Check in.",
    "You get a visitor number — show it at the gate.",
    "When leaving, scan again and press Check out.",
  ],
  hi: [
    "अपने फ़ोन के कैमरे से यह QR स्कैन करें।",
    "अपना मोबाइल नंबर लिखें।",
    "आने का कारण चुनें और चेक-इन दबाएँ।",
    "आपको विज़िटर नंबर मिलेगा — गेट पर दिखाएँ।",
    "जाते समय फिर स्कैन करें और चेक-आउट दबाएँ।",
  ],
};

/** Poster: the WhatsApp alternative (second QR → wa.me/<school>?text=VISIT). */
export const GATE_WA_POSTER_STEPS = {
  en: [
    "Scan this QR — WhatsApp opens with the school number.",
    "Send the message VISIT (already typed for you).",
    "The school bot greets you by name — choose your purpose from the list.",
    "You get a visitor number on WhatsApp — show it at the gate.",
    "When leaving, send OUT to check out.",
  ],
  hi: [
    "यह QR स्कैन करें — स्कूल के नंबर पर WhatsApp खुलेगा।",
    "VISIT संदेश भेजें (पहले से लिखा मिलेगा)।",
    "स्कूल बॉट आपका नाम लेकर स्वागत करेगा — सूची से कारण चुनें।",
    "WhatsApp पर विज़िटर नंबर मिलेगा — गेट पर दिखाएँ।",
    "जाते समय OUT भेजकर चेक-आउट करें।",
  ],
};
